Repository SeleniumHQ/selenium, pull requests merged in 2018-10, with the labels that each got.

#6459 [Py] Safari 12 webdriver legacy arg
  py/selenium/webdriver/safari/service.py
  py/selenium/webdriver/safari/webdriver.py
  py/test/selenium/webdriver/safari/launcher_tests.py
Labels: C-py

#6552 Adding support for OSX mojave to grid
  java/client/src/org/openqa/selenium/Platform.java
Labels: C-grid

#6491 Added Locale.US for USER_AGENT toLowerCase
  java/client/src/org/openqa/selenium/remote/http/HttpClient.java
Labels: C-java
