Repository SeleniumHQ/selenium, pull requests merged in 2018-07, with the labels that each got.

#6112 Add cause when JsonException occurs
  java/client/src/org/openqa/selenium/remote/ProtocolHandshake.java
Labels: C-java

#6029 Fix test to work with newer byte-buddy
  java/client/test/org/openqa/selenium/remote/BaseAugmenterTest.java
Labels: C-java, R-awaits CLA confirmation

#5933 Add until.urlContains null value check
  javascript/node/selenium-webdriver/lib/until.js
Labels: C-nodejs

#6172 [py] fix: drag and drop by offset broken (#6171)
  py/selenium/webdriver/common/action_chains.py
Labels: C-py

#6183 fix unable to disable native events on IE driver version 3.4+ issue
  java/client/src/org/openqa/selenium/ie/InternetExplorerOptions.java
Labels: C-java

#5979 Be consistent with webdriver init kwarg service_log_path
  py/selenium/webdriver/edge/webdriver.py
  py/selenium/webdriver/firefox/webdriver.py
  py/selenium/webdriver/ie/webdriver.py
  py/test/selenium/webdriver/firefox/ff_launcher_tests.py
  py/test/selenium/webdriver/marionette/mn_launcher_tests.py
Labels: C-py

#6189 constant default_move_duration prevents appium to override it
  rb/lib/selenium/webdriver/common/interactions/pointer_actions.rb
  rb/spec/unit/selenium/webdriver/common/interactions/pointer_actions_spec.rb
Labels: C-rb

#6158 A Hub API that can query all running sessions.
  java/server/src/org/openqa/grid/web/Hub.java
  java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java
  java/server/test/org/openqa/grid/e2e/GridE2ETests.java
  java/server/test/org/openqa/grid/e2e/misc/GridListActiveSessionsTest.java
  java/server/test/org/openqa/grid/e2e/node/SmokeTest.java
Labels: C-grid

#6137 Restore missing error class and limit error class lookup scope - Fixes Issue 6122
  rb/lib/selenium/webdriver/common/error.rb
Labels: C-rb
