Repository SeleniumHQ/selenium, pull requests merged in 2019-04, with the labels that each got.

#6965 [rb] move driver responsibilities into Service class
  rb/lib/selenium/webdriver/chrome.rb
  rb/lib/selenium/webdriver/chrome/driver.rb
  rb/lib/selenium/webdriver/chrome/service.rb
  rb/lib/selenium/webdriver/common/driver.rb
  rb/lib/selenium/webdriver/common/service.rb
  rb/lib/selenium/webdriver/edge.rb
  rb/lib/selenium/webdriver/edge/driver.rb
  rb/lib/selenium/webdriver/edge/service.rb
  rb/lib/selenium/webdriver/firefox.rb
  rb/lib/selenium/webdriver/firefox/marionette/driver.rb
  rb/lib/selenium/webdriver/firefox/service.rb
  rb/lib/selenium/webdriver/ie.rb
  rb/lib/selenium/webdriver/ie/driver.rb
  rb/lib/selenium/webdriver/ie/service.rb
  rb/lib/selenium/webdriver/safari.rb
  rb/lib/selenium/webdriver/safari/driver.rb
  rb/lib/selenium/webdriver/safari/service.rb
  rb/spec/unit/selenium/webdriver/chrome/service_spec.rb
  rb/spec/unit/selenium/webdriver/common/service_spec.rb
  rb/spec/unit/selenium/webdriver/edge/service_spec.rb
  rb/spec/unit/selenium/webdriver/firefox/service_spec.rb
  rb/spec/unit/selenium/webdriver/ie/service_spec.rb
  rb/spec/unit/selenium/webdriver/phantomjs/driver_spec.rb
  rb/spec/unit/selenium/webdriver/phantomjs/service_spec.rb
  rb/spec/unit/selenium/webdriver/safari/service_spec.rb
Labels: C-rb

#7075 switch to parent frame fix for non-w3c compatible drivers
  javascript/node/selenium-webdriver/lib/http.js
  javascript/node/selenium-webdriver/test/frame_test.js
Labels: C-nodejs

#6935 capabilities.js - used unused variable in merge()
  javascript/node/selenium-webdriver/lib/capabilities.js
  javascript/node/selenium-webdriver/test/lib/capabilities_test.js
Labels: C-nodejs

#6989 [rb] rename WebDriver::Options class to WebDriver::Manage
  rb/lib/selenium/webdriver/common.rb
  rb/lib/selenium/webdriver/common/driver.rb
  rb/lib/selenium/webdriver/common/manager.rb
  rb/lib/selenium/webdriver/common/w3c_manager.rb
  rb/lib/selenium/webdriver/remote/oss/bridge.rb
  rb/lib/selenium/webdriver/remote/w3c/bridge.rb
  rb/spec/integration/selenium/webdriver/manage_spec.rb
Labels: C-rb

#6994 [py] Raise error for unsupported method
  py/selenium/webdriver/remote/webdriver.py
Labels: C-py

#7123 [py] license specified twice in setup
  py/setup.py
Labels: C-py
