Repository SeleniumHQ/selenium, pull requests merged in 2019-12, with the labels that each got.

#7839 Add: Add support to get property of referenced web element
  javascript/node/selenium-webdriver/lib/command.js
  javascript/node/selenium-webdriver/lib/http.js
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/test/actions_test.js
Labels: C-nodejs

#7850 Add: Added W3C capability strictFileInteractability(c-nodejs)
  javascript/node/selenium-webdriver/lib/capabilities.js
  javascript/node/selenium-webdriver/lib/test/fileserver.js
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/test/lib/capabilities_test.js
Labels: C-nodejs

#7633 Update EdgeOptions constructor to use new ms:edgeOptions capability name
  dotnet/src/webdriver/Edge/EdgeOptions.cs
  java/client/src/org/openqa/selenium/edge/EdgeOptions.java
Labels: C-dotnet, D-edge

#7893 [rb] Fix deprecation warnings for Ruby 2.7 in 3.x
  rb/lib/selenium/webdriver/chrome/driver.rb
  rb/lib/selenium/webdriver/edge/driver.rb
  rb/lib/selenium/webdriver/firefox/marionette/driver.rb
  rb/lib/selenium/webdriver/ie/driver.rb
  rb/lib/selenium/webdriver/phantomjs/driver.rb
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/lib/selenium/webdriver/safari/driver.rb
Labels: C-rb
