Repository SeleniumHQ/selenium, pull requests merged in 2019-06, with the labels that each got.

#7257 Add Chrome based Edge to the Ruby bindings
  rb/build.desc
  rb/lib/selenium/webdriver.rb
  rb/lib/selenium/webdriver/common/driver.rb
  rb/lib/selenium/webdriver/common/service.rb
  rb/lib/selenium/webdriver/edge.rb
  rb/lib/selenium/webdriver/edge_chrome/bridge.rb
  rb/lib/selenium/webdriver/edge_chrome/driver.rb
  rb/lib/selenium/webdriver/edge_chrome/options.rb
  rb/lib/selenium/webdriver/edge_chrome/profile.rb
  rb/lib/selenium/webdriver/edge_chrome/service.rb
  rb/lib/selenium/webdriver/edge_html/driver.rb
  rb/lib/selenium/webdriver/edge_html/options.rb
  rb/lib/selenium/webdriver/edge_html/service.rb
  rb/lib/selenium/webdriver/remote/capabilities.rb
  rb/spec/integration/selenium/webdriver/action_builder_spec.rb
  rb/spec/integration/selenium/webdriver/edge_chrome/driver_spec.rb
  rb/spec/integration/selenium/webdriver/edge_chrome/options_spec.rb
  rb/spec/integration/selenium/webdriver/edge_chrome/profile_spec.rb
  rb/spec/integration/selenium/webdriver/edge_chrome/sample.crx
  rb/spec/integration/selenium/webdriver/manager_spec.rb
  rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb
  rb/spec/integration/selenium/webdriver/storage_spec.rb
  rb/spec/integration/selenium/webdriver/window_spec.rb
  rb/spec/unit/selenium/webdriver/edge/driver_spec.rb
  rb/spec/unit/selenium/webdriver/edge/options_spec.rb
  rb/spec/unit/selenium/webdriver/edge/service_spec.rb
Labels: C-rb

#7287 [rb] Add missing verification in timeout_spec.rb
  rb/spec/integration/selenium/webdriver/timeout_spec.rb
Labels: C-rb

#6787 Enable support for browser_specific_settings in Firefox
  javascript/node/selenium-webdriver/firefox.js
Labels: C-nodejs

#6983 Added socksVersion field in proxy class
  py/selenium/webdriver/common/proxy.py
  py/test/selenium/webdriver/common/proxy_tests.py
Labels: C-py

#7276 Add log extension commands coming in chromedriver 76/77 to Chrome bridge
  rb/lib/selenium/webdriver/chrome/bridge.rb
Labels: C-rb
