Repository SeleniumHQ/selenium, pull requests merged in 2020-03, with the labels that each got.

#7901 Add: Adding new cookie sameSite (c-nodejs)
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/test/cookie_test.js
Labels: C-nodejs

#7464 node/selenium-webdriver/firefox.js: accept zip webextensions
  javascript/node/selenium-webdriver/firefox.js
  javascript/node/selenium-webdriver/lib/test/data/firefox/webextension.zip
  javascript/node/selenium-webdriver/test/firefox_test.js
Labels: C-nodejs

#8066 Cleanup temporary directories even if non-empty
  javascript/node/selenium-webdriver/io/index.js
Labels: C-nodejs, I-defect

#6375 [py] Add WPEWebKit driver
  py/selenium/webdriver/__init__.py
  py/selenium/webdriver/common/desired_capabilities.py
  py/selenium/webdriver/wpewebkit/__init__.py
  py/selenium/webdriver/wpewebkit/options.py
  py/selenium/webdriver/wpewebkit/service.py
  py/selenium/webdriver/wpewebkit/webdriver.py
Labels: A-needs decision, C-py

#8098 Fixed typos in EdgeDriverService.cs
  dotnet/src/webdriver/Edge/EdgeDriverService.cs
Labels: C-dotnet

#8118 Add: Adding sameSite cookie attribute for rb bindings
  rb/lib/selenium/webdriver/common/manager.rb
  rb/spec/integration/selenium/webdriver/manager_spec.rb
Labels: C-rb

#8105 [java] Use a capability to switch engines for Edge
  java/client/src/org/openqa/selenium/chrome/ChromeDriver.java
  java/client/src/org/openqa/selenium/chromium/ChromiumDriverCommandExecutor.java
  java/client/src/org/openqa/selenium/edge/ChromiumEdgeDriverService.java
  java/client/src/org/openqa/selenium/edge/EdgeDriver.java
  java/client/src/org/openqa/selenium/edge/EdgeDriverInfo.java
  java/client/src/org/openqa/selenium/edge/EdgeOptions.java
  java/client/src/org/openqa/selenium/edge/edgehtml/EdgeHtmlDriverService.java
  java/client/test/com/thoughtworks/selenium/InternalSelenseTestBase.java
  java/client/test/org/openqa/selenium/testing/drivers/TestEdgeDriver.java
  java/client/test/org/openqa/selenium/testing/drivers/WebDriverBuilder.java
Labels: C-java

#8102 Add non-nullable modifier to return type of functions never returning null
  javascript/atoms/frame.js
  javascript/atoms/html5/storage.js
  javascript/atoms/locators/link_text.js
  javascript/atoms/locators/tag_name.js
Labels: C-nodejs

#8094 Support functions for message in driver.wait()
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/test/lib/webdriver_test.js
Labels: C-nodejs

#7482 Add sendDevToolsCommandAndGetReturn to Javascript Chrome webdriver.
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/chrome.js
  javascript/node/selenium-webdriver/test/chrome/devtools_test.js
Labels: C-nodejs

#7938 Send and get CDP command from NodeJS for Chrome.
  javascript/node/selenium-webdriver/chrome.js
  javascript/node/selenium-webdriver/test/chrome/devtools_test.js
Labels: C-nodejs

#8141 Small refactoring to RemoteWebDriver: remove code duplication in a constructor
  java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java
Labels: C-java
