Repository SeleniumHQ/selenium, pull requests merged in 2020-06, with the labels that each got.

#8408 Ruby - stop using an obsolete method of Net::HTTP
  rb/lib/selenium/server.rb
  rb/lib/selenium/webdriver/remote/http/default.rb
  rb/spec/unit/selenium/server_spec.rb
Labels: C-rb

#7704 WIP: Adding sonar sources for java,rb,py
  sonar-project.properties
Labels: C-build

#7395 Catch the NoSuchElementException if the element is not present in DOM
  java/client/src/org/openqa/selenium/support/ui/ExpectedConditions.java
Labels: C-java
