Repository SeleniumHQ/selenium, pull requests merged in 2020-04, with the labels that each got.

#7832 Implement w3c parameters for options class
  rb/lib/selenium/webdriver/chrome/options.rb
  rb/lib/selenium/webdriver/common/driver.rb
  rb/lib/selenium/webdriver/common/options.rb
  rb/lib/selenium/webdriver/edge_chrome/options.rb
  rb/lib/selenium/webdriver/edge_html/options.rb
  rb/lib/selenium/webdriver/firefox/options.rb
  rb/lib/selenium/webdriver/ie/options.rb
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/lib/selenium/webdriver/safari/options.rb
  rb/spec/unit/selenium/webdriver/chrome/driver_spec.rb
  rb/spec/unit/selenium/webdriver/chrome/options_spec.rb
  rb/spec/unit/selenium/webdriver/edge/driver_spec.rb
  rb/spec/unit/selenium/webdriver/edge/options_spec.rb
  rb/spec/unit/selenium/webdriver/firefox/driver_spec.rb
  rb/spec/unit/selenium/webdriver/firefox/options_spec.rb
  rb/spec/unit/selenium/webdriver/ie/driver_spec.rb
  rb/spec/unit/selenium/webdriver/ie/options_spec.rb
  rb/spec/unit/selenium/webdriver/remote/bridge_spec.rb
  rb/spec/unit/selenium/webdriver/remote/driver_spec.rb
  rb/spec/unit/selenium/webdriver/safari/driver_spec.rb
  rb/spec/unit/selenium/webdriver/safari/options_spec.rb
Labels: C-rb

#7820 [rb] convert Bridge modules to subclasses
  rb/lib/selenium/webdriver/chrome/bridge.rb
  rb/lib/selenium/webdriver/chrome/driver.rb
  rb/lib/selenium/webdriver/common/driver.rb
  rb/lib/selenium/webdriver/edge_chrome/bridge.rb
  rb/lib/selenium/webdriver/edge_chrome/driver.rb
  rb/lib/selenium/webdriver/firefox/bridge.rb
  rb/lib/selenium/webdriver/firefox/driver.rb
  rb/lib/selenium/webdriver/safari/bridge.rb
  rb/lib/selenium/webdriver/safari/driver.rb
Labels: C-rb

#8054 Add: Added Missing 'fileUploadDialogTimeout' capability in JS bindings
  javascript/node/selenium-webdriver/ie.js
  javascript/node/selenium-webdriver/test/ie/options_test.js
Labels: C-nodejs, D-IE

#6536 [py] verify command_executor ssl certificate by default
  py/selenium/webdriver/remote/remote_connection.py
  py/setup.py
  py/test/selenium/webdriver/remote/remote_hub_connection.py
  py/tox.ini
  third_party/py/asn1crypto-0.24.0-py2.py3-none-any.whl
  third_party/py/certifi-2018.8.24-py2.py3-none-any.whl
  third_party/py/cffi-1.11.5.tar.gz
  third_party/py/cryptography-2.3.1.tar.gz
  third_party/py/enum34-1.1.6-py3-none-any.whl
  third_party/py/idna-2.7-py2.py3-none-any.whl
  third_party/py/ipaddress-1.0.22-py2.py3-none-any.whl
  third_party/py/pyOpenSSL-18.0.0-py2.py3-none-any.whl
  third_party/py/pycparser-2.19.tar.gz
  third_party/py/six-1.11.0-py2.py3-none-any.whl
Labels: C-py

#3481 Fix erro in webelemet not created, verifing if is str or dict.
  py/selenium/webdriver/support/expected_conditions.py
Labels: C-py

#7037 Check if argument is iterable. E.g. type **list** also works.
  py/selenium/webdriver/support/expected_conditions.py
Labels: C-py

#6974 Fix comments on Java Actions.moveToElement
  java/client/src/org/openqa/selenium/interactions/Actions.java
Labels: C-java

#8206 [rb] fix: cdp for edge from goog to ms to match the vendor prefix
  rb/lib/selenium/webdriver/edge_chrome/bridge.rb
Labels: C-rb
