Repository SeleniumHQ/selenium, pull requests merged in 2021-04, with the labels that each got.

#9357 [java] Set logging level to the logger when method is called
  java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java
Labels: C-java

#6785 make isPromise() return boolean value for null and undefined cases
  javascript/node/selenium-webdriver/test/lib/promise_test.js
Labels: C-nodejs, R-awaiting answer

#9362 [JS] Remove legacy action API support
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/lib/actions.js
  javascript/node/selenium-webdriver/lib/command.js
  javascript/node/selenium-webdriver/lib/http.js
  javascript/node/selenium-webdriver/lib/input.js
  javascript/node/selenium-webdriver/test/chrome/devtools_test.js
  javascript/node/selenium-webdriver/test/lib/input_test.js
Labels: C-nodejs

#9335 [rb] fix bugs and allow saving print page
  rb/lib/selenium/webdriver/common/driver_extensions/prints_page.rb
  rb/lib/selenium/webdriver/remote/driver.rb
  rb/spec/integration/selenium/webdriver/chrome/driver_spec.rb
Labels: C-rb

#9336 [py] Allow overriding the default 250 msecs duration of pointer movement
  py/selenium/webdriver/common/action_chains.py
  py/selenium/webdriver/common/actions/action_builder.py
  py/selenium/webdriver/common/actions/pointer_actions.py
Labels: C-py

#9374 [py] Expand element to be clickable
  py/selenium/webdriver/support/expected_conditions.py
  py/test/selenium/webdriver/support/expected_conditions_tests.py
Labels: C-py

#9330 [py] Fix converting list of tuples to str in send_keys
  py/selenium/webdriver/remote/webelement.py
  py/test/selenium/webdriver/common/upload_tests.py
Labels: C-py

#7897 [js] Add windowTypes option support for ChromiumDriver
  javascript/node/selenium-webdriver/chromium.js
  javascript/node/selenium-webdriver/test/chrome/options_test.js
Labels: C-nodejs, R-awaiting answer

#9405 Rework the LocalNewSessionQueue to be simpler
  java/server/src/org/openqa/selenium/grid/data/NewSessionResponse.java
  java/server/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/server/src/org/openqa/selenium/grid/sessionqueue/NewSessionQueue.java
  java/server/src/org/openqa/selenium/grid/sessionqueue/SessionCreated.java
  java/server/src/org/openqa/selenium/grid/sessionqueue/SessionNotCreated.java
  java/server/src/org/openqa/selenium/grid/sessionqueue/local/GetNewSessionResponse.java
  java/server/src/org/openqa/selenium/grid/sessionqueue/local/LocalNewSessionQueue.java
  java/server/src/org/openqa/selenium/grid/sessionqueue/local/NewSessionRequest.java
  java/server/src/org/openqa/selenium/grid/sessionqueue/local/SessionRequests.java
  java/server/src/org/openqa/selenium/grid/sessionqueue/remote/RemoteNewSessionQueue.java
  java/server/test/org/openqa/selenium/grid/graphql/GraphqlHandlerTest.java
  java/server/test/org/openqa/selenium/grid/sessionqueue/local/BUILD.bazel
  java/server/test/org/openqa/selenium/grid/sessionqueue/local/LocalNewSessionQueueTest.java
  java/server/test/org/openqa/selenium/grid/sessionqueue/local/SessionRequestsTest.java
Labels: A-tests failed, C-grid, Selenium-4-Beta
