Repository SeleniumHQ/selenium, pull requests merged in 2022-06, with the labels that each got.

#10741 [java] Throwing warnings for non-W3C before creating session
  java/src/org/openqa/selenium/PersistentCapabilities.java
  java/src/org/openqa/selenium/SharedCapabilitiesMethods.java
  java/src/org/openqa/selenium/W3CCapabilityKeysValidator.java
  java/src/org/openqa/selenium/remote/RemoteWebDriver.java
  java/src/org/openqa/selenium/remote/RemoteWebDriverBuilder.java
Labels: C-java

#10631 [py] Additional types and tweaks for remote webdriver
  py/selenium/webdriver/remote/file_detector.py
  py/selenium/webdriver/remote/webdriver.py
Labels: C-py

#10627 [py] additional type hints in wait.py & command.py
  py/selenium/types.py
  py/selenium/webdriver/remote/command.py
  py/selenium/webdriver/support/wait.py
Labels: C-py

#10647 [py] python3.7+ syntax throughout `*.py` files.
  py/conftest.py
  py/docs/source/conf.py
  py/generate.py
  py/selenium/common/exceptions.py
  py/selenium/webdriver/chrome/service.py
  py/selenium/webdriver/chrome/webdriver.py
  py/selenium/webdriver/chromium/options.py
  py/selenium/webdriver/chromium/remote_connection.py
  py/selenium/webdriver/common/actions/interaction.py
  py/selenium/webdriver/common/actions/key_actions.py
  py/selenium/webdriver/common/actions/key_input.py
  py/selenium/webdriver/common/actions/pointer_actions.py
  py/selenium/webdriver/common/actions/pointer_input.py
  py/selenium/webdriver/common/actions/wheel_actions.py
  py/selenium/webdriver/common/bidi/cdp.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/edge/options.py
  py/selenium/webdriver/edge/service.py
  py/selenium/webdriver/edge/webdriver.py
  py/selenium/webdriver/firefox/firefox_profile.py
  py/selenium/webdriver/firefox/options.py
  py/selenium/webdriver/firefox/webdriver.py
  py/selenium/webdriver/ie/options.py
  py/selenium/webdriver/remote/errorhandler.py
  py/selenium/webdriver/remote/remote_connection.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/webelement.py
  py/selenium/webdriver/safari/options.py
  py/selenium/webdriver/support/color.py
  py/selenium/webdriver/support/event_firing_webdriver.py
  py/selenium/webdriver/webkitgtk/options.py
  py/selenium/webdriver/wpewebkit/options.py
  py/test/selenium/webdriver/common/alerts_tests.py
  py/test/selenium/webdriver/common/api_example_tests.py
  py/test/selenium/webdriver/common/cookie_tests.py
  py/test/selenium/webdriver/common/executing_async_javascript_tests.py
  py/test/selenium/webdriver/common/interactions_tests.py
  py/test/selenium/webdriver/common/network.py
  py/test/selenium/webdriver/common/w3c_interaction_tests.py
  py/test/selenium/webdriver/common/webserver.py
  py/test/selenium/webdriver/support/event_firing_webdriver_tests.py
  py/test/unit/selenium/webdriver/chrome/chrome_options_tests.py
  py/test/unit/selenium/webdriver/remote/new_session_tests.py
  py/test/unit/selenium/webdriver/remote/subtyping_tests.py
Labels: C-py

#10630 [py] remove `opera`
  py/MANIFEST.in
  py/docs/source/api.rst
  py/docs/source/webdriver_opera/selenium.webdriver.opera.webdriver.rst
  py/selenium/webdriver/__init__.py
  py/selenium/webdriver/common/desired_capabilities.py
  py/selenium/webdriver/opera/__init__.py
  py/selenium/webdriver/opera/options.py
  py/selenium/webdriver/opera/webdriver.py
  py/setup.py
  py/test/unit/selenium/webdriver/opera/opera_options_tests.py
  py/test/unit/selenium/webdriver/remote/new_session_tests.py
Labels: C-py

#10764 [JS] Fix: using fulfillRequest when intercepting
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/test/devtools_test.js
Labels: C-nodejs

#10811 #10810 pick the right target using given window handle
  java/src/org/openqa/selenium/chromium/ChromiumDriver.java
  java/src/org/openqa/selenium/devtools/DevTools.java
  java/src/org/openqa/selenium/devtools/NetworkInterceptor.java
  java/src/org/openqa/selenium/devtools/events/CdpEventTypes.java
  java/test/org/openqa/selenium/devtools/DevToolsTestBase.java
  java/test/org/openqa/selenium/grid/router/DistributedCdpTest.java
Labels: C-java, C-devtools
