Repository SeleniumHQ/selenium, pull requests merged in 2022-09, with the labels that each got.

#10992 Fix javadoc
  java/src/org/openqa/selenium/JavascriptExecutor.java
Labels: C-java

#10998 [java] Ensure event firing decorator can accept a target class
  java/src/org/openqa/selenium/support/events/EventFiringDecorator.java
  java/test/org/openqa/selenium/support/BUILD.bazel
  java/test/org/openqa/selenium/support/events/BUILD.bazel
  java/test/org/openqa/selenium/support/events/EventFiringDecoratorTest.java
Labels: C-java

#10938 Ie find edge
  cpp/iedriver/BrowserFactory.cpp
  cpp/iedriver/BrowserFactory.h
Labels: D-IE

#11053 [py]: add type hints for method parameters
  py/selenium/webdriver/remote/webdriver.py
Labels: C-py

#11051 Remove spelling mistake from the method name
  py/selenium/webdriver/remote/remote_connection.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py

#11048 isPromise() thenable fix
  javascript/node/selenium-webdriver/lib/util.js
  javascript/node/selenium-webdriver/test/lib/promise_test.js
Labels: C-nodejs
