Repository SeleniumHQ/selenium, pull requests merged in 2022-05, with the labels that each got.

#10461 [py] Port to new style classes
  py/conftest.py
  py/selenium/webdriver/common/action_chains.py
  py/selenium/webdriver/common/actions/action_builder.py
  py/selenium/webdriver/common/actions/input_device.py
  py/selenium/webdriver/common/actions/interaction.py
  py/selenium/webdriver/common/actions/mouse_button.py
  py/selenium/webdriver/common/alert.py
  py/selenium/webdriver/common/by.py
  py/selenium/webdriver/common/desired_capabilities.py
  py/selenium/webdriver/common/html5/application_cache.py
  py/selenium/webdriver/common/keys.py
  py/selenium/webdriver/common/proxy.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/common/timeouts.py
  py/selenium/webdriver/common/window.py
  py/selenium/webdriver/firefox/firefox_binary.py
  py/selenium/webdriver/firefox/firefox_profile.py
  py/selenium/webdriver/firefox/options.py
  py/selenium/webdriver/remote/command.py
  py/selenium/webdriver/remote/errorhandler.py
  py/selenium/webdriver/remote/mobile.py
  py/selenium/webdriver/remote/remote_connection.py
  py/selenium/webdriver/safari/options.py
  py/selenium/webdriver/safari/permissions.py
  py/selenium/webdriver/support/abstract_event_listener.py
  py/selenium/webdriver/support/color.py
  py/selenium/webdriver/support/event_firing_webdriver.py
  py/selenium/webdriver/support/relative_locator.py
  py/selenium/webdriver/support/select.py
  py/selenium/webdriver/support/wait.py
  py/test/selenium/webdriver/common/google_one_box.py
  py/test/selenium/webdriver/common/results_page.py
  py/test/selenium/webdriver/common/webdriverwait_tests.py
  py/test/selenium/webdriver/common/webserver.py
  py/test/selenium/webdriver/marionette/mn_options_tests.py
  py/test/selenium/webdriver/safari/launcher_tests.py
  py/test/unit/selenium/webdriver/remote/subtyping_tests.py
Labels: C-py

#10653 [py] fix: SecurityError: Invalid Domain problem
  common/src/web/virtual-authenticator.html
  py/conftest.py
  py/selenium/webdriver/common/virtual_authenticator.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/virtual_authenticator_tests.py
  py/test/selenium/webdriver/common/webserver.py
Labels: C-py

#10674 [java] Include JMX monitoring feature in the Grid local distributor
  java/src/org/openqa/selenium/grid/distributor/local/BUILD.bazel
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/test/org/openqa/selenium/grid/router/JmxTest.java
Labels: C-java

#10656 [py] simplify boolean checks for `_identify_http_proxy_auth`
  py/selenium/webdriver/remote/remote_connection.py
Labels: C-py

#10537 [py] Tidy up python exception handling
  py/selenium/webdriver/remote/switch_to.py
  py/selenium/webdriver/remote/webelement.py
  py/selenium/webdriver/support/color.py
  py/selenium/webdriver/support/event_firing_webdriver.py
  py/selenium/webdriver/support/expected_conditions.py
  py/selenium/webdriver/support/wait.py
  py/test/selenium/webdriver/common/webdriverwait_tests.py
Labels: C-py

#10655 [py] implement `__all__` for `selenium.common`
  py/selenium/common/__init__.py
Labels: C-py

#10643 Add __all__ to __init__.py to make imports public
  py/selenium/webdriver/__init__.py
Labels: C-py

#10671 [dotnet] allow RemoteWebDriver to access Selenium logs
  dotnet/src/webdriver/Logs.cs
Labels: C-dotnet

#10713 Fix `unreleased` note in Ruby changelog
  rb/CHANGES
Labels: C-rb

#10663 [JS] feat: Added virtual authenticator
  javascript/node/selenium-webdriver/lib/command.js
  javascript/node/selenium-webdriver/lib/http.js
  javascript/node/selenium-webdriver/lib/test/fileserver.js
  javascript/node/selenium-webdriver/lib/virtual_authenticator.js
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/net/index.js
  javascript/node/selenium-webdriver/test/lib/credentials_test.js
  javascript/node/selenium-webdriver/test/lib/virtualauthenticatoroptions_test.js
  javascript/node/selenium-webdriver/test/virtualAuthenticator_test.js
Labels: C-nodejs
