Repository SeleniumHQ/selenium, pull requests merged in 2023-01, with the labels that each got.

#11495 [js][bidi] Add filtering capability to LogInspector
  javascript/node/selenium-webdriver/bidi/filterBy.js
  javascript/node/selenium-webdriver/bidi/logInspector.js
  javascript/node/selenium-webdriver/test/bidi/bidi_test.js
Labels: C-nodejs, C-devtools

#11477 [java] Overload methods creating interactions to accept `Point`
  java/src/org/openqa/selenium/interactions/PointerInput.java
  java/src/org/openqa/selenium/interactions/WheelInput.java
  java/test/org/openqa/selenium/interactions/PenPointerTest.java
  java/test/org/openqa/selenium/interactions/WheelInputTest.java
Labels: C-java

#11205 pylint fixes including tidy of f strings, simplifications of conditional statements and isinstances
  py/generate.py
  py/selenium/webdriver/chromium/webdriver.py
  py/selenium/webdriver/common/bidi/cdp.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/webelement.py
  py/test/runner/run_pytest.py
  py/test/selenium/webdriver/chrome/proxy_tests.py
  py/test/selenium/webdriver/common/executing_async_javascript_tests.py
  py/test/selenium/webdriver/common/executing_javascript_tests.py
  py/test/selenium/webdriver/marionette/mn_options_tests.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
  py/test/unit/selenium/webdriver/support/color_tests.py
Labels: C-py
