Repository SeleniumHQ/selenium, pull requests merged in 2024-04, with the labels that each got.

#13753 [js] Fix linting
  javascript/node/selenium-webdriver/test/bidi/script_test.js
  javascript/node/selenium-webdriver/test/bidi/setFiles_command_test.js
  javascript/node/selenium-webdriver/test/bidi/storage_test.js
  javascript/node/selenium-webdriver/test/driver_factory.js
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#13763 [js] Add JS comments for BiDi related files
  javascript/node/selenium-webdriver/bidi/addInterceptParameters.js
  javascript/node/selenium-webdriver/bidi/browser.js
  javascript/node/selenium-webdriver/bidi/browsingContext.js
  javascript/node/selenium-webdriver/bidi/browsingContextInspector.js
  javascript/node/selenium-webdriver/bidi/browsingContextTypes.js
  javascript/node/selenium-webdriver/bidi/captureScreenshotParameters.js
  javascript/node/selenium-webdriver/bidi/clipRectangle.js
  javascript/node/selenium-webdriver/bidi/continueRequestParameters.js
  javascript/node/selenium-webdriver/bidi/continueResponseParameters.js
  javascript/node/selenium-webdriver/bidi/cookieFilter.js
  javascript/node/selenium-webdriver/bidi/evaluateResult.js
  javascript/node/selenium-webdriver/bidi/input.js
  javascript/node/selenium-webdriver/bidi/interceptPhase.js
  javascript/node/selenium-webdriver/bidi/logEntries.js
  javascript/node/selenium-webdriver/bidi/network.js
  javascript/node/selenium-webdriver/bidi/networkTypes.js
  javascript/node/selenium-webdriver/bidi/partialCookie.js
  javascript/node/selenium-webdriver/bidi/partitionDescriptor.js
  javascript/node/selenium-webdriver/bidi/partitionKey.js
  javascript/node/selenium-webdriver/bidi/protocolType.js
  javascript/node/selenium-webdriver/bidi/protocolValue.js
  javascript/node/selenium-webdriver/bidi/provideResponseParameters.js
  javascript/node/selenium-webdriver/bidi/realmInfo.js
  javascript/node/selenium-webdriver/bidi/resultOwnership.js
  javascript/node/selenium-webdriver/bidi/scriptManager.js
  javascript/node/selenium-webdriver/bidi/scriptTypes.js
  javascript/node/selenium-webdriver/bidi/storage.js
  javascript/node/selenium-webdriver/bidi/urlPattern.js
Labels: enhancement, Review effort [1-5]: 5

#13767 [bidi][java] Deprecate using builder for Locate Node parameters.
  java/src/org/openqa/selenium/bidi/browsingcontext/LocateNodeParameters.java
  java/test/org/openqa/selenium/bidi/browsingcontext/LocateNodesTest.java
Labels: enhancement, Review effort [1-5]: 2

#13770 [bidi][java] Enable chrome tests
  java/src/org/openqa/selenium/chrome/ChromeDriverInfo.java
  java/test/org/openqa/selenium/bidi/browser/BUILD.bazel
  java/test/org/openqa/selenium/bidi/browsingcontext/BUILD.bazel
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextInspectorTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextTest.java
  java/test/org/openqa/selenium/bidi/input/BUILD.bazel
  java/test/org/openqa/selenium/bidi/input/CombinedInputActionsTest.java
  java/test/org/openqa/selenium/bidi/input/DefaultMouseTest.java
  java/test/org/openqa/selenium/bidi/log/BUILD.bazel
  java/test/org/openqa/selenium/bidi/network/NetworkCommandsTest.java
  java/test/org/openqa/selenium/bidi/network/NetworkEventsTest.java
  java/test/org/openqa/selenium/bidi/script/BUILD.bazel
  java/test/org/openqa/selenium/bidi/script/LocalValueTest.java
  java/test/org/openqa/selenium/bidi/script/ScriptCommandsTest.java
  java/test/org/openqa/selenium/bidi/script/ScriptEventsTest.java
  java/test/org/openqa/selenium/bidi/storage/BUILD.bazel
  java/test/org/openqa/selenium/bidi/storage/StorageCommandsTest.java
Labels: enhancement, Review effort [1-5]: 2, tests

#13768 [dotnet] use correct devtools session id after reinitialization
  dotnet/src/webdriver/DevTools/DevToolsSession.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
Labels: Review effort [1-5]: 2, tests, bug_fix

#13772 [grid] handle baseRoute like the hubRoute and the graphqlRoute
  java/src/org/openqa/selenium/grid/TemplateGridServerCommand.java
  java/src/org/openqa/selenium/grid/commands/Hub.java
  java/src/org/openqa/selenium/grid/commands/Standalone.java
  java/src/org/openqa/selenium/grid/router/httpd/RouterServer.java
Labels: enhancement, Review effort [1-5]: 2

#13780 [bidi][java] Enable Edge BiDi tests
  java/src/org/openqa/selenium/edge/EdgeDriverInfo.java
  java/test/org/openqa/selenium/bidi/browser/BUILD.bazel
  java/test/org/openqa/selenium/bidi/browser/BrowserCommandsTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BUILD.bazel
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextInspectorTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextTest.java
  java/test/org/openqa/selenium/bidi/input/BUILD.bazel
  java/test/org/openqa/selenium/bidi/input/CombinedInputActionsTest.java
  java/test/org/openqa/selenium/bidi/input/DefaultKeyboardTest.java
  java/test/org/openqa/selenium/bidi/input/DefaultMouseTest.java
  java/test/org/openqa/selenium/bidi/input/DefaultWheelTest.java
  java/test/org/openqa/selenium/bidi/input/DragAndDropTest.java
  java/test/org/openqa/selenium/bidi/input/ReleaseCommandTest.java
  java/test/org/openqa/selenium/bidi/input/SetFilesCommandTest.java
  java/test/org/openqa/selenium/bidi/log/BUILD.bazel
  java/test/org/openqa/selenium/bidi/script/BUILD.bazel
  java/test/org/openqa/selenium/bidi/script/LocalValueTest.java
  java/test/org/openqa/selenium/bidi/script/ScriptCommandsTest.java
  java/test/org/openqa/selenium/bidi/script/ScriptEventsTest.java
  java/test/org/openqa/selenium/bidi/storage/StorageCommandsTest.java
Labels: enhancement, Review effort [1-5]: 2, tests

#13750 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13775 Add type hints for selenium.webdriver.remote.webdriver.WebDriver.__init__
  py/selenium/webdriver/remote/webdriver.py
Labels: enhancement, Review effort [1-5]: 2

#13786 Add types to set_window_position parameters
  py/selenium/webdriver/remote/webdriver.py
Labels: enhancement, Review effort [1-5]: 1

#13790 [bidi][js] Enable tests for Edge and Chrome
  javascript/node/selenium-webdriver/bidi/scriptManager.js
  javascript/node/selenium-webdriver/test/bidi/add_intercept_parameters_test.js
  javascript/node/selenium-webdriver/test/bidi/bidi_session_test.js
  javascript/node/selenium-webdriver/test/bidi/bidi_test.js
  javascript/node/selenium-webdriver/test/bidi/browser_test.js
  javascript/node/selenium-webdriver/test/bidi/browsingcontext_inspector_test.js
  javascript/node/selenium-webdriver/test/bidi/browsingcontext_test.js
  javascript/node/selenium-webdriver/test/bidi/input_test.js
  javascript/node/selenium-webdriver/test/bidi/local_value_test.js
  javascript/node/selenium-webdriver/test/bidi/locate_nodes_test.js
  javascript/node/selenium-webdriver/test/bidi/log_inspector_test.js
  javascript/node/selenium-webdriver/test/bidi/network_commands_test.js
  javascript/node/selenium-webdriver/test/bidi/network_test.js
  javascript/node/selenium-webdriver/test/bidi/script_test.js
  javascript/node/selenium-webdriver/test/bidi/setFiles_command_test.js
  javascript/node/selenium-webdriver/test/bidi/storage_test.js
  javascript/node/selenium-webdriver/testing/index.js
Labels: enhancement, Review effort [1-5]: 2, tests

#13792 Fixing atom to capitalize text
  javascript/atoms/dom.js
  javascript/atoms/test/text_test.html
Labels: Review effort [1-5]: 2, bug_fix

#13789 [grid][java] fix node-docker
  java/src/org/openqa/selenium/grid/node/remote/RemoteNode.java
  java/src/org/openqa/selenium/remote/http/jdk/JdkHttpMessages.java
Labels: Review effort [1-5]: 2, bug_fix

#13798 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13810 [rust] Use DEBUG level for WARN traces in offline mode
  rust/src/lib.rs
  rust/src/logger.rs
  rust/src/main.rs
Labels: C-rust, Review effort [1-5]: 2, bug_fix

#13804 [grid][java] browser containers provisioned in dynamic grid can get hostconfig from node-docker
  java/src/org/openqa/selenium/docker/ContainerConfig.java
  java/src/org/openqa/selenium/docker/ContainerInfo.java
  java/src/org/openqa/selenium/docker/v1_41/InspectContainer.java
  java/src/org/openqa/selenium/grid/node/docker/DockerFlags.java
  java/src/org/openqa/selenium/grid/node/docker/DockerOptions.java
  java/src/org/openqa/selenium/grid/node/docker/DockerSessionFactory.java
Labels: enhancement, Review effort [1-5]: 4

#13819 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13385 [java] Selenium Manager generates output from argument list
  java/src/org/openqa/selenium/PersistentCapabilities.java
  java/src/org/openqa/selenium/chrome/ChromeDriver.java
  java/src/org/openqa/selenium/chrome/ChromeDriverInfo.java
  java/src/org/openqa/selenium/chrome/ChromeDriverService.java
  java/src/org/openqa/selenium/edge/EdgeDriver.java
  java/src/org/openqa/selenium/edge/EdgeDriverInfo.java
  java/src/org/openqa/selenium/edge/EdgeDriverService.java
  java/src/org/openqa/selenium/firefox/FirefoxDriver.java
  java/src/org/openqa/selenium/firefox/GeckoDriverInfo.java
  java/src/org/openqa/selenium/firefox/GeckoDriverService.java
  java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java
  java/src/org/openqa/selenium/ie/InternetExplorerDriver.java
  java/src/org/openqa/selenium/ie/InternetExplorerDriverInfo.java
  java/src/org/openqa/selenium/ie/InternetExplorerDriverService.java
  java/src/org/openqa/selenium/internal/Require.java
  java/src/org/openqa/selenium/manager/SeleniumManager.java
  java/src/org/openqa/selenium/remote/NoSuchDriverException.java
  java/src/org/openqa/selenium/remote/service/DriverFinder.java
  java/src/org/openqa/selenium/remote/service/DriverService.java
  java/src/org/openqa/selenium/safari/SafariDriver.java
  java/src/org/openqa/selenium/safari/SafariDriverInfo.java
  java/src/org/openqa/selenium/safari/SafariDriverService.java
  java/src/org/openqa/selenium/safari/SafariTechPreviewDriverInfo.java
  java/src/org/openqa/selenium/safari/SafariTechPreviewDriverService.java
  java/test/org/openqa/selenium/remote/service/BUILD.bazel
  java/test/org/openqa/selenium/remote/service/DriverFinderTest.java
Labels: C-java

#13386 [rb] update SOC for driver finder and selenium manager classes
  rb/lib/selenium/webdriver/common/driver_finder.rb
  rb/lib/selenium/webdriver/common/local_driver.rb
  rb/lib/selenium/webdriver/common/platform.rb
  rb/lib/selenium/webdriver/common/selenium_manager.rb
  rb/lib/selenium/webdriver/common/service.rb
  rb/spec/integration/selenium/webdriver/chrome/service_spec.rb
  rb/spec/integration/selenium/webdriver/edge/service_spec.rb
  rb/spec/integration/selenium/webdriver/firefox/service_spec.rb
  rb/spec/unit/selenium/webdriver/chrome/driver_spec.rb
  rb/spec/unit/selenium/webdriver/chrome/service_spec.rb
  rb/spec/unit/selenium/webdriver/common/driver_finder_spec.rb
  rb/spec/unit/selenium/webdriver/common/selenium_manager_spec.rb
  rb/spec/unit/selenium/webdriver/edge/driver_spec.rb
  rb/spec/unit/selenium/webdriver/edge/service_spec.rb
  rb/spec/unit/selenium/webdriver/firefox/driver_spec.rb
  rb/spec/unit/selenium/webdriver/firefox/service_spec.rb
  rb/spec/unit/selenium/webdriver/ie/driver_spec.rb
  rb/spec/unit/selenium/webdriver/ie/service_spec.rb
  rb/spec/unit/selenium/webdriver/safari/driver_spec.rb
  rb/spec/unit/selenium/webdriver/safari/service_spec.rb
Labels: C-rb

#13823 Update Dockerfile to use JDK 17
  scripts/dev-image/Dockerfile
Labels: enhancement, Review effort [1-5]: 1

#13387 [py] update SOC for driver finder and selenium manager classes
  Rakefile
  py/selenium/webdriver/chromium/webdriver.py
  py/selenium/webdriver/common/driver_finder.py
  py/selenium/webdriver/common/selenium_manager.py
  py/selenium/webdriver/firefox/webdriver.py
  py/selenium/webdriver/ie/webdriver.py
  py/selenium/webdriver/safari/webdriver.py
  py/selenium/webdriver/webkitgtk/webdriver.py
  py/selenium/webdriver/wpewebkit/webdriver.py
  py/test/selenium/webdriver/common/driver_finder_tests.py
  py/test/selenium/webdriver/common/selenium_manager_tests.py
Labels: C-py

#13830 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
  java/test/org/openqa/selenium/bidi/input/SetFilesCommandTest.java
  java/test/org/openqa/selenium/bidi/storage/StorageCommandsTest.java
Labels: enhancement, Review effort [1-5]: 2

#13835 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 1

#13838 Nightly dotnet
  .github/workflows/bazel.yml
  .github/workflows/nightly.yml
  Rakefile
  dotnet/selenium-dotnet-version.bzl
Labels: enhancement, Review effort [1-5]: 3, tests

#13833 [dotnet] Making SeleniumManager a thin wrapper
  dotnet/src/webdriver/Chromium/ChromiumDriver.cs
  dotnet/src/webdriver/DriverFinder.cs
  dotnet/src/webdriver/DriverService.cs
  dotnet/src/webdriver/Firefox/FirefoxDriver.cs
  dotnet/src/webdriver/IE/InternetExplorerDriver.cs
  dotnet/src/webdriver/Safari/SafariDriver.cs
  dotnet/src/webdriver/SeleniumManager.cs
Labels: enhancement, Review effort [1-5]: 4

#13844 Nightly javascript
  .github/workflows/bazel.yml
  .github/workflows/nightly.yml
  Rakefile
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/package.json
  package-lock.json
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#13849 [grid][java]: relay service can set protocol version in fetching status
  java/src/org/openqa/selenium/grid/node/relay/RelayFlags.java
  java/src/org/openqa/selenium/grid/node/relay/RelayOptions.java
  java/src/org/openqa/selenium/grid/node/relay/RelaySessionFactory.java
  java/test/org/openqa/selenium/grid/node/relay/RelayOptionsTest.java
Labels: enhancement, Review effort [1-5]: 3

#13836 [cdp][java] Continue requests without modification for know errors in NetworkInterceptor
  java/src/org/openqa/selenium/devtools/idealized/Network.java
  java/src/org/openqa/selenium/devtools/v121/v121Network.java
  java/src/org/openqa/selenium/devtools/v122/v122Network.java
  java/src/org/openqa/selenium/devtools/v123/v123Network.java
  java/src/org/openqa/selenium/devtools/v85/V85Network.java
  java/test/org/openqa/selenium/devtools/NetworkInterceptorTest.java
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#13766 [bidi] Update browsing context create method
  java/src/org/openqa/selenium/bidi/browsingcontext/BrowsingContext.java
  java/src/org/openqa/selenium/bidi/browsingcontext/CreateContextParameters.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextTest.java
  javascript/node/selenium-webdriver/bidi/browsingContext.js
  javascript/node/selenium-webdriver/bidi/createContextParameters.js
  javascript/node/selenium-webdriver/test/bidi/browsingcontext_test.js
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#13868 [build] Prepare for release of Selenium 4.20.0
  .github/workflows/pre-release.yml
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v124/BUILD.bazel
  common/devtools/chromium/v124/browser_protocol.pdl
  common/devtools/chromium/v124/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v124/V124Domains.cs
  dotnet/src/webdriver/DevTools/v124/V124JavaScript.cs
  dotnet/src/webdriver/DevTools/v124/V124Log.cs
  dotnet/src/webdriver/DevTools/v124/V124Network.cs
  dotnet/src/webdriver/DevTools/v124/V124Target.cs
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/src/org/openqa/selenium/devtools/v124/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v124/v124CdpInfo.java
  java/src/org/openqa/selenium/devtools/v124/v124Domains.java
  java/src/org/openqa/selenium/devtools/v124/v124Events.java
  java/src/org/openqa/selenium/devtools/v124/v124Javascript.java
  java/src/org/openqa/selenium/devtools/v124/v124Log.java
  java/src/org/openqa/selenium/devtools/v124/v124Network.java
  java/src/org/openqa/selenium/devtools/v124/v124Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  package-lock.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/setup.py
  rb/.rubocop.yml
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/devtools/network_interceptor.rb
  rb/lib/selenium/webdriver/version.rb
  rust/CHANGELOG.md
Labels: C-build, enhancement, documentation, Review effort [1-5]: 3

#13841 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13879 Ensure rules_proto comes from the module file
  WORKSPACE
Labels: enhancement, Review effort [1-5]: 2

#13886 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2
