Repository SeleniumHQ/selenium, pull requests merged in 2024-07, with the labels that each got.

#14215 [bidi] [java] Ensure the listeners returns an id
  java/src/org/openqa/selenium/bidi/BiDi.java
  java/src/org/openqa/selenium/bidi/Connection.java
  java/src/org/openqa/selenium/bidi/module/LogInspector.java
Labels: enhancement, Review effort [1-5]: 3

#14230 [bidi][js] Add methods to add/remove handlers in Script module
  javascript/node/selenium-webdriver/bidi/scriptManager.js
Labels: enhancement, Review effort [1-5]: 3

#14189 [rb] Update selenium manager types
  rb/sig/lib/selenium/webdriver/common/selenium_manager.rbs
Labels: enhancement, Review effort [1-5]: 2

#14244 [bidi] Add source type to log entry
  java/src/org/openqa/selenium/bidi/log/BaseLogEntry.java
  java/src/org/openqa/selenium/bidi/log/ConsoleLogEntry.java
  java/src/org/openqa/selenium/bidi/log/GenericLogEntry.java
  java/src/org/openqa/selenium/bidi/log/JavascriptLogEntry.java
  java/test/org/openqa/selenium/bidi/log/LogInspectorTest.java
  java/test/org/openqa/selenium/grid/router/RemoteWebDriverBiDiTest.java
  javascript/node/selenium-webdriver/bidi/logEntries.js
  javascript/node/selenium-webdriver/bidi/logInspector.js
  javascript/node/selenium-webdriver/test/bidi/log_inspector_test.js
Labels: enhancement, Review effort [1-5]: 3, tests

#14233 [py] Remove precompiled binaries from sdist
  py/BUILD.bazel
  py/pyproject.toml
  py/selenium/webdriver/common/selenium_manager.py
  py/setup.py
  rust/BUILD.bazel
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#14238 [bidi][js] Add dom mutation handlers
  javascript/bidi-support/BUILD.bazel
  javascript/bidi-support/bidi-mutation-listener.js
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/lib/atoms/BUILD.bazel
  javascript/node/selenium-webdriver/lib/atoms/bidi-mutation-listener.js
  javascript/node/selenium-webdriver/lib/script.js
  javascript/node/selenium-webdriver/test/lib/webdriver_script_test.js
Labels: enhancement, tests, Review effort [1-5]: 4

#14250 [bidi][js] Add high-level script pinning APIs
  javascript/node/selenium-webdriver/lib/script.js
  javascript/node/selenium-webdriver/test/lib/webdriver_script_test.js
Labels: enhancement, Review effort [1-5]: 2, tests

#14134 [java] Revert workaround for old netty http client (addendum to #12843)
  java/src/org/openqa/selenium/chromium/ChromiumOptions.java
Labels: C-java, enhancement, Review effort [1-5]: 2

#14251 [bidi][js] Deprecate argument value wrapper class
  javascript/node/selenium-webdriver/bidi/argumentValue.js
  javascript/node/selenium-webdriver/bidi/protocolValue.js
  javascript/node/selenium-webdriver/lib/script.js
  javascript/node/selenium-webdriver/test/bidi/local_value_test.js
  javascript/node/selenium-webdriver/test/bidi/locate_nodes_test.js
  javascript/node/selenium-webdriver/test/bidi/script_test.js
Labels: enhancement, Review effort [1-5]: 3, tests

#14242 [dotnet] quit fails after not successful new session
  dotnet/src/webdriver/WebDriver.cs
Labels: Bug fix, Review effort [1-5]: 1

#14247 Remove 'browserName' capability from stereotype when using RelaySession
  java/src/org/openqa/selenium/grid/node/relay/RelaySessionFactory.java
Labels: Review effort [1-5]: 2, Bug fix

#13082 py: fix RelativeBy#near to take 2 parameters
  py/selenium/webdriver/common/by.py
  py/selenium/webdriver/support/relative_locator.py
  py/test/selenium/webdriver/support/relative_by_tests.py
Labels: A-needs decision, C-py, support

#14217 [java] Merge android specific parameters in chrome options
  java/src/org/openqa/selenium/chromium/ChromiumOptions.java
  java/test/org/openqa/selenium/chrome/ChromeOptionsTest.java
Labels: Review effort [1-5]: 2, Bug fix, tests

#14170 [rb] Add backtrace locations and cause to errors
  rb/lib/selenium/webdriver/common/error.rb
  rb/lib/selenium/webdriver/remote/response.rb
  rb/sig/lib/selenium/webdriver/common/error.rbs
  rb/sig/lib/selenium/webdriver/remote/response.rbs
  rb/spec/integration/selenium/webdriver/error_spec.rb
Labels: enhancement, Review effort [1-5]: 2, tests

#14177 Update logo path in readme
  README.md
Labels: documentation, Review effort [1-5]: 1

#14085 [java] custom duration for Actions constructor
  java/src/org/openqa/selenium/interactions/Actions.java
  java/test/org/openqa/selenium/interactions/ActionDurationTest.java
Labels: C-java, enhancement, Review effort [1-5]: 2

#14272 [grid] Set session-request-timeout as client readTimeout in RemoteNewSessionQueue
  java/src/org/openqa/selenium/grid/sessionqueue/remote/RemoteNewSessionQueue.java
Labels: enhancement, Review effort [1-5]: 2

#14225 [bidi][java] Add high-level logging APIs
  java/src/org/openqa/selenium/remote/BUILD.bazel
  java/src/org/openqa/selenium/remote/RemoteScript.java
  java/src/org/openqa/selenium/remote/RemoteWebDriver.java
  java/src/org/openqa/selenium/remote/Script.java
  java/test/org/openqa/selenium/WebScriptTest.java
Labels: enhancement, Review effort [1-5]: 3, tests

#14273 [build] Prepare for release of Selenium 4.23.0
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v127/BUILD.bazel
  common/devtools/chromium/v127/browser_protocol.pdl
  common/devtools/chromium/v127/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v127/V127Domains.cs
  dotnet/src/webdriver/DevTools/v127/V127JavaScript.cs
  dotnet/src/webdriver/DevTools/v127/V127Log.cs
  dotnet/src/webdriver/DevTools/v127/V127Network.cs
  dotnet/src/webdriver/DevTools/v127/V127Target.cs
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v127/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v127/v127CdpInfo.java
  java/src/org/openqa/selenium/devtools/v127/v127Domains.java
  java/src/org/openqa/selenium/devtools/v127/v127Events.java
  java/src/org/openqa/selenium/devtools/v127/v127Javascript.java
  java/src/org/openqa/selenium/devtools/v127/v127Log.java
  java/src/org/openqa/selenium/devtools/v127/v127Network.java
  java/src/org/openqa/selenium/devtools/v127/v127Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  package-lock.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/setup.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
  rb/selenium-devtools.gemspec
  rb/selenium-webdriver.gemspec
  rust/CHANGELOG.md
Labels: C-build

#14276 [rb] Deprecate WebStorage JS methods
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/spec/integration/selenium/webdriver/storage_spec.rb
Labels: enhancement, Review effort [1-5]: 2, tests

#14267 [rb] Add test for detached shadow root error type
  rb/spec/integration/selenium/webdriver/shadow_root_spec.rb
Labels: Review effort [1-5]: 2, tests

#14297 Fix 14278 and match ordering of dependencies
  py/BUILD.bazel
  py/setup.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#14277 [rb] Fix firefox pipeline by removing guards
  rb/spec/integration/selenium/webdriver/action_builder_spec.rb
Labels: Review effort [1-5]: 2, Bug fix

#14282 [grid] Exclude status DRAINING when distributor getting available nodes
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
Labels: Review effort [1-5]: 2, Bug fix

#14292 [dotnet] Migration from `Newtonsoft.Json` to `System.Text.Json` package
  MODULE.bazel
  dotnet/paket.dependencies
  dotnet/paket.lock
  dotnet/paket.nuget.bzl
  dotnet/src/support/BUILD.bazel
  dotnet/src/webdriver/BUILD.bazel
  dotnet/src/webdriver/Chromium/ChromiumNetworkConditions.cs
  dotnet/src/webdriver/Command.cs
  dotnet/src/webdriver/Cookie.cs
  dotnet/src/webdriver/DevTools/DevToolsCommandData.cs
  dotnet/src/webdriver/DevTools/DevToolsSession.cs
  dotnet/src/webdriver/DevTools/DevToolsSessionEventReceivedEventArgs.cs
  dotnet/src/webdriver/DevTools/DevToolsVersionInfo.cs
  dotnet/src/webdriver/DevTools/IDevToolsSession.cs
  dotnet/src/webdriver/DevTools/Json/JsonEnumMemberConverter.cs
  dotnet/src/webdriver/DomMutationData.cs
  dotnet/src/webdriver/DriverOptions.cs
  dotnet/src/webdriver/Firefox/FirefoxExtension.cs
  dotnet/src/webdriver/Firefox/FirefoxProfile.cs
  dotnet/src/webdriver/Internal/ResponseValueJsonConverter.cs
  dotnet/src/webdriver/Internal/ReturnedCapabilities.cs
  dotnet/src/webdriver/JavaScriptEngine.cs
  dotnet/src/webdriver/Proxy.cs
  dotnet/src/webdriver/Remote/RemoteSessionSettings.cs
  dotnet/src/webdriver/Response.cs
  dotnet/src/webdriver/SeleniumManager.cs
  dotnet/src/webdriver/StackTraceElement.cs
  dotnet/src/webdriver/WebDriver.StrongNamed.nuspec
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/src/webdriver/WebDriver.nuspec
  dotnet/test/chrome/WebDriver.Chrome.Tests.csproj
  dotnet/test/common/BUILD.bazel
  dotnet/test/common/ProxyTest.cs
  dotnet/test/common/TakesScreenshotTest.cs
  dotnet/test/common/WebDriver.Common.Tests.csproj
  dotnet/test/edge/WebDriver.Edge.Tests.csproj
  dotnet/test/firefox/WebDriver.Firefox.Tests.csproj
  dotnet/test/ie/WebDriver.IE.Tests.csproj
  dotnet/test/remote/WebDriver.Remote.Tests.csproj
  dotnet/test/safari/WebDriver.Safari.Tests.csproj
  dotnet/test/support/WebDriver.Support.Tests.csproj
  third_party/dotnet/devtools/src/generator/Templates/command.hbs
  third_party/dotnet/devtools/src/generator/Templates/domain.hbs
  third_party/dotnet/devtools/src/generator/Templates/event.hbs
  third_party/dotnet/devtools/src/generator/Templates/type-enum.hbs
  third_party/dotnet/devtools/src/generator/Templates/type-hash.hbs
  third_party/dotnet/devtools/src/generator/Templates/type-object.hbs
Labels: dependencies, enhancement, tests, Review effort [1-5]: 4, configuration changes

#14158 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14306 Allow setting JDKHttpClient connectionTimeout, readTimeout, version via system property
  java/src/org/openqa/selenium/remote/http/ClientConfig.java
  java/test/org/openqa/selenium/remote/internal/HttpClientTestBase.java
Labels: enhancement, Review effort [1-5]: 2, tests

#14295 [java] remove package org.openqa.selenium.grid.session.remote
  java/src/org/openqa/selenium/grid/session/remote/ActiveSessionCommandExecutor.java
  java/src/org/openqa/selenium/grid/session/remote/RemoteSession.java
  java/src/org/openqa/selenium/grid/session/remote/ServicedSession.java
Labels: enhancement, Review effort [1-5]: 2

#14320 [rb] BUGFIX: Add stamp to nightly build
  rb/lib/selenium/webdriver/version.rb
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#14314 [dotnet] Fix running of support tests in CI bazel
  dotnet/test/support/Events/BUILD.bazel
  dotnet/test/support/Extensions/BUILD.bazel
  dotnet/test/support/UI/BUILD.bazel
Labels: Review effort [1-5]: 2, Bug fix

#14325 [js] expose selenium version for node.js
  javascript/node/selenium-webdriver/index.js
Labels: enhancement, Review effort [1-5]: 2
