Repository SeleniumHQ/selenium, pull requests merged in 2024-08, with the labels that each got.

#14324 py: Don't expose 0.0.0.0 as destination IP for tests
  py/conftest.py
  py/test/selenium/webdriver/common/webserver.py
Labels: Review effort [1-5]: 2, Bug fix

#14345 [bidi][js] Add authentication handlers
  javascript/node/selenium-webdriver/bidi/network.js
  javascript/node/selenium-webdriver/lib/network.js
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/test/bidi/network_commands_test.js
  javascript/node/selenium-webdriver/test/lib/webdriver_network_test.js
Labels: C-devtools, javascript, enhancement, Review effort [1-5]: 3, tests

#14293 [bidi][js] Add high-level script command
  javascript/node/selenium-webdriver/bidi/protocolValue.js
  javascript/node/selenium-webdriver/lib/script.js
  javascript/node/selenium-webdriver/test/bidi/local_value_test.js
  javascript/node/selenium-webdriver/test/bidi/locate_nodes_test.js
  javascript/node/selenium-webdriver/test/lib/webdriver_script_execute_test.js
Labels: enhancement, tests, Review effort [1-5]: 4

#14334 [bidi][java] Add authentication handlers
  java/src/org/openqa/selenium/bidi/module/Network.java
  java/src/org/openqa/selenium/remote/BUILD.bazel
  java/src/org/openqa/selenium/remote/Network.java
  java/src/org/openqa/selenium/remote/RemoteNetwork.java
  java/src/org/openqa/selenium/remote/RemoteWebDriver.java
  java/test/org/openqa/selenium/WebNetworkTest.java
Labels: C-java, C-devtools, enhancement, Review effort [1-5]: 3, tests

#14337 [grid] ensure the local_sessionmap.remove event is raised
  java/src/org/openqa/selenium/grid/sessionmap/local/LocalSessionMap.java
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#14349 [bidi][java] Add filter auth handler
  java/src/org/openqa/selenium/remote/Network.java
  java/src/org/openqa/selenium/remote/RemoteNetwork.java
  java/test/org/openqa/selenium/WebNetworkTest.java
Labels: C-java, C-devtools, enhancement, Review effort [1-5]: 3, tests

#14354 [py] Allow overriding `GLOBAL_DEFAULT_TIMEOUT`
  py/selenium/webdriver/remote/remote_connection.py
Labels: C-py, python, enhancement, Review effort [1-5]: 2

#14323 [java] Add "se" prefixed capabilities to session response
  java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java
  java/test/org/openqa/selenium/grid/node/local/LocalNodeTest.java
Labels: enhancement, Review effort [1-5]: 2, tests

#14319 [java] Add JSpecify annotations to WebElement and SearchContext
  MODULE.bazel
  java/maven_install.json
  java/src/org/openqa/selenium/BUILD.bazel
  java/src/org/openqa/selenium/SearchContext.java
  java/src/org/openqa/selenium/WebElement.java
Labels: dependencies, enhancement, Review effort [1-5]: 2

#14352 [JS]: Handle optional dependency for @bazel/runfiles
  javascript/node/selenium-webdriver/testing/index.js
Labels: Review effort [1-5]: 2, Bug fix

#14370 [bazel] With the move to aspect_rules_js we do not need to pre-warm the npm cache
  scripts/github-actions/ci-build.sh
Labels: enhancement, Review effort [1-5]: 1

#14373 [bazel + ci]: Stop being selective about which parts of the tree to test
  .skipped-tests
  rust/BUILD.bazel
  rust/tests/BUILD.bazel
  scripts/github-actions/ci-build.sh
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#14377 [py] fix mypy errors for `input_device.py`, `ie/options.py` and `selenium_manager.py`
  py/selenium/webdriver/common/actions/input_device.py
  py/selenium/webdriver/common/selenium_manager.py
  py/selenium/webdriver/ie/options.py
Labels: Review effort [1-5]: 2, Bug fix

#14379 Fix Github Workflow vulnerable to script injection
  .github/workflows/stage-release.yml
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#14371 [java] Add JSpecify annotations for WebDriver and 3 other interfaces
  java/src/org/openqa/selenium/JavascriptExecutor.java
  java/src/org/openqa/selenium/OutputType.java
  java/src/org/openqa/selenium/TakesScreenshot.java
  java/src/org/openqa/selenium/WebDriver.java
Labels: enhancement, Review effort [1-5]: 2

#14389 Bug 14229 fixed
  common/src/web/javascriptPage.html
  javascript/atoms/domcore.js
  py/test/selenium/webdriver/common/visibility_tests.py
Labels: Review effort [1-5]: 2, Bug fix, tests

#14392 [py] fix type errors for `log.py`, `chromium/options.py`, `websocket_connection.py` and `chrome/options.py`
  py/selenium/webdriver/chrome/options.py
  py/selenium/webdriver/chromium/options.py
  py/selenium/webdriver/common/log.py
  py/selenium/webdriver/remote/websocket_connection.py
Labels: Review effort [1-5]: 3, Bug fix

#14153 Implement getAttributes() method of MBean, and update Number-based MBean attributes to return Number objects instead of Strings
  java/src/org/openqa/selenium/grid/jmx/MBean.java
  java/test/org/openqa/selenium/grid/router/JmxTest.java
Labels: C-grid, enhancement, Review effort [1-5]: 3, tests

#14390 Modern Modal
  common/src/web/modal_dialogs/modern_modal.html
  java/test/org/openqa/selenium/ModernModalTest.java
  java/test/org/openqa/selenium/testing/Pages.java
Labels: enhancement, documentation, Review effort [1-5]: 2

#14388 [rust] Use the Debug format specifier to display error messages
  rust/src/logger.rs
  rust/src/main.rs
Labels: C-rust, enhancement, Review effort [1-5]: 1

#14398 Refactor ChromeDriverFunctionalTest:
  java/test/org/openqa/selenium/chrome/ChromeDriverFunctionalTest.java
Labels: enhancement, Review effort [1-5]: 1

#14330 [bidi][java] Add execute script high-level API
  java/src/org/openqa/selenium/bidi/script/LocalValue.java
  java/src/org/openqa/selenium/remote/RemoteScript.java
  java/src/org/openqa/selenium/remote/Script.java
  java/test/org/openqa/selenium/WebScriptExecuteTest.java
Labels: enhancement, Review effort [1-5]: 3, tests

#14378 [ci] Use a tag to figure out what we might want to release
  dotnet/BUILD.bazel
  java/src/org/openqa/selenium/BUILD.bazel
  java/src/org/openqa/selenium/chrome/BUILD.bazel
  java/src/org/openqa/selenium/chromium/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v125/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v126/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v127/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v85/BUILD.bazel
  java/src/org/openqa/selenium/edge/BUILD.bazel
  java/src/org/openqa/selenium/firefox/BUILD.bazel
  java/src/org/openqa/selenium/grid/BUILD.bazel
  java/src/org/openqa/selenium/grid/sessionmap/jdbc/BUILD.bazel
  java/src/org/openqa/selenium/grid/sessionmap/redis/BUILD.bazel
  java/src/org/openqa/selenium/ie/BUILD.bazel
  java/src/org/openqa/selenium/json/BUILD.bazel
  java/src/org/openqa/selenium/manager/BUILD.bazel
  java/src/org/openqa/selenium/os/BUILD.bazel
  java/src/org/openqa/selenium/remote/BUILD.bazel
  java/src/org/openqa/selenium/remote/http/BUILD.bazel
  java/src/org/openqa/selenium/safari/BUILD.bazel
  java/src/org/openqa/selenium/support/BUILD.bazel
  javascript/node/selenium-webdriver/BUILD.bazel
  py/BUILD.bazel
  rb/BUILD.bazel
  scripts/github-actions/ci-build.sh
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#14256 [py] moved all pytest configuration settings from `pytest.ini` file to `pyproject.toml`
  py/BUILD.bazel
  py/pyproject.toml
  py/pytest.ini
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#14423 [bazel] Use the `release` configs for the release tasks
  .bazelrc
  Rakefile
Labels: enhancement, Review effort [1-5]: 2

#14439 Add delete comments workflow
  delete-comments.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#14440 [py] Add unhandled prompt behavior option is BiDi is enabled
  py/conftest.py
Labels: enhancement, Review effort [1-5]: 1

#14441 [dotnet] Add unhandled prompt behavior value to tests for Chrome and …
  dotnet/test/common/BUILD.bazel
  dotnet/test/common/Environment/DriverFactory.cs
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextInspectorTest.java
Labels: enhancement, Review effort [1-5]: 2, tests

#14442 chore(ci): correct github-script API calls
  .github/workflows/delete-comments.yml
Labels: enhancement, Bug fix, Review effort [1-5]: 1

#14444 [rust] Include arguments for skipping drivers and browsers in path
  rust/src/config.rs
  rust/src/lib.rs
  rust/src/main.rs
Labels: C-rust, enhancement, Review effort [1-5]: 2

#14429 Release 4.24.0
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v128/BUILD.bazel
  common/devtools/chromium/v128/browser_protocol.pdl
  common/devtools/chromium/v128/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v128/V128Domains.cs
  dotnet/src/webdriver/DevTools/v128/V128JavaScript.cs
  dotnet/src/webdriver/DevTools/v128/V128Log.cs
  dotnet/src/webdriver/DevTools/v128/V128Network.cs
  dotnet/src/webdriver/DevTools/v128/V128Target.cs
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v128/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v128/v128CdpInfo.java
  java/src/org/openqa/selenium/devtools/v128/v128Domains.java
  java/src/org/openqa/selenium/devtools/v128/v128Events.java
  java/src/org/openqa/selenium/devtools/v128/v128Javascript.java
  java/src/org/openqa/selenium/devtools/v128/v128Log.java
  java/src/org/openqa/selenium/devtools/v128/v128Network.java
  java/src/org/openqa/selenium/devtools/v128/v128Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/src/org/openqa/selenium/remote/http/jdk/JdkHttpClient.java
  java/test/org/openqa/selenium/testing/drivers/Browser.java
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  package-lock.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/selenium/webdriver/__init__.py
  py/setup.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
  rust/BUILD.bazel
  rust/CHANGELOG.md
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
Labels: dependencies, enhancement, documentation, Review effort [1-5]: 3, tests, configuration changes
