Repository SeleniumHQ/selenium, pull requests merged in 2024-06, with the labels that each got.

#14071 [rb] manage bidi instance on the bridge not the driver
  rb/lib/selenium/webdriver/common/driver.rb
  rb/lib/selenium/webdriver/common/driver_extensions/has_bidi.rb
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/sig/lib/selenium/webdriver/common/driver.rbs
  rb/sig/lib/selenium/webdriver/remote/bridge.rbs
Labels: C-rb, C-devtools, enhancement, Review effort [1-5]: 3

#14031 Fix EOFError when calling the Remote WebDriver download_file method
  py/selenium/webdriver/remote/webdriver.py
Labels: C-py, Review effort [1-5]: 2, Bug fix

#13709 [rb] Expand RBS typing support by replacing untypes with precise typing
  rb/sig/lib/selenium/server.rbs
  rb/sig/lib/selenium/webdriver/atoms.rbs
  rb/sig/lib/selenium/webdriver/bidi.rbs
  rb/sig/lib/selenium/webdriver/chrome/features.rbs
  rb/sig/lib/selenium/webdriver/common/options.rbs
  rb/sig/lib/selenium/webdriver/common/target_locator.rbs
  rb/sig/lib/selenium/webdriver/devtools.rbs
  rb/sig/lib/selenium/webdriver/edge.rbs
  rb/sig/lib/selenium/webdriver/firefox.rbs
  rb/sig/lib/selenium/webdriver/safari.rbs
  rb/sig/lib/selenium/webdriver/support.rbs
  rb/sig/lib/selenium_webdriver.rbs
Labels: enhancement, Review effort [1-5]: 2

#14082 [rb] Add `logger` gem as a runtime dependency
  rb/Gemfile.lock
  rb/selenium-webdriver.gemspec
Labels: enhancement, Bug fix, Review effort [1-5]: 1

#14083 [build] Add Bazel bidi flag
  .skipped-tests
  rb/spec/tests.bzl
Labels: enhancement, Review effort [1-5]: 3, tests

#14051 [dotnet] add asynchronous methods to Navigation class
  dotnet/src/support/Events/EventFiringWebDriver.cs
  dotnet/src/webdriver/ICommandExecutor.cs
  dotnet/src/webdriver/INavigation.cs
  dotnet/src/webdriver/Navigator.cs
  dotnet/src/webdriver/Remote/DriverServiceCommandExecutor.cs
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/test/common/NavigationTest.cs
  dotnet/test/support/Events/EventFiringWebDriverTest.cs
Labels: C-dotnet, C-devtools, enhancement, tests, Review effort [1-5]: 4

#13977 [py] Add low-level sync API to use DevTools
  py/BUILD.bazel
  py/generate.py
  py/requirements.txt
  py/requirements_lock.txt
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/websocket_connection.py
  py/test/selenium/webdriver/common/devtools_tests.py
Labels: C-py, enhancement, Review effort [1-5]: 3, tests

#14097 [bidi][js] Add types for user prompt related events
  javascript/node/selenium-webdriver/bidi/browsingContextInspector.js
  javascript/node/selenium-webdriver/bidi/browsingContextTypes.js
  javascript/node/selenium-webdriver/test/bidi/browsingcontext_inspector_test.js
Labels: enhancement, Review effort [1-5]: 2, tests

#14096 [build] update rules_dotnet to 0.15.1
  MODULE.bazel
  dotnet/paket.bzl
  dotnet/paket.nuget.bzl
  dotnet/paket.nuget_extension.bzl
  dotnet/src/support/BUILD.bazel
  dotnet/src/webdriver/BUILD.bazel
  dotnet/test/common/BUILD.bazel
  dotnet/test/support/Events/BUILD.bazel
  dotnet/test/support/Extensions/BUILD.bazel
  dotnet/test/support/UI/BUILD.bazel
  dotnet/update-deps.sh
  third_party/dotnet/devtools/src/generator/BUILD.bazel
Labels: C-dotnet, C-build, enhancement, Review effort [1-5]: 2, configuration changes

#14114 [rust] Use pure Rust implementation for which command
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/lib.rs
  rust/src/shell.rs
Labels: C-rust, enhancement, Review effort [1-5]: 3, Bug fix

#14099 [rust] Enable Firefox nightly for linux on arm64
  rust/src/firefox.rs
Labels: enhancement, Review effort [1-5]: 2

#14123 [bazel + js]: Get small js tests running on the rbe
  .github/workflows/ci-javascript.yml
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/test/driver_factory.js
  javascript/node/selenium-webdriver/test/io/io_test.js
  javascript/node/selenium-webdriver/test/io/zip_test.js
  javascript/node/selenium-webdriver/test/lib/by_test.js
  javascript/node/selenium-webdriver/test/lib/credentials_test.js
  javascript/node/selenium-webdriver/test/lib/error_test.js
  javascript/node/selenium-webdriver/test/lib/http_test.js
  javascript/node/selenium-webdriver/test/lib/input_test.js
  javascript/node/selenium-webdriver/test/lib/logging_test.js
  javascript/node/selenium-webdriver/test/lib/promise_test.js
  javascript/node/selenium-webdriver/test/lib/until_test.js
  javascript/node/selenium-webdriver/test/lib/virtualauthenticatoroptions_test.js
  javascript/node/selenium-webdriver/test/lib/webdriver_test.js
  javascript/node/selenium-webdriver/test/logging_test.js
  javascript/node/selenium-webdriver/test/net/index_test.js
  javascript/node/selenium-webdriver/test/net/portprober_test.js
  javascript/private/mocha_test.bzl
Labels: enhancement, Review effort [1-5]: 3, tests

#14120 [bidi][js] Add callback handlers for logging APIs
  javascript/node/selenium-webdriver/bidi/logInspector.js
  javascript/node/selenium-webdriver/test/bidi/log_inspector_test.js
Labels: enhancement, tests, Review effort [1-5]: 4

#14129 Update bazel and its dependencies
  .bazelversion
  MODULE.bazel
  WORKSPACE
Labels: dependencies, enhancement, Review effort [1-5]: 2

#14053 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14138 fixed docs api url in README.md for selenium-webdriver npm package
  javascript/node/selenium-webdriver/README.md
Labels: documentation, Bug fix, Review effort [1-5]: 1

#14139 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14144 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14107 [py] Implement High Level Logging API with BiDi
  .gitignore
  py/BUILD.bazel
  py/conftest.py
  py/selenium/webdriver/common/bidi/script.py
  py/selenium/webdriver/common/bidi/session.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/websocket_connection.py
  py/test/selenium/webdriver/common/bidi_script_tests.py
  rb/spec/integration/selenium/webdriver/bidi/script_spec.rb
Labels: C-py, C-devtools, enhancement

#14152 [rb] Adds support for the w3c silent option for the ruby library
  rb/lib/selenium/webdriver/ie/options.rb
  rb/spec/unit/selenium/webdriver/ie/options_spec.rb
Labels: Review effort [1-5]: 2, Bug fix, tests

#14148 [java][grid]: video file name set independently in dynamic grid via se:videoName
  java/src/org/openqa/selenium/grid/node/docker/DockerSessionFactory.java
Labels: C-grid, enhancement, Review effort [1-5]: 2

#14155 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14135 [bidi][js] Add high-level logging API
  javascript/node/selenium-webdriver/bidi/logInspector.js
  javascript/node/selenium-webdriver/lib/script.js
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/test/lib/webdriver_script_test.js
Labels: enhancement, Review effort [1-5]: 3, tests

#14140 [js] Fix locate nodes BiDi test
  javascript/node/selenium-webdriver/test/bidi/locate_nodes_test.js
Labels: Review effort [1-5]: 2, Bug fix

#14128 [py] remove desired capabilities argument for Webkitgtk
  py/selenium/webdriver/webkitgtk/webdriver.py
  py/selenium/webdriver/wpewebkit/webdriver.py
Labels: Review effort [1-5]: 2, Bug fix

#14122 [build] create a stage release workflow for after the pre-release PR
  .github/workflows/stage-release.yml
  Rakefile
Labels: C-build, enhancement, Review effort [1-5]: 3, configuration changes

#14054 [java] minor performance improvements and code cleanup
  java/src/org/openqa/selenium/Cookie.java
  java/src/org/openqa/selenium/chromium/ChromiumOptions.java
  java/src/org/openqa/selenium/firefox/FileExtension.java
  java/src/org/openqa/selenium/grid/commands/CompletionCommand.java
  java/src/org/openqa/selenium/grid/config/ConcatenatingConfig.java
  java/src/org/openqa/selenium/logging/LogLevelMapping.java
  java/src/org/openqa/selenium/print/PrintOptions.java
  java/src/org/openqa/selenium/remote/RemoteLogs.java
  java/src/org/openqa/selenium/support/events/EventFiringDecorator.java
  java/test/org/openqa/selenium/ExecutingAsyncJavascriptTest.java
  java/test/org/openqa/selenium/ExecutingJavascriptTest.java
  java/test/org/openqa/selenium/build/BazelBuild.java
  java/test/org/openqa/selenium/grid/router/SessionQueueGridWithTimeoutTest.java
  java/test/org/openqa/selenium/ie/InternetExplorerDriverTest.java
  java/test/org/openqa/selenium/remote/RemoteWebDriverUnitTest.java
Labels: C-java, enhancement, Review effort [1-5]: 2, tests

#14163 [build] Prepare for release of Selenium 4.22.0
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v126/BUILD.bazel
  common/devtools/chromium/v126/browser_protocol.pdl
  common/devtools/chromium/v126/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v126/V126Domains.cs
  dotnet/src/webdriver/DevTools/v126/V126JavaScript.cs
  dotnet/src/webdriver/DevTools/v126/V126Log.cs
  dotnet/src/webdriver/DevTools/v126/V126Network.cs
  dotnet/src/webdriver/DevTools/v126/V126Target.cs
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v126/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v126/v126CdpInfo.java
  java/src/org/openqa/selenium/devtools/v126/v126Domains.java
  java/src/org/openqa/selenium/devtools/v126/v126Events.java
  java/src/org/openqa/selenium/devtools/v126/v126Javascript.java
  java/src/org/openqa/selenium/devtools/v126/v126Log.java
  java/src/org/openqa/selenium/devtools/v126/v126Network.java
  java/src/org/openqa/selenium/devtools/v126/v126Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  package-lock.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/setup.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
Labels: C-build, dependencies, enhancement, Review effort [1-5]: 4

#14169 [rust] Update Rust changelog for version 0.4.22
  rust/CHANGELOG.md
Labels: C-rust, documentation

#14171 Added requirements.txt to doc build environment
  py/tox.ini
Labels: documentation, Bug fix, Review effort [1-5]: 1

#14168 [py] property strict_timestamp was added
  py/selenium/webdriver/firefox/firefox_profile.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#13978 [dotnet] Log http requests/responses via internal DiagnosticsHttpHandler
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#13796 [rb] Add FedCM support to the ruby selenium client
  common/src/web/fedcm/fedcm.html
  common/src/web/fedcm/fedcm.json
  rb/lib/selenium/webdriver/chromium/driver.rb
  rb/lib/selenium/webdriver/common.rb
  rb/lib/selenium/webdriver/common/driver_extensions/has_fedcm_dialog.rb
  rb/lib/selenium/webdriver/common/fedcm.rb
  rb/lib/selenium/webdriver/common/fedcm/account.rb
  rb/lib/selenium/webdriver/common/fedcm/dialog.rb
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/lib/selenium/webdriver/remote/bridge/commands.rb
  rb/sig/lib/selenium/webdriver/fedcm/account.rbs
  rb/sig/lib/selenium/webdriver/fedcm/dialog.rbs
  rb/sig/lib/selenium/webdriver/remote/bridge.rbs
  rb/spec/integration/selenium/webdriver/fedcm_spec.rb
  rb/spec/unit/selenium/webdriver/common/fedcm/account_spec.rb
  rb/spec/unit/selenium/webdriver/common/fedcm/dialog_spec.rb
Labels: enhancement, Review effort [1-5]: 3, tests

#13906 [rb] Run remote tests on RBE
  .github/workflows/ci-ruby.yml
  .skipped-tests
  rb/spec/integration/selenium/webdriver/driver_spec.rb
  rb/spec/integration/selenium/webdriver/firefox/profile_spec.rb
  rb/spec/integration/selenium/webdriver/spec_helper.rb
  rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb
  rb/spec/tests.bzl
Labels: enhancement, Review effort [1-5]: 3, tests

#14174 [rb] Add URLs constant to update error messages
  rb/lib/selenium/webdriver/common/error.rb
  rb/sig/lib/selenium/webdriver/common/error.rbs
  rb/spec/integration/selenium/webdriver/error_spec.rb
  rb/spec/unit/selenium/webdriver/common/driver_finder_spec.rb
Labels: enhancement, Review effort [1-5]: 3, tests

#14192 [js][bidi] Fix the event unsubscribe method. Update modules to have close methods.
  javascript/node/selenium-webdriver/bidi/browsingContextInspector.js
  javascript/node/selenium-webdriver/bidi/index.js
  javascript/node/selenium-webdriver/bidi/logInspector.js
  javascript/node/selenium-webdriver/bidi/network.js
  javascript/node/selenium-webdriver/bidi/scriptManager.js
  javascript/node/selenium-webdriver/test/bidi/add_intercept_parameters_test.js
  javascript/node/selenium-webdriver/test/bidi/bidi_test.js
  javascript/node/selenium-webdriver/test/bidi/browsingcontext_inspector_test.js
  javascript/node/selenium-webdriver/test/bidi/network_test.js
  javascript/node/selenium-webdriver/test/bidi/script_test.js
Labels: enhancement, Review effort [1-5]: 3, Bug fix, tests

#14193 Bump JS dependencies
  javascript/node/selenium-webdriver/package.json
  pnpm-lock.yaml
Labels: dependencies, enhancement, Review effort [1-5]: 2

#14187 [py] websocket-client v.1.8.0 was added to setup.py
  py/BUILD.bazel
  py/setup.py
Labels: dependencies, Bug fix, Review effort [1-5]: 1
