Repository SeleniumHQ/selenium, pull requests merged in 2024-05, with the labels that each got.

#13890 Bump `rules_jvm_external` to 6.1
  MODULE.bazel
Labels: enhancement, Review effort [1-5]: 1

#13891 Bump to Bazel 7.1.1
  .bazelversion
Labels: enhancement, Review effort [1-5]: 1

#13893 [bazel + js] Allow `bazel build //javascript/...` to work
  javascript/grid-ui/BUILD.bazel
  javascript/grid-ui/tsconfig.json
  javascript/node/selenium-webdriver/BUILD.bazel
Labels: enhancement, Review effort [1-5]: 3

#13895 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 1

#13892 [py] removed unused logger object from `firefox/webdriver.py`
  py/selenium/webdriver/firefox/webdriver.py
Labels: Bug fix, Review effort [1-5]: 1

#13899 [js] Ensure 'selectVisibleByText' method is same as other languages
  common/src/web/select_space.html
  javascript/node/selenium-webdriver/lib/select.js
  javascript/node/selenium-webdriver/lib/test/fileserver.js
  javascript/node/selenium-webdriver/test/select_test.js
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#13856 [grid] flatten combined routes to improve routing
  java/src/org/openqa/selenium/remote/http/Route.java
  java/test/org/openqa/selenium/remote/http/RouteTest.java
Labels: enhancement, Review effort [1-5]: 3

#13834 [Java] Java language level aids
  java/test/org/openqa/selenium/ExecutingJavascriptTest.java
  java/test/org/openqa/selenium/ProxyTest.java
  java/test/org/openqa/selenium/environment/webserver/Utf8Handler.java
  java/test/org/openqa/selenium/grid/distributor/AddingNodesTest.java
  java/test/org/openqa/selenium/json/JsonOutputTest.java
  java/test/org/openqa/selenium/json/JsonTest.java
  java/test/org/openqa/selenium/remote/DesiredCapabilitiesTest.java
  java/test/org/openqa/selenium/remote/codec/w3c/W3CHttpResponseCodecTest.java
Labels: enhancement, Review effort [1-5]: 2

#13880 [grid][java]: apply protocol version in relay session factory
  java/src/org/openqa/selenium/grid/node/relay/RelaySessionFactory.java
Labels: Review effort [1-5]: 2, Bug fix

#13858 [java][sm] Configure Selenium Manager environment from System Properties
  java/src/org/openqa/selenium/manager/SeleniumManager.java
Labels: enhancement, Review effort [1-5]: 3

#13907 [java][grid]: Set test name to video file name in dynamic grid
  java/src/org/openqa/selenium/grid/node/docker/DockerSessionFactory.java
Labels: enhancement, Review effort [1-5]: 3

#13854 [grid][java]: session-timeout set connection timeout in RemoteNode
  java/src/org/openqa/selenium/grid/data/NodeStatus.java
  java/src/org/openqa/selenium/grid/distributor/AddNode.java
  java/src/org/openqa/selenium/grid/distributor/GridModel.java
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/src/org/openqa/selenium/grid/node/Node.java
  java/src/org/openqa/selenium/grid/node/k8s/OneShotNode.java
  java/src/org/openqa/selenium/grid/node/local/LocalNode.java
  java/src/org/openqa/selenium/grid/node/remote/RemoteNode.java
  java/src/org/openqa/selenium/redis/GridRedisClient.java
  java/test/org/openqa/selenium/grid/data/NodeStatusTest.java
  java/test/org/openqa/selenium/grid/distributor/AddingNodesTest.java
  java/test/org/openqa/selenium/grid/distributor/selector/DefaultSlotSelectorTest.java
  java/test/org/openqa/selenium/grid/node/NodeTest.java
Labels: enhancement, Review effort [1-5]: 3

#13909 [java] type casting and numeric improvements
  java/src/org/openqa/selenium/devtools/CdpClientGenerator.java
  java/src/org/openqa/selenium/support/AbstractFindByBuilder.java
  java/src/org/openqa/selenium/support/Color.java
  java/test/org/openqa/selenium/bidi/input/DefaultMouseTest.java
  java/test/org/openqa/selenium/bidi/input/DragAndDropTest.java
  java/test/org/openqa/selenium/interactions/DefaultMouseTest.java
  java/test/org/openqa/selenium/interactions/PenPointerTest.java
Labels: enhancement, Review effort [1-5]: 2

#13847 [cdp][java] Allow filters to recover from failed requests in NetworkInterceptor
  java/src/org/openqa/selenium/devtools/RequestFailedException.java
  java/src/org/openqa/selenium/devtools/idealized/Network.java
  java/test/org/openqa/selenium/devtools/NetworkInterceptorTest.java
Labels: enhancement, Review effort [1-5]: 3, tests

#13903 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13916 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13902 [js] Ensure parity in the locators used by methods
  javascript/node/selenium-webdriver/lib/select.js
Labels: C-nodejs, enhancement, Review effort [1-5]: 3, Bug fix

#13924 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13921 [java] allow a DevTools listener to determinate the order of handler calls
  java/src/org/openqa/selenium/devtools/Connection.java
  java/src/org/openqa/selenium/devtools/DevTools.java
Labels: enhancement, Review effort [1-5]: 2

#13926 Moving ignore_local_proxy_environment_variables to BaseOptions
  py/selenium/webdriver/common/options.py
Labels: enhancement, Review effort [1-5]: 2

#13935 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13900 [dotnet] Overwrite internal log file if it already exists
  dotnet/src/webdriver/Internal/Logging/FileLogHandler.cs
  dotnet/test/common/Internal/Logging/FileLogHandlerTest.cs
Labels: enhancement, Review effort [1-5]: 2, tests

#13901 [dotnet] Align binary location property for FirefoxOptions with other options
  dotnet/src/webdriver/Firefox/FirefoxOptions.cs
  dotnet/test/common/Environment/DriverFactory.cs
Labels: enhancement, Review effort [1-5]: 2

#13945 [build] Prepare for release of Selenium 4.21.0
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v125/BUILD.bazel
  common/devtools/chromium/v125/browser_protocol.pdl
  common/devtools/chromium/v125/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v125/V125Domains.cs
  dotnet/src/webdriver/DevTools/v125/V125JavaScript.cs
  dotnet/src/webdriver/DevTools/v125/V125Log.cs
  dotnet/src/webdriver/DevTools/v125/V125Network.cs
  dotnet/src/webdriver/DevTools/v125/V125Target.cs
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/bidi/browsingcontext/LocateNodeParameters.java
  java/src/org/openqa/selenium/devtools/v125/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v125/v125CdpInfo.java
  java/src/org/openqa/selenium/devtools/v125/v125Domains.java
  java/src/org/openqa/selenium/devtools/v125/v125Events.java
  java/src/org/openqa/selenium/devtools/v125/v125Javascript.java
  java/src/org/openqa/selenium/devtools/v125/v125Log.java
  java/src/org/openqa/selenium/devtools/v125/v125Network.java
  java/src/org/openqa/selenium/devtools/v125/v125Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/test/org/openqa/selenium/bidi/browsingcontext/LocateNodesTest.java
  java/test/org/openqa/selenium/bidi/storage/StorageCommandsTest.java
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/bidi/browsingContext.js
  javascript/node/selenium-webdriver/package.json
  javascript/node/selenium-webdriver/test/bidi/locate_nodes_test.js
  package-lock.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/setup.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
  rb/spec/integration/selenium/webdriver/bidi_spec.rb
  rust/CHANGELOG.md
Labels: C-build

#13960 [dotnet] change source of navigation alias
  dotnet/src/webdriver/Navigator.cs
  dotnet/src/webdriver/WebDriver.cs
Labels: C-dotnet, enhancement, Review effort [1-5]: 2

#13414 [rust] Include mixed output (INFO, WARN, DEBUG, etc. to stderr and minimal JSON to stdout)
  rust/src/logger.rs
  rust/src/main.rs
  rust/tests/grid_tests.rs
  rust/tests/output_tests.rs
Labels: C-rust

#13998 Add `selenium-manager` executables to python manifest
  py/MANIFEST.in
Labels: enhancement, Bug fix, Review effort [1-5]: 1

#13942 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14011 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14013 [java][bidi] Remove non-relevant annotations
  java/test/org/openqa/selenium/bidi/BiDiSessionTest.java
  java/test/org/openqa/selenium/bidi/BiDiTest.java
  java/test/org/openqa/selenium/bidi/browser/BrowserCommandsTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextInspectorTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/LocateNodesTest.java
  java/test/org/openqa/selenium/bidi/input/CombinedInputActionsTest.java
  java/test/org/openqa/selenium/bidi/input/DefaultKeyboardTest.java
  java/test/org/openqa/selenium/bidi/input/DefaultMouseTest.java
  java/test/org/openqa/selenium/bidi/input/DefaultWheelTest.java
  java/test/org/openqa/selenium/bidi/input/DragAndDropTest.java
  java/test/org/openqa/selenium/bidi/input/ReleaseCommandTest.java
  java/test/org/openqa/selenium/bidi/input/SetFilesCommandTest.java
  java/test/org/openqa/selenium/bidi/network/AddInterceptParametersTest.java
  java/test/org/openqa/selenium/bidi/network/NetworkCommandsTest.java
  java/test/org/openqa/selenium/bidi/network/NetworkEventsTest.java
  java/test/org/openqa/selenium/bidi/script/CallFunctionParameterTest.java
  java/test/org/openqa/selenium/bidi/script/LocalValueTest.java
  java/test/org/openqa/selenium/bidi/script/ScriptCommandsTest.java
  java/test/org/openqa/selenium/bidi/script/ScriptEventsTest.java
  java/test/org/openqa/selenium/bidi/storage/StorageCommandsTest.java
Labels: enhancement, Review effort [1-5]: 2

#14029 [java] Add convenience for enabling BiDi
  java/src/org/openqa/selenium/chromium/ChromiumOptions.java
  java/src/org/openqa/selenium/firefox/FirefoxOptions.java
  java/test/org/openqa/selenium/bidi/BiDiSessionCleanUpTest.java
  java/test/org/openqa/selenium/testing/drivers/Browser.java
Labels: C-java, enhancement, Review effort [1-5]: 2, tests

#14037 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14044 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#14038 14035: Add 'toJson' method to produce expected serialization
  java/src/org/openqa/selenium/Rectangle.java
Labels: C-java, enhancement, Review effort [1-5]: 2

#14046 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2, configuration changes
