Repository SeleniumHQ/selenium, pull requests merged in 2024-03, with the labels that each got.

#13677 [bidi] [java] Add browser module
  java/src/org/openqa/selenium/bidi/Browser.java
  java/test/org/openqa/selenium/bidi/browser/BUILD.bazel
  java/test/org/openqa/selenium/bidi/browser/BrowserCommandsTest.java
  javascript/node/selenium-webdriver/bidi/browser.js
  javascript/node/selenium-webdriver/test/bidi/browser_test.js
Labels: enhancement, Review effort [1-5]: 2

#13673 [dotnet] Add dispose on constructor failure to ensure driver closes
  dotnet/src/webdriver/WebDriver.cs
Labels: Review effort [1-5]: 2, Bug fix

#13704 [bidi][js] Add continueRequest and continueResponse command
  javascript/node/selenium-webdriver/bidi/continueRequestParameters.js
  javascript/node/selenium-webdriver/bidi/continueResponseParameters.js
  javascript/node/selenium-webdriver/bidi/network.js
  javascript/node/selenium-webdriver/bidi/networkTypes.js
  javascript/node/selenium-webdriver/test/bidi/network_commands_test.js
Labels: enhancement, Review effort [1-5]: 3, tests

#13708 [bidi] Add provide response command
  java/src/org/openqa/selenium/bidi/module/Network.java
  java/src/org/openqa/selenium/bidi/network/ProvideResponseParameters.java
  java/test/org/openqa/selenium/bidi/network/NetworkCommandsTest.java
  javascript/node/selenium-webdriver/bidi/network.js
  javascript/node/selenium-webdriver/bidi/provideResponseParameters.js
  javascript/node/selenium-webdriver/test/bidi/network_commands_test.js
Labels: C-java, C-nodejs, enhancement, Review effort [1-5]: 2, tests

#13699 [rust] Bump clap to version 4.5.2
  WORKSPACE
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
Labels: C-rust, Review effort [1-5]: 1

#13711 [bidi][java][js] Add setFiles command of the Input Module
  java/src/org/openqa/selenium/bidi/module/Input.java
  java/test/org/openqa/selenium/bidi/input/SetFilesCommandTest.java
  javascript/node/selenium-webdriver/bidi/input.js
  javascript/node/selenium-webdriver/bidi/protocolValue.js
  javascript/node/selenium-webdriver/test/bidi/setFiles_command_test.js
Labels: enhancement, Review effort [1-5]: 3

#13713 [bazel] Bump to 7.1.0 without bzlmod
  .bazelrc
  .bazelversion
  MODULE.bazel
  WORKSPACE
  WORKSPACE.bzlmod
  java/private/export.bzl
  java/private/module.bzl
  java/private/selenium_test.bzl
  java/test/org/openqa/selenium/testing/drivers/BUILD.bazel
  java/test/org/openqa/selenium/testing/drivers/OutOfProcessSeleniumServer.java
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#13698 [dotnet] Support setting timeouts in capabilities
  dotnet/src/webdriver/DriverOptions.cs
  dotnet/src/webdriver/Timeouts.cs
  dotnet/test/common/Environment/DriverFactory.cs
  dotnet/test/common/TimeoutDriverOptionsTest.cs
Labels: enhancement, Review effort [1-5]: 2, tests

#13725 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13680 Add JSON serialization for ShadowRoot
  .gitignore
  java/spotbugs-excludes.xml
  java/src/org/openqa/selenium/remote/RemoteWebDriver.java
  java/src/org/openqa/selenium/remote/WebElementToJsonConverter.java
  java/src/org/openqa/selenium/remote/codec/w3c/W3CHttpCommandCodec.java
  java/src/org/openqa/selenium/remote/internal/WebElementToJsonConverter.java
  java/test/org/openqa/selenium/remote/BUILD.bazel
  java/test/org/openqa/selenium/remote/WebElementToJsonConverterTest.java
  java/test/org/openqa/selenium/remote/internal/BUILD.bazel
  java/test/org/openqa/selenium/support/pagefactory/UsingPageFactoryTest.java
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#13727 [dotnet] Enable internal logging at trace level for unit tests
  dotnet/test/common/AssemblyFixture.cs
Labels: enhancement, tests, Review effort [1-5]: 1

#13737 Update script commands to fix the failing BiDi tests
  java/src/org/openqa/selenium/bidi/module/Script.java
  java/test/org/openqa/selenium/bidi/script/ScriptCommandsTest.java
  javascript/node/selenium-webdriver/bidi/scriptManager.js
  javascript/node/selenium-webdriver/test/bidi/script_test.js
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#13736 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13694 install_addon() didn't take into account dir paths with trailing slashes
  py/selenium/webdriver/firefox/webdriver.py
Labels: Review effort [1-5]: 2, bug_fix

#13491 Explicitly export Select and WebDriverWait from selenium.webdriver.support.ui
  py/selenium/webdriver/support/ui.py
Labels: C-py

#13490 Add return type to webelement.submit
  py/selenium/webdriver/remote/webelement.py
Labels: C-py

#13528 [java] Remove "se:bidi"
  java/src/org/openqa/selenium/bidi/BiDiProvider.java
  java/src/org/openqa/selenium/grid/node/ProxyNodeWebsockets.java
  java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java
  java/src/org/openqa/selenium/grid/node/local/LocalNode.java
Labels: C-java

#13492 Add type to parameter of webelement.WebElement.send_keys
  py/selenium/webdriver/remote/webelement.py
Labels: C-py

#13740 [rust] Use apple-flat-package crate to extract PKG files
  WORKSPACE
  rust/BUILD.bazel
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/files.rs
  rust/src/lib.rs
Labels: C-rust, enhancement, Review effort [1-5]: 3, bug_fix

#13705 [rust] Fix Edge management in RPM-based Linux
  rust/src/files.rs
Labels: C-rust, enhancement, Review effort [1-5]: 2

#13741 [rust] Enhance logic to uncompress DEB files and set toolchain version
  rust/src/files.rs
Labels: C-rust, enhancement, Review effort [1-5]: 2, bug_fix

#13743 [bidi][java] Update the capture screenshot APIs to include all parameters and remove scroll parameter
  java/src/org/openqa/selenium/bidi/browsingcontext/BoxClipRectangle.java
  java/src/org/openqa/selenium/bidi/browsingcontext/BrowsingContext.java
  java/src/org/openqa/selenium/bidi/browsingcontext/CaptureScreenshotParameters.java
  java/src/org/openqa/selenium/bidi/browsingcontext/ClipRectangle.java
  java/src/org/openqa/selenium/bidi/browsingcontext/ElementClipRectangle.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextTest.java
Labels: C-java, C-devtools, enhancement, Bug fix, Review effort [1-5]: 4

#13742 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#13747 Release 4.19.0
  AUTHORS
  Rakefile
  common/devtools/chromium/v123/BUILD.bazel
  common/devtools/chromium/v123/browser_protocol.pdl
  common/devtools/chromium/v123/js_protocol.pdl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v123/V123Domains.cs
  dotnet/src/webdriver/DevTools/v123/V123JavaScript.cs
  dotnet/src/webdriver/DevTools/v123/V123Log.cs
  dotnet/src/webdriver/DevTools/v123/V123Network.cs
  dotnet/src/webdriver/DevTools/v123/V123Target.cs
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_deps.bzl
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v123/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v123/v123CdpInfo.java
  java/src/org/openqa/selenium/devtools/v123/v123Domains.java
  java/src/org/openqa/selenium/devtools/v123/v123Events.java
  java/src/org/openqa/selenium/devtools/v123/v123Javascript.java
  java/src/org/openqa/selenium/devtools/v123/v123Log.java
  java/src/org/openqa/selenium/devtools/v123/v123Network.java
  java/src/org/openqa/selenium/devtools/v123/v123Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  package-lock.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/setup.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
  rust/BUILD.bazel
  rust/CHANGELOG.md
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#13744 [bidi][js] Update the capture screenshot APIs to include all parameters and remove scroll parameter
  javascript/node/selenium-webdriver/bidi/browsingContext.js
  javascript/node/selenium-webdriver/bidi/captureScreenshotParameters.js
  javascript/node/selenium-webdriver/bidi/clipRectangle.js
  javascript/node/selenium-webdriver/test/bidi/browsingcontext_test.js
Labels: C-nodejs, C-devtools, enhancement, Review effort [1-5]: 3, bug_fix
