Repository SeleniumHQ/selenium, pull requests merged in 2024-11, with the labels that each got.

#14699 [py] Fix TypeError when init Safari webdriver
  .github/workflows/ci-python.yml
  py/selenium/webdriver/safari/webdriver.py
  py/test/selenium/webdriver/safari/launcher_tests.py
Labels: Review effort [1-5]: 2

#14559 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort [1-5]: 1

#14706 [py] Fixed Flaky Upload Tests
  py/test/selenium/webdriver/common/upload_tests.py
Labels: Review effort [1-5]: 2

#14701 [py] Fixed Flaky Bidi Test
  py/test/selenium/webdriver/common/bidi_tests.py
Labels: Review effort [1-5]: 2

#14675 [py] Added Deprecation of WebElement.get_attribute() per #13334
  py/selenium/webdriver/remote/webelement.py
Labels: C-py, Review effort [1-5]: 2

#14705 [py] add a new ExtendedHandler in webserver.py
  py/test/selenium/webdriver/common/webserver.py
Labels: Review effort [1-5]: 3

#14700 [py] add safari service tests
  .github/workflows/ci-python.yml
  py/test/selenium/webdriver/common/alerts_tests.py
  py/test/selenium/webdriver/common/api_example_tests.py
  py/test/selenium/webdriver/common/interactions_tests.py
  py/test/selenium/webdriver/common/interactions_with_device_tests.py
  py/test/selenium/webdriver/common/position_and_size_tests.py
  py/test/selenium/webdriver/common/selenium_manager_tests.py
  py/test/selenium/webdriver/common/upload_tests.py
  py/test/selenium/webdriver/common/w3c_interaction_tests.py
  py/test/selenium/webdriver/common/webdriverwait_tests.py
  py/test/selenium/webdriver/common/window_switching_tests.py
  py/test/selenium/webdriver/safari/__init__.py
  py/test/selenium/webdriver/safari/safari_service_tests.py
Labels: C-py, Review effort [1-5]: 2

#14702 [java] use common annotations in BiDi tests
  java/test/org/openqa/selenium/bidi/BiDiTest.java
  java/test/org/openqa/selenium/bidi/browser/BrowserCommandsTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextInspectorTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextTest.java
  java/test/org/openqa/selenium/bidi/browsingcontext/LocateNodesTest.java
  java/test/org/openqa/selenium/bidi/input/ReleaseCommandTest.java
  java/test/org/openqa/selenium/bidi/input/SetFilesCommandTest.java
  java/test/org/openqa/selenium/bidi/log/LogInspectorTest.java
  java/test/org/openqa/selenium/bidi/network/AddInterceptParametersTest.java
  java/test/org/openqa/selenium/bidi/network/NetworkCommandsTest.java
  java/test/org/openqa/selenium/bidi/network/NetworkEventsTest.java
  java/test/org/openqa/selenium/bidi/script/CallFunctionParameterTest.java
  java/test/org/openqa/selenium/bidi/script/EvaluateParametersTest.java
  java/test/org/openqa/selenium/bidi/script/ScriptCommandsTest.java
  java/test/org/openqa/selenium/bidi/script/ScriptEventsTest.java
  java/test/org/openqa/selenium/grid/router/RemoteWebDriverBiDiTest.java
Labels: Review effort [1-5]: 2

#14666 [java]: mark WebElement.getAttribute deprecated
  java/src/org/openqa/selenium/WebElement.java
Labels: C-java, Review effort [1-5]: 1

#14707 [java] stream api usage enhancement
  java/src/org/openqa/selenium/By.java
  java/src/org/openqa/selenium/JavascriptExecutor.java
  java/src/org/openqa/selenium/support/pagefactory/ByAll.java
  java/src/org/openqa/selenium/support/pagefactory/ByChained.java
Labels: C-java, Review effort [1-5]: 2

#14711 [java] remove toml parser warning
  java/src/org/openqa/selenium/grid/config/TomlConfig.java
Labels: C-grid, Review effort [1-5]: 1

#14651 [dotnet] Fix API docs static generation
  dotnet/docs/api/index.md
  dotnet/docs/docfx.json
  dotnet/docs/images/favicon.ico
  dotnet/docs/images/logo.svg
  dotnet/docs/index.md
  dotnet/docs/support/.gitignore
  dotnet/docs/toc.yml
  dotnet/docs/webdriver/.gitignore
Labels: C-dotnet, Review effort [1-5]: 2

#14713 [dotnet] Gracefully handle clashing device names
  dotnet/src/webdriver/Interactions/ActionSequence.cs
  dotnet/src/webdriver/Interactions/Actions.cs
  dotnet/test/common/Interactions/CombinedInputActionsTest.cs
Labels: Review effort [1-5]: 3

#14716 [dotnet] Add ChromiumNetworkConditions to command serialization
  dotnet/src/webdriver/Command.cs
Labels: Review effort [1-5]: 1

#14688 [java] deleted the deprecated FormEncodedData
  java/src/org/openqa/selenium/remote/http/FormEncodedData.java
  java/test/org/openqa/selenium/remote/http/FormEncodedDataTest.java
Labels: Review effort [1-5]: 1

#14191 Cleaned up Py doc sphinx warnings/errors and added README
  py/docs/README.rst
  py/selenium/webdriver/chromium/webdriver.py
  py/selenium/webdriver/common/virtual_authenticator.py
  py/selenium/webdriver/support/relative_locator.py
Labels: documentation, Review effort [1-5]: 2, Bug fix

#14616 Throw Error When Using Unsupported Linux ARM
  java/src/org/openqa/selenium/manager/SeleniumManager.java
Labels: Review effort [1-5]: 2, Bug fix

#14095 [java] case insensitive header names in http requests
  java/src/org/openqa/selenium/remote/http/HttpMessage.java
  java/test/org/openqa/selenium/devtools/ChangeUserAgentTest.java
  java/test/org/openqa/selenium/remote/http/DumpHttpExchangeFilterTest.java
  java/test/org/openqa/selenium/remote/http/HttpMessageTest.java
Labels: enhancement, Review effort [1-5]: 2

#14426 [java] feat: Add method to select options containing the provided text
  common/src/web/formPage.html
  java/src/org/openqa/selenium/support/ui/ISelect.java
  java/src/org/openqa/selenium/support/ui/Select.java
  java/test/org/openqa/selenium/support/ui/SelectElementTest.java
  java/test/org/openqa/selenium/support/ui/SelectTest.java
Labels: enhancement, Review effort [1-5]: 3, tests

#14729 [ci][py] Update runners and tests
  .github/workflows/bazel.yml
  .github/workflows/ci-python.yml
  .github/workflows/label-commenter.yml
Labels: Review effort [1-5]: 2

#14677 [py] Updated Handling for DetachedShadowRoot Exception
  py/selenium/common/__init__.py
  py/selenium/common/exceptions.py
  py/selenium/webdriver/remote/errorhandler.py
  py/test/unit/selenium/webdriver/remote/error_handler_tests.py
Labels: C-py, Review effort [1-5]: 2

#14732 [dotnet] Add reflection-based JSON serialization fallback to `Command`s
  dotnet/src/webdriver/Command.cs
  dotnet/test/common/CommandTests.cs
Labels: Review effort [1-5]: 2

#14733 [dotnet] Make Selenium Manager's AOT safety explicit
  dotnet/src/webdriver/SeleniumManager.cs
Labels: Review effort [1-5]: 2

#14680 [py] moved `MANIFEST.in` contents to `pyproject.toml`
  py/BUILD.bazel
  py/MANIFEST.in
  py/pyproject.toml
Labels: C-py, Review effort [1-5]: 2

#14718 [py] Set user_agent and extra_headers via ClientConfig
  py/selenium/webdriver/remote/client_config.py
  py/selenium/webdriver/remote/remote_connection.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py, Review effort [1-5]: 3

#14661 [rb] Reduce RBS errors to 0
  rb/Gemfile.lock
  rb/lib/selenium/webdriver/bidi/log_handler.rb
  rb/lib/selenium/webdriver/bidi/struct.rb
  rb/lib/selenium/webdriver/common/error.rb
  rb/lib/selenium/webdriver/common/fedcm/account.rb
  rb/lib/selenium/webdriver/common/target_locator.rb
  rb/lib/selenium/webdriver/remote/http/common.rb
  rb/sig/lib/selenium/webdriver/bidi.rbs
  rb/sig/lib/selenium/webdriver/bidi/log_handler.rbs
  rb/sig/lib/selenium/webdriver/bidi/struct.rbs
  rb/sig/lib/selenium/webdriver/common/driver_finder.rbs
  rb/sig/lib/selenium/webdriver/common/error.rbs
  rb/sig/lib/selenium/webdriver/common/logger.rbs
  rb/sig/lib/selenium/webdriver/common/options.rbs
  rb/sig/lib/selenium/webdriver/common/selenium_manager.rbs
  rb/sig/lib/selenium/webdriver/common/service.rbs
  rb/sig/lib/selenium/webdriver/common/websocket_connection.rbs
  rb/sig/lib/selenium/webdriver/fedcm/account.rbs
  rb/sig/lib/selenium/webdriver/firefox/options.rbs
  rb/sig/lib/selenium/webdriver/remote/bidi_bridge.rbs
  rb/sig/lib/selenium/webdriver/remote/bridge.rbs
  rb/sig/lib/selenium/webdriver/remote/response.rbs
  rb/sig/selenium/web_driver/script.rbs
Labels: Review effort [1-5]: 4

#14726 [dotnet] Allow `RemoteSessionSettings` to use any value for metadata
  dotnet/src/webdriver/Remote/RemoteSessionSettings.cs
  dotnet/test/remote/RemoteSessionCreationTests.cs
Labels: Review effort [1-5]: 3

#14736 [dotnet] Remove JSON serialization from `.ToString()` methods
  dotnet/src/webdriver/DriverOptions.cs
  dotnet/src/webdriver/Internal/ReturnedCapabilities.cs
  dotnet/src/webdriver/Remote/RemoteSessionSettings.cs
Labels: Review effort [1-5]: 2

#14703 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort [1-5]: 2

#14523 [rb] Add Bidi network commands for authentication and interception
  java/.idea/workspace.xml
  rb/lib/selenium/webdriver/bidi.rb
  rb/lib/selenium/webdriver/bidi/network.rb
  rb/lib/selenium/webdriver/common.rb
  rb/lib/selenium/webdriver/common/driver.rb
  rb/lib/selenium/webdriver/common/network.rb
  rb/sig/lib/selenium/webdriver/bidi/network.rbs
  rb/sig/lib/selenium/webdriver/common/driver.rbs
  rb/sig/lib/selenium/webdriver/common/network.rbs
  rb/spec/integration/selenium/webdriver/bidi/network_spec.rb
  rb/spec/integration/selenium/webdriver/network_spec.rb
Labels: enhancement, tests, Review effort [1-5]: 4

#14386 [bidi][js] Allow passing in uri for authentication handlers
  javascript/node/selenium-webdriver/lib/network.js
  javascript/node/selenium-webdriver/test/lib/webdriver_network_test.js
Labels: enhancement, Review effort [1-5]: 3, tests

#14424 [bidi][java] Add network request handler APIs
  java/src/org/openqa/selenium/bidi/network/Header.java
  java/src/org/openqa/selenium/bidi/network/ResponseData.java
  java/src/org/openqa/selenium/remote/Network.java
  java/src/org/openqa/selenium/remote/RemoteNetwork.java
  java/src/org/openqa/selenium/remote/http/HttpMethod.java
  java/test/org/openqa/selenium/WebNetworkTest.java
  java/test/org/openqa/selenium/bidi/network/NetworkEventsTest.java
Labels: enhancement, tests, Review effort [1-5]: 4

#14723 [py] add edge driver tests
  .github/workflows/ci-python.yml
  .skipped-tests
  py/test/selenium/webdriver/edge/conftest.py
  py/test/selenium/webdriver/edge/edge_service_tests.py
Labels: Review effort [1-5]: 3

#14737 [dotnet] Fix `RelativeBy.Near` and empty list return, port Java tests
  dotnet/src/webdriver/RelativeBy.cs
  dotnet/test/common/RelativeLocatorTest.cs
Labels: Review effort [1-5]: 2

#14710 [🚀 Feature] [py]: Support FedCM commands for python
  py/selenium/webdriver/common/fedcm/account.py
  py/selenium/webdriver/common/fedcm/dialog.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/remote/command.py
  py/selenium/webdriver/remote/fedcm.py
  py/selenium/webdriver/remote/remote_connection.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/fedcm_tests.py
  py/test/unit/selenium/webdriver/common/fedcm/account_tests.py
  py/test/unit/selenium/webdriver/common/fedcm/dialog_tests.py
Labels: Review effort [1-5]: 4

#14748 [py] Added Common Tests to Edge CI
  .github/workflows/ci-python.yml
  py/BUILD.bazel
Labels: Review effort [1-5]: 1

#14608 [java] Fix SpotBugs bugs in the Selenium manager
  java/spotbugs-excludes.xml
  java/src/org/openqa/selenium/manager/SeleniumManager.java
  java/src/org/openqa/selenium/manager/SeleniumManagerOutput.java
Labels: Review effort [1-5]: 2, Bug fix

#14756 [grid] detect a client timeout while session creation #14743
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/src/org/openqa/selenium/grid/sessionqueue/local/LocalNewSessionQueue.java
  java/test/org/openqa/selenium/grid/router/BUILD.bazel
  java/test/org/openqa/selenium/grid/router/DistributedTest.java
Labels: Review effort [1-5]: 3

#14430 [rb] Handle graceful webdriver shutdown
  rb/lib/selenium/webdriver/common/child_process.rb
  rb/lib/selenium/webdriver/common/service_manager.rb
Labels: enhancement, Review effort [1-5]: 3, tests

#14742 [dotnet] Make `FirefoxProfile` AOT-safe
  dotnet/src/webdriver/Firefox/FirefoxProfile.cs
  dotnet/src/webdriver/Firefox/Preferences.cs
Labels: Review effort [1-5]: 3

#14672 [dotnet] Enable NRT on exceptional types
  dotnet/src/webdriver/DefaultFileDetector.cs
  dotnet/src/webdriver/DetachedShadowRootException.cs
  dotnet/src/webdriver/DevTools/CommandResponseException.cs
  dotnet/src/webdriver/DriverServiceNotFoundException.cs
  dotnet/src/webdriver/ElementClickInterceptedException.cs
  dotnet/src/webdriver/ElementNotInteractableException.cs
  dotnet/src/webdriver/ElementNotSelectableException.cs
  dotnet/src/webdriver/ElementNotVisibleException.cs
  dotnet/src/webdriver/ErrorResponse.cs
  dotnet/src/webdriver/Firefox/FirefoxDriver.cs
  dotnet/src/webdriver/IFileDetector.cs
  dotnet/src/webdriver/InsecureCertificateException.cs
  dotnet/src/webdriver/Internal/NullableAttributes.cs
  dotnet/src/webdriver/InvalidCookieDomainException.cs
  dotnet/src/webdriver/InvalidElementStateException.cs
  dotnet/src/webdriver/InvalidSelectorException.cs
  dotnet/src/webdriver/JavaScriptException.cs
  dotnet/src/webdriver/MoveTargetOutOfBoundsException.cs
  dotnet/src/webdriver/NoAlertPresentException.cs
  dotnet/src/webdriver/NoSuchDriverException.cs
  dotnet/src/webdriver/NoSuchElementException.cs
  dotnet/src/webdriver/NoSuchFrameException.cs
  dotnet/src/webdriver/NoSuchShadowRootException.cs
  dotnet/src/webdriver/NoSuchWindowException.cs
  dotnet/src/webdriver/NotFoundException.cs
  dotnet/src/webdriver/Remote/LocalFileDetector.cs
  dotnet/src/webdriver/StackTraceElement.cs
  dotnet/src/webdriver/StaleElementReferenceException.cs
  dotnet/src/webdriver/UnableToSetCookieException.cs
  dotnet/src/webdriver/UnhandledAlertException.cs
  dotnet/src/webdriver/WebDriverArgumentException.cs
  dotnet/src/webdriver/WebDriverException.cs
  dotnet/src/webdriver/WebDriverTimeoutException.cs
  dotnet/src/webdriver/XPathLookupException.cs
Labels: C-dotnet, Review effort [1-5]: 3

#14619 [rust] Selenium Manager honors full browser version (#13419)
  rust/src/chrome.rs
  rust/src/lib.rs
  rust/tests/browser_download_tests.rs
Labels: C-rust, enhancement, Review effort [1-5]: 3, tests

#14775 [dotnet] Propagate async throughout test setup and teardown
  dotnet/test/chrome/ChromeSpecificTests.cs
  dotnet/test/common/AssemblyFixture.cs
  dotnet/test/common/Environment/EnvironmentManager.cs
  dotnet/test/common/Environment/RemoteSeleniumServer.cs
  dotnet/test/common/Environment/TestWebServer.cs
  dotnet/test/edge/AssemblyTeardown.cs
  dotnet/test/firefox/AssemblyTeardown.cs
  dotnet/test/ie/AssemblyTeardown.cs
  dotnet/test/remote/AssemblyTeardown.cs
  dotnet/test/support/UI/PopupWindowFinderTest.cs
  dotnet/test/support/UI/SelectBrowserTests.cs
Labels: Review effort [1-5]: 2

#14747 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort [1-5]: 1

#14774 Add funding information to package.json and gemspec files
  javascript/node/selenium-webdriver/package.json
  rb/selenium-devtools.gemspec
  rb/selenium-webdriver.gemspec
Labels: Review effort [1-5]: 1

#14770 [rb] Resolve `uri` gem deprecation warning
  rb/lib/selenium/webdriver/remote/bridge.rb
Labels: C-rb, bug, Review effort [1-5]: 1

#14708 [dotnet] Solidify nullability of `PinnedScript`, add test
  dotnet/src/support/Events/EventFiringWebDriver.cs
  dotnet/src/webdriver/IJavaScriptEngine.cs
  dotnet/src/webdriver/IJavascriptExecutor.cs
  dotnet/src/webdriver/ISearchContext.cs
  dotnet/src/webdriver/JavaScriptEngine.cs
  dotnet/src/webdriver/PinnedScript.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/test/common/ExecutingJavascriptTest.cs
Labels: C-dotnet, Review effort [1-5]: 3

#14311 [py] moved project metadata from `setup.py` to `pyproject.toml`
  py/pyproject.toml
  py/setup.py
Labels: R-awaiting merge, C-py, enhancement, Review effort [1-5]: 2

#14759 [dotnet] Add CDP deprecation warning for Firefox
  dotnet/src/webdriver/Firefox/FirefoxDriver.cs
  dotnet/src/webdriver/Remote/RemoteWebDriver.cs
Labels: Review effort [1-5]: 1

#14739 [ci][py] Update latest index for new Nightly upload
  Rakefile
  py/BUILD.bazel
  py/docs/source/conf.py
  py/pyproject.toml
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/setup.py
Labels: Review effort [1-5]: 1

#14094 [rb] implement navigation commands with BiDi
  rb/lib/selenium/webdriver/bidi/browsing_context.rb
  rb/lib/selenium/webdriver/bidi/browsing_context_info.rb
  rb/lib/selenium/webdriver/bidi/navigate_result.rb
  rb/lib/selenium/webdriver/remote/bidi_bridge.rb
  rb/sig/lib/selenium/webdriver/bidi/browsing_context.rbs
  rb/sig/lib/selenium/webdriver/remote/bidi_bridge.rbs
  rb/spec/integration/selenium/webdriver/bidi/browsing_context_spec.rb
  rb/spec/integration/selenium/webdriver/navigation_spec.rb
Labels: A-needs decision, C-rb, C-devtools, enhancement, Review effort [1-5]: 3, tests

#14776 [dotnet] Modernize exception handling in tests
  dotnet/src/webdriver/WebDriver.cs
  dotnet/test/common/AlertsTest.cs
  dotnet/test/common/CorrectEventFiringTest.cs
  dotnet/test/common/ElementAttributeTest.cs
  dotnet/test/common/Environment/RemoteSeleniumServer.cs
  dotnet/test/common/ExecutingJavascriptTest.cs
  dotnet/test/common/FrameSwitchingTest.cs
  dotnet/test/common/TargetLocatorTest.cs
  dotnet/test/common/WindowSwitchingTest.cs
  dotnet/test/support/Extensions/ExecuteJavaScriptTest.cs
Labels: Review effort [1-5]: 3

#14762 [py] Added Deprecation of CDP for Firefox
  py/selenium/webdriver/common/bidi/cdp.py
Labels: C-py, Review effort [1-5]: 2

#14763 [rb] Deprecate CDP methods on Firefox
  rb/lib/selenium/webdriver/common/driver_extensions/has_log_events.rb
  rb/lib/selenium/webdriver/common/driver_extensions/has_network_interception.rb
Labels: C-rb, Review effort [1-5]: 2

#14790 [rb] Downgrade steep to 1.5.2 to avoid issues on windows based pipelines
  rb/Gemfile
  rb/Gemfile.lock
Labels: C-rb, Bug fix, Review effort [1-5]: 1

#14780 [build] Prepare for release of Selenium 4.27.0
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v131/BUILD.bazel
  common/devtools/chromium/v131/browser_protocol.pdl
  common/devtools/chromium/v131/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/paket.dependencies
  dotnet/paket.lock
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v131/V131Domains.cs
  dotnet/src/webdriver/DevTools/v131/V131JavaScript.cs
  dotnet/src/webdriver/DevTools/v131/V131Log.cs
  dotnet/src/webdriver/DevTools/v131/V131Network.cs
  dotnet/src/webdriver/DevTools/v131/V131Target.cs
  dotnet/src/webdriver/WebDriver.StrongNamed.nuspec
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/src/webdriver/WebDriver.nuspec
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v131/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v131/v131CdpInfo.java
  java/src/org/openqa/selenium/devtools/v131/v131Domains.java
  java/src/org/openqa/selenium/devtools/v131/v131Events.java
  java/src/org/openqa/selenium/devtools/v131/v131Javascript.java
  java/src/org/openqa/selenium/devtools/v131/v131Log.java
  java/src/org/openqa/selenium/devtools/v131/v131Network.java
  java/src/org/openqa/selenium/devtools/v131/v131Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/pyproject.toml
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
  rust/CHANGELOG.md
Labels: C-build, Review effort [1-5]: 2

#14773 [dotnet] Add nullability annotations to print types
  dotnet/src/webdriver/EncodedFile.cs
  dotnet/src/webdriver/ISupportsPrint.cs
  dotnet/src/webdriver/PrintDocument.cs
  dotnet/src/webdriver/PrintOptions.cs
  dotnet/src/webdriver/Screenshot.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/test/common/PrintTest.cs
Labels: Review effort [1-5]: 3

#14802 [dotnet] Propagate `IWebDriver.GetAttribute` obsoletion to `WebDriver`
  dotnet/src/support/Events/EventFiringWebDriver.cs
  dotnet/src/webdriver/WebElement.cs
Labels: Review effort [1-5]: 1

#14808 [py] Revert the Deprecation warnings of WebElement.get_attribute()
  py/selenium/webdriver/remote/webelement.py
Labels: Review effort [1-5]: 1

#14806 [py] Fix `pyproject.toml` for installable from sdist
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/pyproject.toml
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/tox.ini
Labels: Review effort [1-5]: 1

#14816 [java]: encapsulate `additionalCommands` with getter method
  java/src/org/openqa/selenium/remote/HttpCommandExecutor.java
  java/test/org/openqa/selenium/remote/RemoteWebDriverInitializationTest.java
Labels: Review effort [1-5]: 1

#14812 [dotnet] Add nullability annotations to `ShadowRoot`
  dotnet/src/webdriver/ISearchContext.cs
  dotnet/src/webdriver/IWrapsDriver.cs
  dotnet/src/webdriver/Internal/IWebDriverObjectReference.cs
  dotnet/src/webdriver/ShadowRoot.cs
  dotnet/src/webdriver/WebDriver.cs
Labels: Review effort [1-5]: 2

#14814 [dotnet] Fix `WebDriver.AuthenticatorId`
  dotnet/src/webdriver/WebDriver.cs
  dotnet/test/common/VirtualAuthn/VirtualAuthenticatorTest.cs
Labels: Review effort [1-5]: 2

#14821 [dotnet] Add future-proofing note on `Base64UrlEncoder`
  dotnet/src/webdriver/Internal/Base64UrlEncoder.cs
Labels: Review effort [1-5]: 1

#14766 [java] SpotBugs exclude `NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE` from the `firefox.AddHasExtensions$1`
  java/spotbugs-excludes.xml
Labels: C-java, Review effort [1-5]: 1

#14829 [bazel] Bump `rules_jvm_external` to 6.6 and use the maven resolver
  MODULE.bazel
  java/maven_install.json
Labels: Review effort [1-5]: 2

#14834 [dotnet] Add nullable reference annotations to `Platform`
  dotnet/src/webdriver/Chromium/ChromiumDriverService.cs
  dotnet/src/webdriver/Firefox/FirefoxDriverService.cs
  dotnet/src/webdriver/Platform.cs
Labels: Review effort [1-5]: 2
