Repository SeleniumHQ/selenium, pull requests merged in 2024-09, with the labels that each got.

#14448 fix type errors for `service.py`, `cdp.py`, `webelement.py` and `remote_connection.py`
  py/selenium/webdriver/common/bidi/cdp.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/remote/remote_connection.py
  py/selenium/webdriver/remote/webelement.py
  py/selenium/webdriver/webkitgtk/service.py
Labels: C-py, Review effort [1-5]: 2, Bug fix

#14433 [rb] Fix add_cause method not being able to process an array of hashes
  rb/lib/selenium/webdriver/remote/response.rb
  rb/sig/lib/selenium/webdriver/remote/response.rbs
  rb/spec/integration/selenium/webdriver/error_spec.rb
Labels: Review effort [1-5]: 2, Bug fix, tests

#14478 replace `fedcm` links with new ones
  common/devtools/chromium/v126/browser_protocol.pdl
  common/devtools/chromium/v127/browser_protocol.pdl
  common/devtools/chromium/v128/browser_protocol.pdl
  java/src/org/openqa/selenium/federatedcredentialmanagement/FederatedCredentialManagementAccount.java
  java/src/org/openqa/selenium/federatedcredentialmanagement/FederatedCredentialManagementDialog.java
  java/src/org/openqa/selenium/federatedcredentialmanagement/HasFederatedCredentialManagement.java
  java/src/org/openqa/selenium/remote/DriverCommand.java
  java/test/org/openqa/selenium/environment/webserver/FedCmIdAssertion.java
  rb/lib/selenium/webdriver/common/fedcm/account.rb
  rb/sig/lib/selenium/webdriver/fedcm/account.rbs
Labels: documentation, Review effort [1-5]: 2

#14459 fix type errors for `input_device` and `file_detector`
  py/selenium/webdriver/common/actions/input_device.py
  py/selenium/webdriver/remote/file_detector.py
Labels: python

#14476 fix type errors for `pointer_input.py`, `wheel_input.py` and `firefox/options.py`
  py/selenium/webdriver/chromium/service.py
  py/selenium/webdriver/common/actions/pointer_input.py
  py/selenium/webdriver/common/actions/wheel_input.py
  py/selenium/webdriver/firefox/options.py
  py/selenium/webdriver/wpewebkit/service.py
Labels: Review effort [1-5]: 2, Bug fix

#14492 [bazel] Bump `rules_jvm_external` to 6.3
  MODULE.bazel
Labels: dependencies, enhancement, Review effort [1-5]: 1

#14489 firefox_profile.py: use `with` statement in zipfile as Python 2.x support is dropped
  py/selenium/webdriver/firefox/firefox_profile.py
Labels: enhancement, Review effort [1-5]: 2

#14491 toml: warn about upcoming change enforcing string to have quotes
  java/src/org/openqa/selenium/grid/config/TomlConfig.java
Labels: enhancement, Review effort [1-5]: 2

#14495 [dotnet] [bidi] Get tree from browsing context as root
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContext.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextNetworkModule.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextScriptModule.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/GetTreeCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/AddInterceptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/AddPreloadScriptCommand.cs
Labels: enhancement, Review effort [1-5]: 2

#14499 [dotnet] Workaround using pre-processor directive
  dotnet/src/webdriver/BUILD.bazel
Labels: enhancement, Bug fix, Review effort [1-5]: 1

#14501 [js] Close CDP websocket connection on driver.quit
  javascript/node/selenium-webdriver/lib/webdriver.js
Labels: C-nodejs, Review effort [1-5]: 2, Bug fix

#14486 `java/CookieHandler`: escape cookie values when required
  java/test/org/openqa/selenium/environment/webserver/CookieHandler.java
Labels: enhancement, Review effort [1-5]: 2

#14493 [rust] Reuse driver mirror URL (when available) to discover Firefox versions (#13941)
  rust/src/firefox.rs
  rust/src/lib.rs
Labels: C-rust, enhancement, Review effort [1-5]: 2

#14505 .gitignore: add py/python.iml
  .gitignore
Labels: other

#14510 [py] fix tests in `correct_event_firing_tests.py`
  py/test/selenium/webdriver/common/correct_event_firing_tests.py
Labels: Review effort [1-5]: 2, Bug fix, tests

#14516 [build] Prepare for release of Selenium 4.25.0
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v129/BUILD.bazel
  common/devtools/chromium/v129/browser_protocol.pdl
  common/devtools/chromium/v129/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v129/V129Domains.cs
  dotnet/src/webdriver/DevTools/v129/V129JavaScript.cs
  dotnet/src/webdriver/DevTools/v129/V129Log.cs
  dotnet/src/webdriver/DevTools/v129/V129Network.cs
  dotnet/src/webdriver/DevTools/v129/V129Target.cs
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v129/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v129/v129CdpInfo.java
  java/src/org/openqa/selenium/devtools/v129/v129Domains.java
  java/src/org/openqa/selenium/devtools/v129/v129Events.java
  java/src/org/openqa/selenium/devtools/v129/v129Javascript.java
  java/src/org/openqa/selenium/devtools/v129/v129Log.java
  java/src/org/openqa/selenium/devtools/v129/v129Network.java
  java/src/org/openqa/selenium/devtools/v129/v129Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/setup.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/common/logger.rb
  rb/lib/selenium/webdriver/common/target_locator.rb
  rb/lib/selenium/webdriver/common/wait.rb
  rb/lib/selenium/webdriver/version.rb
  rust/CHANGELOG.md
Labels: C-build, dependencies, enhancement, documentation, Review effort [1-5]: 3, tests, configuration changes

#14521 [build] Prepare for release of Selenium 4.25.0
  common/selenium_manager.bzl
Labels: C-build, enhancement, documentation, Review effort [1-5]: 2

#14546 [dotnet] Don't include http headers in internal logs
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
Labels: enhancement, Review effort [1-5]: 2
