Repository SeleniumHQ/selenium, pull requests merged in 2024-12, with the labels that each got.

#14822 [dotnet] Fix Virtual Authenticator removal, annotate NRT
  dotnet/src/webdriver/VirtualAuth/Credential.cs
  dotnet/src/webdriver/VirtualAuth/IHasVirtualAuthenticator.cs
  dotnet/src/webdriver/VirtualAuth/VirtualAuthenticatorOptions.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/test/common/VirtualAuthn/VirtualAuthenticatorTest.cs
Labels: Review effort [1-5]: 3

#14840 [dotnet] Annotate Nullable Reference Types on `OpenQA.Selenium.Internal`
  dotnet/src/webdriver/ICapabilities.cs
  dotnet/src/webdriver/Internal/AndroidOptions.cs
  dotnet/src/webdriver/Internal/FileUtilities.cs
  dotnet/src/webdriver/Internal/IFindsElement.cs
  dotnet/src/webdriver/Internal/IHasCapabilitiesDictionary.cs
  dotnet/src/webdriver/Internal/ResourceUtilities.cs
  dotnet/src/webdriver/Internal/ResponseValueJsonConverter.cs
  dotnet/src/webdriver/Internal/ReturnedCapabilities.cs
Labels: Review effort [1-5]: 2

#14819 [dotnet] Annotate nullable reference types in internal logging
  dotnet/src/webdriver/Internal/Logging/ConsoleLogHandler.cs
  dotnet/src/webdriver/Internal/Logging/FileLogHandler.cs
  dotnet/src/webdriver/Internal/Logging/ILogContext.cs
  dotnet/src/webdriver/Internal/Logging/ILogHandler.cs
  dotnet/src/webdriver/Internal/Logging/ILogHandlerList.cs
  dotnet/src/webdriver/Internal/Logging/ILogger.cs
  dotnet/src/webdriver/Internal/Logging/Log.cs
  dotnet/src/webdriver/Internal/Logging/LogContext.cs
  dotnet/src/webdriver/Internal/Logging/LogContextManager.cs
  dotnet/src/webdriver/Internal/Logging/LogEvent.cs
  dotnet/src/webdriver/Internal/Logging/LogEventLevel.cs
  dotnet/src/webdriver/Internal/Logging/LogHandlerList.cs
  dotnet/src/webdriver/Internal/Logging/Logger.cs
Labels: Review effort [1-5]: 2

#14843 [rb] Add tests for the cookie named, and updates type
  rb/Gemfile.lock
  rb/lib/selenium/webdriver/common/manager.rb
  rb/sig/lib/selenium/webdriver/common/manager.rbs
  rb/spec/integration/selenium/webdriver/manager_spec.rb
Labels: C-rb, Review effort [1-5]: 2, Bug fix

#14832 [rust] xz uncompressor for Firefox Linux nightlies
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/files.rs
Labels: C-rust, Review effort [1-5]: 2

#14810 [java] Enhance Null Check in Exception Handling
  java/src/org/openqa/selenium/internal/Require.java
Labels: Review effort [1-5]: 1

#14283 [py] Typing package import enhancement
  py/generate.py
  py/selenium/types.py
  py/selenium/webdriver/chrome/service.py
  py/selenium/webdriver/chromium/service.py
  py/selenium/webdriver/common/actions/pointer_input.py
  py/selenium/webdriver/common/bidi/cdp.py
  py/selenium/webdriver/common/bidi/script.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/common/virtual_authenticator.py
  py/selenium/webdriver/edge/service.py
  py/selenium/webdriver/firefox/service.py
  py/selenium/webdriver/ie/service.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/safari/options.py
  py/selenium/webdriver/safari/service.py
  py/selenium/webdriver/support/event_firing_webdriver.py
  py/selenium/webdriver/support/wait.py
  py/selenium/webdriver/webkitgtk/service.py
  py/selenium/webdriver/wpewebkit/options.py
  py/selenium/webdriver/wpewebkit/service.py
Labels: C-py, enhancement, Review effort [1-5]: 2

#14597 [java] SpotBugs exclude `DMI_HARDCODED_ABSOLUTE_FILENAME`
  java/spotbugs-excludes.xml
Labels: Bug fix, Review effort [1-5]: 1

#14857 [java]Replace lambdas with method references
  java/src/org/openqa/selenium/chromium/ChromiumDriver.java
  java/src/org/openqa/selenium/devtools/SeleniumCdpConnection.java
  java/src/org/openqa/selenium/firefox/FirefoxDriver.java
  java/src/org/openqa/selenium/remote/RemoteWebDriver.java
  java/test/org/openqa/selenium/NoSuchShadowRootTest.java
  java/test/org/openqa/selenium/grid/node/relay/RelayOptionsTest.java
  java/test/org/openqa/selenium/grid/server/BaseServerOptionsTest.java
Labels: Review effort [1-5]: 1

#14865 [ci] Update script pinned_browsers for changes in Edge API product fetch
  common/repositories.bzl
  scripts/pinned_browsers.py
Labels: Review effort [1-5]: 2

#14858 [py] moved all getters in `fedcm/account.py` into descriptor object.
  py/selenium/webdriver/common/fedcm/account.py
Labels: Review effort [1-5]: 2

#14848 [dotnet] Address warnings with `ActionSequence.inputDevice`
  dotnet/src/webdriver/Interactions/ActionSequence.cs
  dotnet/src/webdriver/Interactions/Actions.cs
Labels: Review effort [1-5]: 1

#14870 [dotnet] Migrate remaining NUnit assertions to `Assert.That` and `Has.Count`
  dotnet/test/common/BiDi/Browser/BrowserTest.cs
  dotnet/test/common/BiDi/Network/NetworkEventsTest.cs
  dotnet/test/common/BiDi/Script/ScriptCommandsTest.cs
  dotnet/test/common/BiDi/Storage/StorageTest.cs
  dotnet/test/common/ClickScrollingTest.cs
  dotnet/test/common/DriverElementFindingTest.cs
  dotnet/test/common/ElementElementFindingTest.cs
  dotnet/test/common/ExecutingAsyncJavascriptTest.cs
  dotnet/test/common/ExecutingJavascriptTest.cs
  dotnet/test/common/Interactions/ActionBuilderTest.cs
  dotnet/test/common/Internal/Logging/FileLogHandlerTest.cs
  dotnet/test/common/NavigationTest.cs
  dotnet/test/common/PositionAndSizeTest.cs
  dotnet/test/firefox/FirefoxDriverTest.cs
  dotnet/test/remote/RemoteWebDriverSpecificTests.cs
  dotnet/test/support/Events/EventFiringWebDriverTest.cs
  dotnet/test/support/UI/LoadableComponentTests.cs
  dotnet/test/support/UI/SlowLoadableComponentTest.cs
  dotnet/test/support/UI/WebDriverWaitTest.cs
Labels: Review effort [1-5]: 2

#14861 [dotnet] Add nullability annotations to `Proxy`
  dotnet/src/webdriver/Proxy.cs
Labels: Review effort [1-5]: 2

#14839 [dotnet] Modernize `Response` type
  dotnet/src/webdriver/Response.cs
Labels: Review effort [1-5]: 2

#14875 [dotnet] Add nullability to Logs API
  dotnet/src/webdriver/ILogs.cs
  dotnet/src/webdriver/LogEntry.cs
  dotnet/src/webdriver/LogLevel.cs
  dotnet/src/webdriver/Logs.cs
Labels: Review effort [1-5]: 2

#14809 [py] add execute_cdp_cmd to Remote
  py/selenium/webdriver/chromium/webdriver.py
  py/selenium/webdriver/remote/webdriver.py
Labels: Review effort [1-5]: 1

#14768 [java] SpotBugs exclude `IS2_INCONSISTENT_SYNC` form the `SeleniumManager`
  java/spotbugs-excludes.xml
Labels: C-java, Review effort [1-5]: 1

#14882 [java] Enable SpotBugs for java_export
  java/private/export.bzl
Labels: Review effort [1-5]: 1

#14874 [dotnet] Add nullability to `CookieJar`
  dotnet/src/webdriver/CookieJar.cs
  dotnet/src/webdriver/ICookieJar.cs
Labels: Review effort [1-5]: 2

#14877 [dotnet] Refactor away private constructor from `Response`
  dotnet/src/webdriver/Response.cs
Labels: Review effort [1-5]: 2

#14669 [dotnet] Add nullability to `Alert`s
  dotnet/src/webdriver/Alert.cs
  dotnet/src/webdriver/Cookie.cs
  dotnet/src/webdriver/IAlert.cs
Labels: C-dotnet, Review effort [1-5]: 3

#14859 [selenium manager]: fix edge artifact deserialisation
  rust/src/edge.rs
Labels: I-defect, C-rust

#14891 [bazel]: Bump `rules_protobuf` to avoid warning about `maven` namespace
  .bazelrc
  MODULE.bazel
  java/maven_install.json
Labels: Review effort [1-5]: 2

#14890 [bazel]: Prepare for bump of `rules_closure`
  javascript/atoms/BUILD.bazel
  javascript/atoms/fragments/BUILD.bazel
  javascript/chrome-driver/BUILD.bazel
  javascript/ie-driver/BUILD.bazel
  javascript/webdriver/BUILD.bazel
  javascript/webdriver/atoms/BUILD.bazel
  javascript/webdriver/atoms/inject/BUILD.bazel
  third_party/js/wgxpath/BUILD.bazel
Labels: Review effort [1-5]: 2

#14895 [bazel] Switch to rules_closure 0.12.0
  WORKSPACE
  javascript/rules_closure_shell.patch
Labels: Review effort [1-5]: 1

#14751 [rb] BiDi Network: add_request_handler, remove_request_handler, clear_request_handlers
  rb/lib/selenium/webdriver/bidi/network.rb
  rb/lib/selenium/webdriver/common/network.rb
  rb/sig/lib/selenium/webdriver/bidi/network.rbs
  rb/sig/lib/selenium/webdriver/common/network.rbs
  rb/spec/integration/selenium/webdriver/bidi/network_spec.rb
  rb/spec/integration/selenium/webdriver/fedcm_spec.rb
  rb/spec/integration/selenium/webdriver/network_spec.rb
Labels: C-rb, Review effort [1-5]: 2

#14898 [rust] Use file lock to protect concurrent accesses to cache
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/files.rs
  rust/src/lib.rs
  rust/src/lock.rs
Labels: C-rust, Review effort [1-5]: 3

#14902 [java]: better span name for `TracedCommandExecutor`
  java/src/org/openqa/selenium/remote/TracedCommandExecutor.java
  java/test/org/openqa/selenium/remote/TracedCommandExecutorTest.java
Labels: Review effort [1-5]: 1

#14709 Updated renovate.json to add correct commitMessagePrefix
  .github/workflows/bazel.yml
  .github/workflows/ci-rbe.yml
  .github/workflows/ci-renovate-rbe.yml
  renovate.json
Labels: Review effort [1-5]: 2

#14878 [dotnet] Correct assertion of struct type in internal tests
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsTestFixture.cs
Labels: Review effort [1-5]: 1

#14841 [dotnet] Add nullability annotations to `SessionId`
  dotnet/src/webdriver/SessionId.cs
  dotnet/src/webdriver/WebDriver.cs
Labels: Review effort [1-5]: 2

#14905 add `locators.html` file in static web pages
  common/src/web/locators_tests/locators.html
Labels: Review effort [1-5]: 1

#14921 [java] setter for flag JsonInput.readPerformed
  java/src/org/openqa/selenium/json/JsonInput.java
Labels: Review effort [1-5]: 2

#14938 [grid] Distributor listen and handle the NodeRestartedEvent
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
Labels: C-grid, Review effort [1-5]: 2

#14764 [grid] delay the newsessionqueue response
  java/src/org/openqa/selenium/grid/commands/Hub.java
  java/src/org/openqa/selenium/grid/commands/Standalone.java
  java/src/org/openqa/selenium/grid/sessionqueue/config/NewSessionQueueOptions.java
  java/src/org/openqa/selenium/grid/sessionqueue/local/LocalNewSessionQueue.java
  java/test/org/openqa/selenium/grid/distributor/AddingNodesTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorDrainingTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorNodeAvailabilityTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorTestBase.java
  java/test/org/openqa/selenium/grid/distributor/SessionSchedulingTest.java
  java/test/org/openqa/selenium/grid/distributor/local/LocalDistributorTest.java
  java/test/org/openqa/selenium/grid/graphql/GraphqlHandlerTest.java
  java/test/org/openqa/selenium/grid/router/JmxTest.java
  java/test/org/openqa/selenium/grid/router/NewSessionCreationTest.java
  java/test/org/openqa/selenium/grid/router/RouterTest.java
  java/test/org/openqa/selenium/grid/router/SessionCleanUpTest.java
  java/test/org/openqa/selenium/grid/router/SessionQueueGridTest.java
  java/test/org/openqa/selenium/grid/router/SessionQueueGridWithTimeoutTest.java
  java/test/org/openqa/selenium/grid/sessionqueue/local/LocalNewSessionQueueTest.java
Labels: C-grid, Review effort [1-5]: 3

#14914 [grid] Improve SlotMatcher and SlotSelector on request browserVersion
  java/src/org/openqa/selenium/grid/data/DefaultSlotMatcher.java
  java/src/org/openqa/selenium/grid/data/NodeStatus.java
  java/src/org/openqa/selenium/grid/data/SemanticVersionComparator.java
  java/src/org/openqa/selenium/grid/distributor/selector/DefaultSlotSelector.java
  java/test/org/openqa/selenium/grid/data/DefaultSlotMatcherTest.java
  java/test/org/openqa/selenium/grid/distributor/selector/DefaultSlotSelectorTest.java
Labels: C-grid, Review effort [1-5]: 4

#14936 [dotnet] Align webdriver errors with spec
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
  dotnet/src/webdriver/UnknownErrorException.cs
  dotnet/src/webdriver/UnknownMethodException.cs
  dotnet/src/webdriver/UnsupportedOperationException.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/src/webdriver/WebDriverError.cs
  dotnet/src/webdriver/WebDriverResult.cs
Labels: Review effort [1-5]: 2

#14929 [dotnet] Add nullability to `IniFileReader`
  dotnet/src/webdriver/Firefox/Internal/IniFileReader.cs
Labels: Review effort [1-5]: 2

#14778 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort [1-5]: 1

#14889 [java] for loop enhance and using of standard java 11 method writeString for tests
  java/src/org/openqa/selenium/grid/jmx/MBean.java
  java/src/org/openqa/selenium/grid/node/docker/DockerSessionFactory.java
  java/test/org/openqa/selenium/UploadTest.java
  java/test/org/openqa/selenium/edge/EdgeOptionsTest.java
  java/test/org/openqa/selenium/environment/webserver/AppServerTestBase.java
  java/test/org/openqa/selenium/grid/node/NodeTest.java
  java/test/org/openqa/selenium/grid/web/ResourceHandlerTest.java
  java/test/org/openqa/selenium/testing/TestUtilities.java
Labels: Review effort [1-5]: 2

#14793 [java] reuse the classes created by the WebDriverDecorator #14789
  java/src/org/openqa/selenium/support/decorators/WebDriverDecorator.java
  java/test/org/openqa/selenium/support/decorators/DecoratedWebDriverTest.java
Labels: Review effort [1-5]: 3

#14930 Added more detailed docstrings to find_element()
  py/selenium/webdriver/remote/shadowroot.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/webelement.py
Labels: Review effort [1-5]: 1

#14899 [py] Refactored `remote/client_config.py` by moving `properties` into `descriptor` object
  py/selenium/webdriver/remote/client_config.py
Labels: Review effort [1-5]: 2

#14888 [dotnet] Annotate nullability on command repository
  dotnet/src/webdriver/CommandInfoRepository.cs
  dotnet/src/webdriver/Remote/W3CWireProtocolCommandInfoRepository.cs
Labels: Review effort [1-5]: 2

#14956 [dotnet] Revert deprecation of GetAttribute method
  dotnet/src/support/Events/EventFiringWebDriver.cs
  dotnet/src/webdriver/IWebElement.cs
  dotnet/src/webdriver/WebElement.cs
Labels: Review effort [1-5]: 1

#14942 [dotnet] Annotate `DriverServiceCommandExecutor` for nullability
  dotnet/src/webdriver/Remote/DriverServiceCommandExecutor.cs
  dotnet/src/webdriver/Remote/ICommandServer.cs
Labels: Review effort [1-5]: 2

#14862 py: Ensure DRIVER_PATH_ENV_KEY defaults to string
  py/selenium/webdriver/common/service.py
Labels: Review effort [1-5]: 1

#14892 [dotnet] Do not intercept exceptions from `ICommandExecutor.ExecuteAsync`
  dotnet/src/webdriver/WebDriver.cs
Labels: Review effort [1-5]: 1

#14794 [py] remove xfail attr for firefox and safari for cookie tests
  py/test/selenium/webdriver/common/cookie_tests.py
Labels: Review effort [1-5]: 1

#14754 [java] Added a check for intentionally existing loggers
  java/src/org/openqa/selenium/grid/log/LoggingOptions.java
Labels: Review effort [1-5]: 1

#14395 [java] JSpecify annotations for immutable models and enums
  java/src/org/openqa/selenium/Dimension.java
  java/src/org/openqa/selenium/Keys.java
  java/src/org/openqa/selenium/Point.java
  java/src/org/openqa/selenium/Rectangle.java
  java/src/org/openqa/selenium/UsernameAndPassword.java
Labels: enhancement, Review effort [1-5]: 2

#14396 [java] JSpecify annotations for wrappers
  java/src/org/openqa/selenium/WrapsDriver.java
  java/src/org/openqa/selenium/WrapsElement.java
Labels: enhancement, documentation, Review effort [1-5]: 1

#14924 [grid] rework the retry of http requests #14917
  java/src/org/openqa/selenium/remote/http/BUILD.bazel
  java/src/org/openqa/selenium/remote/http/RetryRequest.java
  java/test/org/openqa/selenium/remote/http/RetryRequestTest.java
Labels: C-grid, Review effort [1-5]: 3

#14987 [grid] ensure --drain-after-session-count is respected with a lot of sessions in the queue
  java/src/org/openqa/selenium/grid/node/local/LocalNode.java
Labels: Review effort [1-5]: 3
