Repository SeleniumHQ/selenium, pull requests merged in 2024-10, with the labels that each got.

#14183 [java] increasing of properties scope for better appium compatibility
  java/src/org/openqa/selenium/remote/HttpCommandExecutor.java
  java/src/org/openqa/selenium/remote/RemoteWebDriver.java
  java/src/org/openqa/selenium/remote/service/DriverService.java
  java/src/org/openqa/selenium/support/ui/FluentWait.java
Labels: enhancement, Review effort [1-5]: 2

#14502 `py/test/selenium/webdriver/common/network.py`: remove python 2 code
  py/test/selenium/webdriver/common/network.py
Labels: enhancement, Review effort [1-5]: 1

#14286 [py] fixed a bug in `bidi/session.py` by removing mutable object as default value for function argument.
  py/selenium/webdriver/common/bidi/session.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#14411 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: enhancement, Review effort [1-5]: 2

#14556 [dotnet] Fix flaky VerifyRequestPostData test
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
Labels: Review effort [1-5]: 2, Bug fix

#14557 [dotnet] Don't write trace log message when waiting until driver service is initialized
  dotnet/src/webdriver/DriverService.cs
Labels: enhancement, Review effort [1-5]: 2

#14549 [dotnet] Support GetLog command by Remote Web Driver
  dotnet/src/webdriver/Logs.cs
  dotnet/src/webdriver/Remote/W3CWireProtocolCommandInfoRepository.cs
Labels: enhancement, Review effort [1-5]: 2

#14507 [js] Close BiDi websocket connection
  javascript/node/selenium-webdriver/lib/webdriver.js
Labels: enhancement, Review effort [1-5]: 3

#14558 [dotnet] Add more internal logs around CDP DevTools communication
  dotnet/src/webdriver/DevTools/DevToolsSession.cs
Labels: enhancement, Review effort [1-5]: 2, other

#14562 [py] remove un-needed print
  py/selenium/webdriver/common/bidi/script.py
Labels: Bug fix, Review effort [1-5]: 1

#14528 [py] Allow driver path to be set using ENV variables
  py/selenium/webdriver/chromium/service.py
  py/selenium/webdriver/chromium/webdriver.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/edge/service.py
  py/selenium/webdriver/firefox/service.py
  py/selenium/webdriver/firefox/webdriver.py
  py/selenium/webdriver/ie/service.py
  py/selenium/webdriver/ie/webdriver.py
  py/selenium/webdriver/safari/service.py
  py/selenium/webdriver/safari/webdriver.py
  py/test/selenium/webdriver/chrome/chrome_service_tests.py
  py/test/selenium/webdriver/firefox/firefox_service_tests.py
Labels: enhancement, Review effort [1-5]: 3, tests

#14504 [py] remove python 2.x support from py test file
  py/test/selenium/webdriver/common/position_and_size_tests.py
Labels: Bug fix, Review effort [1-5]: 1

#14511 selenium manager: check invalid browser version
  rust/src/lib.rs
Labels: Review effort [1-5]: 2, Bug fix, tests

#14539 [java]: fix decoding of line endings
  java/src/org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.java
Labels: Review effort [1-5]: 2, Bug fix

#14481 [dotnet] Json serializer gen context for SM output
  MODULE.bazel
  dotnet/src/webdriver/BUILD.bazel
  dotnet/src/webdriver/SeleniumManager.cs
Labels: enhancement, Review effort [1-5]: 3

#14506 [java] Add PAC proxy url to arguments for Selenium Manager
  java/src/org/openqa/selenium/remote/service/DriverFinder.java
Labels: Review effort [1-5]: 2, Bug fix

#14572 [js] use only pnpm and remove npm refs
  MODULE.bazel
  javascript/node/selenium-webdriver/package.json
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: dependencies, enhancement, Review effort [1-5]: 2

#14584 [grid]: Capability se:vncEnabled value based on list of vnc-env-var
  java/src/org/openqa/selenium/grid/node/config/NodeFlags.java
  java/src/org/openqa/selenium/grid/node/config/NodeOptions.java
  java/test/org/openqa/selenium/grid/node/config/NodeOptionsTest.java
Labels: C-grid, enhancement, Review effort [1-5]: 2, tests

#14579 [JS] move from npm to pnpm
  MODULE.bazel
  Rakefile
  javascript/node/selenium-webdriver/package.json
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: dependencies, enhancement, Review effort [1-5]: 2

#14582 [grid]: Add node sessionTimeout to Grid status
  java/src/org/openqa/selenium/grid/data/NodeStatus.java
  java/src/org/openqa/selenium/grid/graphql/Grid.java
  java/src/org/openqa/selenium/grid/graphql/Node.java
  java/src/org/openqa/selenium/grid/graphql/selenium-grid-schema.graphqls
  java/src/org/openqa/selenium/grid/router/GridStatusHandler.java
  java/test/org/openqa/selenium/grid/distributor/local/LocalDistributorTest.java
Labels: C-grid, enhancement, Review effort [1-5]: 2, Bug fix

#14585 [java] Fix `v*Network.java` conditions
  java/src/org/openqa/selenium/devtools/v127/v127Network.java
  java/src/org/openqa/selenium/devtools/v128/v128Network.java
  java/src/org/openqa/selenium/devtools/v129/v129Network.java
  java/src/org/openqa/selenium/devtools/v85/V85Network.java
Labels: Review effort [1-5]: 2, Bug fix

#14590 [java] SpotBugs exclude `NM_SAME_SIMPLE_NAME_AS_SUPERCLASS`
  java/spotbugs-excludes.xml
Labels: bug_fix, Review effort [1-5]: 1

#14589 [java] Fix SpotBugs findings in `ChromiumDriver` and `PortProber`
  java/src/org/openqa/selenium/chromium/ChromiumDriver.java
  java/src/org/openqa/selenium/net/PortProber.java
Labels: Review effort [1-5]: 2, Bug fix

#14598 [grid] UI Liveview disconnect noVNC websocket when closing dialog
  javascript/grid-ui/src/components/LiveView/LiveView.tsx
  javascript/grid-ui/src/components/RunningSessions/RunningSessions.tsx
Labels: C-grid, Review effort [1-5]: 2, Bug fix

#14599 [grid] UI Sessions view sort Duration in ascending by default
  javascript/grid-ui/src/components/RunningSessions/RunningSessions.tsx
Labels: C-grid, Review effort [1-5]: 2, Bug fix

#14601 [py] Remote connection throws resp status code when data is empty
  py/selenium/webdriver/remote/remote_connection.py
Labels: python, enhancement, Review effort [1-5]: 2, bug_fix

#14596 [java] SpotBugs exclude `NM_CLASS_NAMING_CONVENTION`
  java/spotbugs-excludes.xml
Labels: enhancement, Review effort [1-5]: 1

#14605 [grid] Fix tests for Grid status endpoint and UI
  java/src/org/openqa/selenium/grid/data/NodeStatus.java
  java/src/org/openqa/selenium/grid/router/GridStatusHandler.java
  java/test/org/openqa/selenium/grid/distributor/local/LocalDistributorTest.java
  java/test/org/openqa/selenium/grid/gridui/OverallGridTest.java
Labels: Review effort [1-5]: 2, Bug fix, tests

#14593 [dotnet] Allow setting of PageDimensions and PageMargins in PrintOptions directly
  dotnet/src/webdriver/PrintOptions.cs
  dotnet/test/common/DriverTestFixture.cs
  dotnet/test/common/PrintTest.cs
Labels: C-dotnet, Bug fix, Review effort [1-5]: 1

#14606 [py] allow logging diagnose in safari driver
  py/selenium/webdriver/safari/service.py
Labels: enhancement, Review effort [1-5]: 2

#14497 tox formatting for python files in `format.sh`
  scripts/format.sh
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#14578 [py] Avoid waiting indefinitely on a frozen chromedriver process
  py/selenium/webdriver/remote/remote_connection.py
Labels: python, Review effort [1-5]: 2, Bug fix

#14611 [rb] Add RBS type support for BiDi related classes
  rb/sig/lib/selenium/webdriver/bidi.rbs
  rb/sig/lib/selenium/webdriver/bidi/log_handler.rbs
  rb/sig/lib/selenium/webdriver/bidi/struct.rbs
  rb/sig/lib/selenium/webdriver/remote/bidi_bridge.rbs
  rb/sig/lib/selenium/webdriver/remote/bridge.rbs
  rb/sig/lib/selenium/webdriver/remote/bridge/locator_converter.rbs
Labels: enhancement, documentation, Review effort [1-5]: 2

#14625 [grid] UI Overview add more sort options
  javascript/grid-ui/src/screens/Overview/Overview.tsx
Labels: Review effort [1-5]: 3

#14587 [🚀 Feature] [py]: Better compatibility with Appium-python
  py/selenium/webdriver/common/by.py
  py/selenium/webdriver/remote/locator_converter.py
  py/selenium/webdriver/remote/remote_connection.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/webelement.py
  py/test/selenium/webdriver/common/driver_element_finding_tests.py
  py/test/selenium/webdriver/remote/custom_element_tests.py
  py/test/selenium/webdriver/remote/remote_custom_locator_tests.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: enhancement, tests, Review effort [1-5]: 4

#14236 Update Ruby BiDi script structs to match spec (as of 2024-07-08)
  rb/lib/selenium/webdriver/bidi/log_handler.rb
  rb/spec/integration/selenium/webdriver/bidi/script_spec.rb
Labels: enhancement, Review effort [1-5]: 3, tests

#14634 [ci] [dotnet] Enable long path in bazel
  .github/workflows/ci-dotnet.yml
Labels: Review effort [1-5]: 1, configuration changes

#14628 [grid] Improvement for Node handling
  java/src/org/openqa/selenium/grid/node/ForwardWebDriverCommand.java
  java/src/org/openqa/selenium/grid/node/Node.java
  java/src/org/openqa/selenium/grid/node/local/LocalNode.java
  java/test/org/openqa/selenium/grid/node/ForwardWebDriverCommandTest.java
  java/test/org/openqa/selenium/grid/node/NodeTest.java
  java/test/org/openqa/selenium/grid/router/StressTest.java
Labels: C-grid, enhancement, Review effort [1-5]: 3

#14639 [dotnet] Lazy-load Selenium manager binary location
  dotnet/src/webdriver/SeleniumManager.cs
Labels: C-dotnet, enhancement, Review effort [1-5]: 2

#13286 [py] implement configurable configuration class for the http client
  py/selenium/webdriver/chrome/remote_connection.py
  py/selenium/webdriver/chromium/remote_connection.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/edge/remote_connection.py
  py/selenium/webdriver/firefox/remote_connection.py
  py/selenium/webdriver/remote/client_config.py
  py/selenium/webdriver/remote/remote_connection.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/safari/remote_connection.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py

#14621 [rb] Add missing RBS methods
  rb/sig/lib/selenium/webdriver/bidi.rbs
  rb/sig/lib/selenium/webdriver/bidi/log_handler.rbs
  rb/sig/lib/selenium/webdriver/common/driver_finder.rbs
  rb/sig/lib/selenium/webdriver/common/search_context.rbs
  rb/sig/lib/selenium/webdriver/common/service.rbs
  rb/sig/lib/selenium/webdriver/common/websocket_connection.rbs
  rb/sig/lib/selenium/webdriver/fedcm/dialog.rbs
  rb/sig/lib/selenium/webdriver/firefox/options.rbs
  rb/sig/lib/selenium/webdriver/remote/http/common.rbs
  rb/sig/lib/selenium/webdriver/support/guards/guard.rbs
  rb/sig/selenium/web_driver/script.rbs
Labels: enhancement, Review effort [1-5]: 3

#14574 [dotnet] Make classic WebDriver commands/responses AOT compatible
  dotnet/src/webdriver/Command.cs
  dotnet/src/webdriver/Internal/ResponseValueJsonConverter.cs
  dotnet/src/webdriver/Response.cs
Labels: enhancement, Review effort [1-5]: 2

#14253 [py] moved mypy settings from `mypy.ini` to `pyproject.toml`
  py/mypy.ini
  py/pyproject.toml
Labels: C-py, enhancement, Review effort [1-5]: 2, configuration changes

#14667 [dotnet] Treat SM's logs always as Trace to avoid SM writing at Info level
  dotnet/src/webdriver/SeleniumManager.cs
Labels: Review effort [1-5]: 2

#14626 [py]: set consistent polling across java and python for `WebDriverWait` methods
  py/selenium/webdriver/support/wait.py
Labels: C-py, Review effort [1-5]: 2, Bug fix

#14410 [grid] limit the number of websocket connections per session
  java/src/org/openqa/selenium/grid/node/Node.java
  java/src/org/openqa/selenium/grid/node/ProxyNodeWebsockets.java
  java/src/org/openqa/selenium/grid/node/TryAcquireConnection.java
  java/src/org/openqa/selenium/grid/node/config/NodeFlags.java
  java/src/org/openqa/selenium/grid/node/config/NodeOptions.java
  java/src/org/openqa/selenium/grid/node/k8s/OneShotNode.java
  java/src/org/openqa/selenium/grid/node/local/LocalNode.java
  java/src/org/openqa/selenium/grid/node/local/LocalNodeFactory.java
  java/src/org/openqa/selenium/grid/node/local/SessionSlot.java
  java/src/org/openqa/selenium/grid/node/remote/RemoteNode.java
  java/test/org/openqa/selenium/grid/distributor/AddingNodesTest.java
Labels: C-grid, enhancement, Review effort [1-5]: 3, tests

#14671 [py] moved `isort`, `black` and `docformatter` settings from `tox.ini` file to `pyproject.toml`
  py/pyproject.toml
  py/setup.cfg
  py/tox.ini
Labels: C-py, Review effort [1-5]: 2

#14668 [py] Added more internal logging for CDP
  py/selenium/webdriver/common/bidi/cdp.py
Labels: C-py, Review effort [1-5]: 2

#14409 [grid] enable the httpclient to perform async requests #14403
  java/src/org/openqa/selenium/remote/http/HttpClient.java
  java/src/org/openqa/selenium/remote/http/jdk/JdkHttpClient.java
  java/test/org/openqa/selenium/remote/internal/HttpClientTestBase.java
Labels: C-grid, enhancement, Review effort [1-5]: 3, tests

#14679 [ci][rb] Fix remote tests
  rb/spec/integration/selenium/webdriver/remote/driver_spec.rb
Labels: C-build, Review effort [1-5]: 2

#14665 [build] Prepare for release of Selenium 4.26.0
  .github/release.yml
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v130/BUILD.bazel
  common/devtools/chromium/v130/browser_protocol.pdl
  common/devtools/chromium/v130/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v130/V130Domains.cs
  dotnet/src/webdriver/DevTools/v130/V130JavaScript.cs
  dotnet/src/webdriver/DevTools/v130/V130Log.cs
  dotnet/src/webdriver/DevTools/v130/V130Network.cs
  dotnet/src/webdriver/DevTools/v130/V130Target.cs
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v130/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v130/v130CdpInfo.java
  java/src/org/openqa/selenium/devtools/v130/v130Domains.java
  java/src/org/openqa/selenium/devtools/v130/v130Events.java
  java/src/org/openqa/selenium/devtools/v130/v130Javascript.java
  java/src/org/openqa/selenium/devtools/v130/v130Log.java
  java/src/org/openqa/selenium/devtools/v130/v130Network.java
  java/src/org/openqa/selenium/devtools/v130/v130Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/setup.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
  rust/CHANGELOG.md
  scripts/github-actions/release_header.md
Labels: C-build, Review effort [1-5]: 3

#14683 [ci] Fix pinned browsers fetch different msedgedriver version per OS
  common/repositories.bzl
  scripts/pinned_browsers.py
Labels: Review effort [1-5]: 2

#14692 [py] Remote connection use timeout from ClientConfig
  py/selenium/webdriver/chromium/remote_connection.py
  py/selenium/webdriver/firefox/remote_connection.py
  py/selenium/webdriver/ie/webdriver.py
  py/selenium/webdriver/remote/remote_connection.py
  py/selenium/webdriver/safari/remote_connection.py
  py/selenium/webdriver/safari/webdriver.py
Labels: C-py, Review effort [1-5]: 2

#14696 [py] Add backward compatibility for AppiumConnection
  py/selenium/webdriver/remote/remote_connection.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: Review effort [1-5]: 2

#14684 [dotnet] [bidi] Reveal browsing context module in bidi instance
  dotnet/src/webdriver/BiDi/BiDi.cs
Labels: Review effort [1-5]: 1

#14697 [dotnet] Fix adding cookies when ReturnedCookie class is used
  dotnet/src/webdriver/Command.cs
Labels: Review effort [1-5]: 1

#14685 [rb] Update minimum Ruby to 3.1
  .github/workflows/ci-rbe.yml
  .github/workflows/ci-ruby.yml
  MODULE.bazel
  rb/.rubocop.yml
  rb/.ruby-version
  rb/README.md
  rb/lib/selenium/server.rb
  rb/lib/selenium/webdriver/bidi.rb
  rb/lib/selenium/webdriver/bidi/log_inspector.rb
  rb/lib/selenium/webdriver/common/driver_extensions/has_network_interception.rb
  rb/lib/selenium/webdriver/common/logger.rb
  rb/lib/selenium/webdriver/common/script.rb
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/lib/selenium/webdriver/support/guards.rb
  rb/selenium-devtools.gemspec
  rb/selenium-webdriver.gemspec
Labels: Review effort [1-5]: 3

#14676 [dotnet] Added Deprecation to WebElement.GetAttribute() per #13334
  dotnet/src/webdriver/IWebElement.cs
Labels: Review effort [1-5]: 1
