Repository SeleniumHQ/selenium, pull requests merged in 2025-04, with the labels that each got.

#15505 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort 1/5

#15549 [dotnet] Simplify `PopupWindowFinder.Invoke`
  dotnet/src/support/UI/PopupWindowFinder.cs
Labels: Review effort 1/5

#15548 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15448 [grid] Expose register status via Node status response
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/src/org/openqa/selenium/grid/distributor/selector/DefaultSlotSelector.java
  java/src/org/openqa/selenium/grid/node/Node.java
  java/src/org/openqa/selenium/grid/node/StatusHandler.java
  java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java
  java/src/org/openqa/selenium/grid/node/k8s/OneShotNode.java
  java/src/org/openqa/selenium/grid/node/local/LocalNode.java
  java/src/org/openqa/selenium/grid/node/remote/RemoteNode.java
  java/test/org/openqa/selenium/grid/router/StressTest.java
Labels: B-grid, Review effort 2/5

#15550 [py] Fix driver class name in test fixtures
  py/conftest.py
Labels: Review effort 1/5

#15542 [build] update templates and auto-label issues
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature_proposal.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue-labeler-config.yml
  .github/workflows/issue-labeler.yml
  Rakefile
Labels: Review effort 3/5

#15544 [java] enable safari for CookieImplementationTest
  java/test/org/openqa/selenium/CookieImplementationTest.java
Labels: Review effort 2/5

#15545 [dotnet] [bidi] Make ContinueWithAuthCommand closer to spec (breaking change)
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Modules/Network/ContinueWithAuthCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/NetworkModule.cs
  dotnet/src/webdriver/BiDi/Modules/Network/Request.cs
  dotnet/test/common/BiDi/Network/NetworkTest.cs
Labels: Review effort 2/5

#15555 [dotnet] [bidi] Avoid intermediate JsonDocument allocation to determine unordered discriminator
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/EvaluateResultConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/LogEntryConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/MessageConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/RealmInfoConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/RemoteValueConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Internal/JsonExtensions.cs
Labels: Review effort 2/5

#15483 [build] allow tests tagged exclusive-if-local to run on rbe
  .bazelrc.remote
Labels: C-rb, B-build, Review effort 1/5

#15569 [build] Prepare for release of Selenium 4.31.0
  .github/ISSUE_TEMPLATE/bug-report.yml
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v135/BUILD.bazel
  common/devtools/chromium/v135/browser_protocol.pdl
  common/devtools/chromium/v135/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v135/V135Domains.cs
  dotnet/src/webdriver/DevTools/v135/V135JavaScript.cs
  dotnet/src/webdriver/DevTools/v135/V135Log.cs
  dotnet/src/webdriver/DevTools/v135/V135Network.cs
  dotnet/src/webdriver/DevTools/v135/V135Target.cs
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v135/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v135/v135CdpInfo.java
  java/src/org/openqa/selenium/devtools/v135/v135Domains.java
  java/src/org/openqa/selenium/devtools/v135/v135Events.java
  java/src/org/openqa/selenium/devtools/v135/v135Javascript.java
  java/src/org/openqa/selenium/devtools/v135/v135Log.java
  java/src/org/openqa/selenium/devtools/v135/v135Network.java
  java/src/org/openqa/selenium/devtools/v135/v135Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/test/org/openqa/selenium/bidi/input/DefaultKeyboardTest.java
  java/version.bzl
  javascript/selenium-webdriver/BUILD.bazel
  javascript/selenium-webdriver/CHANGES.md
  javascript/selenium-webdriver/package.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/pyproject.toml
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
  rust/BUILD.bazel
  rust/CHANGELOG.md
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
Labels: C-py, C-rb, C-dotnet, C-java, C-nodejs, B-build, B-devtools, Review effort 3/5, C-build

#15567 [py] Fix test args for --headless and --bidi
  py/BUILD.bazel
  py/conftest.py
Labels: C-py, B-build, Review effort 2/5

#15470 [py] Only skip WebKit tests on Windows
  py/conftest.py
Labels: Review effort 1/5

#15579 [py] Fix broken test for chromedriver logging
  py/test/selenium/webdriver/chrome/chrome_service_tests.py
Labels: C-py, Review effort 1/5

#15580 [py] Fix test for w3c touch pointer properties
  py/test/selenium/webdriver/common/w3c_interaction_tests.py
Labels: C-py, Review effort 2/5

#15583 [py] Fix FedCM tests leaking state
  py/test/selenium/webdriver/common/fedcm_tests.py
Labels: C-py, Review effort 1/5

#15390 [dotnet] [bidi] Address BiDi's JSON converter AOT warnings
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Enumerable/GetClientWindowsResultConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Enumerable/GetCookiesResultConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Enumerable/GetRealmsResultConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Enumerable/GetUserContextsResultConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Enumerable/InputSourceActionsConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Enumerable/LocateNodesResultConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/InputOriginConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/EvaluateResultConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/LogEntryConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/RealmInfoConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/RemoteValueConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Internal/JsonExtensions.cs
Labels: Review effort 2/5

#15574 [grid] Ignored options when they are prefixed, safari specif as well
  java/src/org/openqa/selenium/grid/data/DefaultSlotMatcher.java
  java/test/org/openqa/selenium/grid/data/DefaultSlotMatcherTest.java
Labels: B-grid, C-java, Review effort 2/5

#15597 [py] Remove broken logo from Sphinx generated API docs
  py/docs/selenium_logo_small.png
  py/docs/source/conf.py
Labels: C-py, Review effort 1/5

#15602 [py] Fix PyTest configuration for WPEWebKit
  py/conftest.py
Labels: C-py, Review effort 1/5

#15605 [py] Fix failing test for Edge logging
  py/test/selenium/webdriver/edge/edge_service_tests.py
Labels: C-py, Review effort 1/5

#14592 [py] BiDi Network implementation of Intercepts and Auth in Python
  py/selenium/webdriver/common/bidi/network.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/websocket_connection.py
  py/test/selenium/webdriver/common/bidi_network_tests.py
Labels: C-py, B-devtools, P-enhancement, Review effort 3/5

#15601 [py] Use XWayland for internal Python Firefox tests
  py/conftest.py
  py/test/selenium/webdriver/firefox/firefox_sizing_tests.py
Labels: C-py, Review effort 1/5

#15607 [py] Use mock.patch for environment variables in tests
  py/test/selenium/webdriver/chrome/chrome_service_tests.py
  py/test/selenium/webdriver/chrome/proxy_tests.py
  py/test/selenium/webdriver/edge/edge_service_tests.py
  py/test/selenium/webdriver/firefox/firefox_service_tests.py
  py/test/selenium/webdriver/safari/safari_service_tests.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py, Review effort 2/5

#15608 [ruby] fix lint for print_options.rb
  rb/lib/selenium/webdriver/common/print_options.rb
Labels: C-rb, Review effort 1/5

#15135 [py] Fix select being able to select options hidden by css rules
  common/src/web/formPage.html
  py/selenium/webdriver/support/select.py
  py/test/selenium/webdriver/common/select_class_tests.py
Labels: C-py, Review effort [1-5]: 2

#15616 [py][bidi]: Implement BiDi browser module
  py/selenium/webdriver/common/bidi/browser.py
  py/selenium/webdriver/common/bidi/common.py
  py/selenium/webdriver/common/bidi/network.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_browser_tests.py
Labels: C-py, B-devtools, Review effort 3/5

#15532 [dotnet] [bidi] Add strongly-typed `LocalValue.ConvertFrom` overloads
  dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs
  dotnet/src/webdriver/BiDi/Modules/Script/RegExpValue.cs
  dotnet/test/common/BiDi/Script/LocalValueConversionTests.cs
Labels: Review effort 2/5

#15624 [py] Add missing modules to Python API docs
  py/docs/source/api.rst
Labels: Review effort 2/5

#15521 [dotnet] [bidi] Do not throw when CallFunction or Evaluate return exceptional result (breaking change)
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextScriptModule.cs
  dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs
  dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs
  dotnet/src/webdriver/BiDi/Modules/Script/ScriptModule.cs
  dotnet/src/webdriver/BiDi/Modules/Script/StackTrace.cs
  dotnet/test/common/BiDi/Script/CallFunctionLocalValueTest.cs
  dotnet/test/common/BiDi/Script/CallFunctionParameterTest.cs
  dotnet/test/common/BiDi/Script/CallFunctionRemoteValueTest.cs
  dotnet/test/common/BiDi/Script/EvaluateParametersTest.cs
  dotnet/test/common/BiDi/Script/ScriptCommandsTest.cs
Labels: Review effort 3/5

#15625 [py] Skip bidi tests on browsers that don't support bidi
  py/conftest.py
  py/pyproject.toml
  py/test/selenium/webdriver/common/bidi_browser_tests.py
  py/test/selenium/webdriver/common/bidi_network_tests.py
  py/test/selenium/webdriver/common/bidi_script_tests.py
  py/test/selenium/webdriver/common/bidi_tests.py
Labels: Review effort 2/5

#15559 [py] complete `test_should_throw_an_exception_if_an_alert_has_not_been_dealt_with_and_dismiss_the_alert`
  py/test/selenium/webdriver/common/alerts_tests.py
Labels: C-py, Review effort 1/5

#15637 [py] Remove unused xfail on chrome/edge service tests
  py/test/selenium/webdriver/chrome/chrome_service_tests.py
  py/test/selenium/webdriver/edge/edge_service_tests.py
Labels: C-py, Review effort 1/5

#15638 [py] Adjust xfail markers for window size/position tests
  py/test/selenium/webdriver/common/api_example_tests.py
  py/test/selenium/webdriver/common/window_tests.py
Labels: Review effort 1/5

#15636 [py] Call service.stop() when session can't be started
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/chrome/chrome_service_tests.py
  py/test/selenium/webdriver/edge/edge_service_tests.py
  py/test/selenium/webdriver/firefox/firefox_service_tests.py
Labels: C-py, Review effort 2/5

#15640 [dotnet] [bidi] Reuse memory when receiving websocket messages
  dotnet/src/webdriver/BiDi/Communication/Transport/WebSocketTransport.cs
Labels: C-dotnet, Review effort 2/5

#15641 [py] Remove logging API for non-Chromium browsers
  py/selenium/webdriver/chromium/webdriver.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/api_example_tests.py
Labels: C-py, Review effort 2/5

#15619 [py] Raise TypeError when creating webdriver.Remote() without options
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/remote/remote_tests.py
Labels: C-py, Review effort 1/5

#15642 [py] Upgrade dependencies for mypy tox environment
  py/tox.ini
Labels: Review effort 1/5

#15648 [py] Fix Remote Firefox tests on Linux/Wayland
  py/conftest.py
  py/test/selenium/webdriver/common/api_example_tests.py
  py/test/selenium/webdriver/common/window_tests.py
Labels: C-py, Review effort 2/5

#15649 [dotnet] Enhance Selenium Manager platform detection
  dotnet/src/webdriver/SeleniumManager.cs
Labels: C-dotnet, Review effort 2/5

#15650 [py] Fix flaky WebDriverWait tests
  py/test/selenium/webdriver/common/webdriverwait_tests.py
Labels: C-py, Review effort 2/5

#15647 [py] Change links in package config
  py/pyproject.toml
Labels: C-py, Review effort 1/5

#15558 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15560 [java][bidi]: add browsingContext event `onNavigationCommitted`
  java/src/org/openqa/selenium/bidi/module/BrowsingContextInspector.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextInspectorTest.java
Labels: C-java, B-devtools, Review effort 2/5

#15412 [java][BiDi]: enable Edge tests for RemoteWebDriverBiDiTest
  java/test/org/openqa/selenium/grid/router/BUILD.bazel
  java/test/org/openqa/selenium/grid/router/RemoteWebDriverBiDiTest.java
Labels: Review effort 2/5

#15654 [java][bidi] Add network module chrome tests
  java/test/org/openqa/selenium/bidi/network/BUILD.bazel
  java/test/org/openqa/selenium/bidi/network/NetworkCommandsTest.java
Labels: C-java, B-build, B-devtools, Review effort 2/5

#15224 [java] Set remote active protocol to BiDi for Firefox
  java/src/org/openqa/selenium/firefox/FirefoxOptions.java
Labels: Review effort 1/5

#15615 [py][bidi]: add bidi command `session.status` and encapsulate in Session class
  py/selenium/webdriver/common/bidi/script.py
  py/selenium/webdriver/common/bidi/session.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_session_tests.py
Labels: C-py, B-devtools, Review effort 2/5

#15655 [java] Add header while creating websocket
  java/src/org/openqa/selenium/remote/http/jdk/JdkHttpClient.java
Labels: C-java, Review effort 2/5

#15661 [java][BiDi] enable Edge BiDi tests for network module
  java/test/org/openqa/selenium/bidi/network/AddInterceptParametersTest.java
  java/test/org/openqa/selenium/bidi/network/BUILD.bazel
  java/test/org/openqa/selenium/bidi/network/NetworkCommandsTest.java
  java/test/org/openqa/selenium/bidi/network/NetworkEventsTest.java
Labels: C-java, B-build, B-devtools, Review effort 1/5

#15657 [py] Re-enable remote tests in bazel and fix broken tests
  py/BUILD.bazel
  py/conftest.py
  py/test/selenium/webdriver/chrome/conftest.py
  py/test/selenium/webdriver/common/conftest.py
  py/test/selenium/webdriver/edge/conftest.py
  py/test/selenium/webdriver/firefox/firefox_sizing_tests.py
  py/test/selenium/webdriver/remote/remote_connection_tests.py
  py/test/selenium/webdriver/remote/remote_custom_element_tests.py
  py/test/selenium/webdriver/remote/remote_custom_locator_tests.py
  py/test/selenium/webdriver/remote/remote_downloads_tests.py
  py/test/selenium/webdriver/remote/remote_firefox_profile_tests.py
  py/test/selenium/webdriver/remote/remote_hub_connection.py
  py/test/selenium/webdriver/support/conftest.py
Labels: C-py, B-build, Review effort 3/5

#15631 [py][bidi]: Implement BiDi `browsing_context` module
  py/selenium/webdriver/common/bidi/browsing_context.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_browsing_context_tests.py
Labels: C-py, B-devtools, Review effort 4/5

#15668 [py][BiDi] separate log module from script module and add more tests
  py/selenium/webdriver/common/bidi/log.py
  py/selenium/webdriver/common/bidi/script.py
  py/test/selenium/webdriver/common/bidi_script_tests.py
Labels: C-py, B-devtools, Review effort 2/5

#15663 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15676 [rb] handle issue with selenium manager exit status being nil
  rb/lib/selenium/webdriver/common/selenium_manager.rb
  rb/spec/unit/selenium/webdriver/common/selenium_manager_spec.rb
Labels: C-rb, Review effort 2/5

#15458 [rb] Add websocket-port parameter to firefox service
  rb/lib/selenium/webdriver/firefox/service.rb
  rb/spec/integration/selenium/webdriver/firefox/service_spec.rb
  rb/spec/unit/selenium/webdriver/firefox/service_spec.rb
Labels: C-rb, Review effort 2/5

#15674 [py] Add client_config property and update deprecation messages
  py/selenium/webdriver/remote/remote_connection.py
  py/test/selenium/webdriver/common/timeout_tests.py
  py/test/selenium/webdriver/common/webdriverwait_tests.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py, Review effort 2/5

#15673 [py] Remove support for GLOBAL_DEFAULT_TIMEOUT environment variable
  py/conftest.py
  py/selenium/webdriver/remote/client_config.py
  py/selenium/webdriver/remote/remote_connection.py
  py/test/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py, Review effort 2/5

#15666 [py] Server class to manage (download/run) grid server
  py/conftest.py
  py/docs/source/api.rst
  py/selenium/webdriver/remote/server.py
  py/test/selenium/webdriver/remote/remote_server_tests.py
  py/test/unit/selenium/webdriver/remote/remote_server_tests.py
Labels: C-py, Review effort 2/5
