Repository SeleniumHQ/selenium, pull requests merged in 2025-01, with the labels that each got.

#14997 [py] add doc for driver_path_env_key
  py/selenium/webdriver/chromium/service.py
  py/selenium/webdriver/edge/service.py
  py/selenium/webdriver/firefox/service.py
  py/selenium/webdriver/safari/service.py
Labels: Review effort [1-5]: 1

#14986 [grid] retry if no node does support the Capabilities
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java
  java/test/org/openqa/selenium/grid/distributor/BUILD.bazel
  java/test/org/openqa/selenium/grid/distributor/DrainTest.java
Labels: Review effort [1-5]: 1

#14995 [py] remove xfail_remote for cookie test
  py/test/selenium/webdriver/common/cookie_tests.py
Labels: Review effort [1-5]: 1

#15005 [js][grid] Fix dependency novnc v1.5.0
  javascript/grid-ui/BUILD.bazel
Labels: Review effort [1-5]: 1

#14998 [dotnet] Move `Response` constructors towards immutability
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
  dotnet/src/webdriver/Response.cs
Labels: Review effort [1-5]: 3

#15027 Added rangeStrategy to renovate file
  renovate.json
Labels: Review effort [1-5]: 1

#15046 [py] Fix WebKitGTK driver name check
  py/conftest.py
  py/selenium/webdriver/webkitgtk/service.py
Labels: C-py, Review effort [1-5]: 2

#15048 [java] rawtypes javac warning fix for AbstractDriverOptions
  java/src/org/openqa/selenium/remote/AbstractDriverOptions.java
Labels: Review effort [1-5]: 1

#15051 [dotnet] Fix current version of `IgnoreTargetAttribute` in test suite
  dotnet/test/common/CustomTestAttributes/IgnoreTargetAttribute.cs
Labels: Review effort [1-5]: 2

#14957 [dotnet] Utilize dedicated WebDriver Spec endpoint to get named cookie
  dotnet/src/webdriver/CookieJar.cs
  dotnet/src/webdriver/ICookieJar.cs
  dotnet/src/webdriver/NoSuchCookieException.cs
  dotnet/src/webdriver/Remote/W3CWireProtocolCommandInfoRepository.cs
  dotnet/src/webdriver/WebDriver.cs
Labels: Review effort [1-5]: 2

#14931 [java]: allow setting custom timeout for DevTools
  java/src/org/openqa/selenium/devtools/DevTools.java
Labels: Review effort [1-5]: 2

#14972 [dotnet] Tolerate invalid UTF-16 strings in DevTools JSON response
  dotnet/src/webdriver/DevTools/Json/DevToolsJsonOptions.cs
  dotnet/src/webdriver/DevTools/Json/StringConverter.cs
  dotnet/src/webdriver/cdp/README.md
  third_party/dotnet/devtools/src/generator/Templates/domain.hbs
Labels: Review effort [1-5]: 2

#15057 [dotnet] Fix logging issue when log context level conflicts with logger already captured level
  dotnet/src/webdriver/Internal/Logging/LogContext.cs
  dotnet/test/common/Internal/Logging/LogTest.cs
Labels: Review effort [1-5]: 3

#15049 [dotnet] Apply formatting on internal CDP generator
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationDefinitionTemplateSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationTemplateSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGeneratorBase.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGeneratorContext.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CommandGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CommandInfo.cs
  third_party/dotnet/devtools/src/generator/CodeGen/DomainGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/EventGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/EventInfo.cs
  third_party/dotnet/devtools/src/generator/CodeGen/IServiceProviderExtensions.cs
  third_party/dotnet/devtools/src/generator/CodeGen/ProtocolGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/TemplatesManager.cs
  third_party/dotnet/devtools/src/generator/CodeGen/TypeGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/TypeInfo.cs
  third_party/dotnet/devtools/src/generator/CodeGen/Utility.cs
  third_party/dotnet/devtools/src/generator/Converters/BooleanJsonConverter.cs
  third_party/dotnet/devtools/src/generator/Program.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/CommandDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/DomainDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/EventDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolDefinitionItem.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolVersionDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/TypeDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/Version.cs
Labels: Review effort [1-5]: 2

#15047 [grid] Dynamic Grid is able to trigger video record in browser node
  java/src/org/openqa/selenium/grid/node/docker/DockerAssetsPath.java
  java/src/org/openqa/selenium/grid/node/docker/DockerOptions.java
  java/src/org/openqa/selenium/grid/node/docker/DockerSessionFactory.java
Labels: Review effort [1-5]: 2

#15062 [java] Nullness annotations for Cookie and Platform
  java/src/org/openqa/selenium/Cookie.java
  java/src/org/openqa/selenium/Platform.java
Labels: Review effort [1-5]: 2

#15061 [dotnet] Move devtools generator to `System.Text.Json`, update to .NET 8
  third_party/dotnet/devtools/src/generator/BUILD.bazel
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationDefinitionTemplateSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationTemplateSettings.cs
  third_party/dotnet/devtools/src/generator/Converters/BooleanJsonConverter.cs
  third_party/dotnet/devtools/src/generator/DevToolsGenerator.csproj
  third_party/dotnet/devtools/src/generator/Program.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/CommandDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/DomainDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/EventDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolDefinitionItem.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolVersionDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/TypeDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/Version.cs
  third_party/dotnet/devtools/src/generator/Templates/project.hbs
Labels: Review effort [1-5]: 2

#15066 [dotnet] Safari driver supports /status endpoint
  dotnet/src/webdriver/Safari/SafariDriverService.cs
Labels: Review effort [1-5]: 2

#15074 [dotnet] Guard for cookie deletion when name is empty
  dotnet/src/webdriver/CookieJar.cs
  dotnet/src/webdriver/ICookieJar.cs
  dotnet/test/common/CookieImplementationTest.cs
Labels: Review effort [1-5]: 2

#15067 [dotnet] Modernize code style in the devtools source generator
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationDefinitionTemplateSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationTemplateSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGeneratorBase.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGeneratorContext.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CommandGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/DomainGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/EventGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/ICodeGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/IServiceProviderExtensions.cs
  third_party/dotnet/devtools/src/generator/CodeGen/ProtocolGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/TemplatesManager.cs
  third_party/dotnet/devtools/src/generator/CodeGen/TypeGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/Utility.cs
  third_party/dotnet/devtools/src/generator/CommandLineOptions.cs
  third_party/dotnet/devtools/src/generator/Converters/BooleanJsonConverter.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/CommandDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/DomainDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/EventDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/IDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolDefinitionItem.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolVersionDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/TypeDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/Version.cs
Labels: Review effort [1-5]: 2

#15043 [java] Replace anonymous types with lambdas
  java/src/org/openqa/selenium/chromium/AddHasCdp.java
  java/src/org/openqa/selenium/chromium/AddHasLaunchApp.java
  java/src/org/openqa/selenium/chromium/AddHasPermissions.java
  java/src/org/openqa/selenium/safari/AddHasDebugger.java
Labels: C-java, Review effort [1-5]: 2

#15054 [py] Upgraded WebDriverWait Docstrings
  py/selenium/webdriver/support/wait.py
Labels: Review effort [1-5]: 1

#14964 [dotnet] Add nullability to `FirefoxExtension`
  dotnet/src/webdriver/Firefox/FirefoxExtension.cs
  dotnet/src/webdriver/Firefox/FirefoxProfile.cs
Labels: Review effort [1-5]: 2

#15065 [py] Added Docstrings to ActionBuilder
  py/selenium/webdriver/common/actions/action_builder.py
Labels: Review effort [1-5]: 1

#15056 [py] Upgraded WebElement Docstrings
  py/selenium/webdriver/remote/webelement.py
Labels: Review effort [1-5]: 2

#15055 [py] Upgraded WebDriver Docstrings
  py/selenium/webdriver/remote/webdriver.py
Labels: Review effort [1-5]: 2

#15086 [dotnet] Improve dependency update developer experience
  dotnet/update-deps.sh
Labels: Review effort [1-5]: 1

#15059 Allow sending DevTools command with custom timeout.
  java/src/org/openqa/selenium/devtools/DevTools.java
Labels: Review effort [1-5]: 2

#15084 [java] Add nullness for Require
  java/src/org/openqa/selenium/internal/Require.java
Labels: Review effort [1-5]: 2

#15083 [java] Add nullness for net
  java/src/org/openqa/selenium/net/DefaultNetworkInterfaceProvider.java
  java/src/org/openqa/selenium/net/HostIdentifier.java
  java/src/org/openqa/selenium/net/NetworkInterface.java
  java/src/org/openqa/selenium/net/NetworkInterfaceProvider.java
Labels: Review effort [1-5]: 2

#15089 [dotnet] Finish nullability annotations on `Support` package
  dotnet/src/support/BUILD.bazel
  dotnet/src/support/Events/EventFiringWebDriver.cs
  dotnet/src/support/Extensions/WebDriverExtensions.cs
  dotnet/src/support/UI/PopupWindowFinder.cs
  dotnet/src/support/UI/SelectElement.cs
  dotnet/src/support/WebDriver.Support.csproj
Labels: Review effort [1-5]: 4

#15081 [java] Add nullness for exceptions
  java/src/org/openqa/selenium/NoSuchElementException.java
  java/src/org/openqa/selenium/NotFoundException.java
  java/src/org/openqa/selenium/StaleElementReferenceException.java
  java/src/org/openqa/selenium/WebDriverException.java
Labels: Review effort [1-5]: 1

#15095 [java] Add nullness for interactions
  java/src/org/openqa/selenium/interactions/Encodable.java
  java/src/org/openqa/selenium/interactions/InputSource.java
  java/src/org/openqa/selenium/interactions/KeyInput.java
  java/src/org/openqa/selenium/interactions/PointerInput.java
Labels: Review effort [1-5]: 2

#15088 [dotnet] Finalize nullability in internal devtools generator
  third_party/dotnet/devtools/src/generator/BUILD.bazel
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGenerationTemplateSettings.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGeneratorBase.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CodeGeneratorContext.cs
  third_party/dotnet/devtools/src/generator/CodeGen/CommandInfo.cs
  third_party/dotnet/devtools/src/generator/CodeGen/EventInfo.cs
  third_party/dotnet/devtools/src/generator/CodeGen/ICodeGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/ProtocolGenerator.cs
  third_party/dotnet/devtools/src/generator/CodeGen/TemplatesManager.cs
  third_party/dotnet/devtools/src/generator/CodeGen/TypeInfo.cs
  third_party/dotnet/devtools/src/generator/CodeGen/Utility.cs
  third_party/dotnet/devtools/src/generator/CommandLineOptions.cs
  third_party/dotnet/devtools/src/generator/DevToolsGenerator.csproj
  third_party/dotnet/devtools/src/generator/Program.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/CommandDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/DomainDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolDefinitionItem.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/ProtocolVersionDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/TypeDefinition.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/Version.cs
Labels: Review effort [1-5]: 4

#14482 [java][js][py] Straight relative-by locators
  common/src/web/relative_locators.html
  dotnet/test/common/RelativeLocatorTest.cs
  java/src/org/openqa/selenium/support/locators/RelativeLocator.java
  java/test/org/openqa/selenium/support/locators/RelativeLocatorTest.java
  javascript/atoms/locators/relative.js
  javascript/atoms/test/deps.js
  javascript/atoms/test/relative_locator_test.html
  javascript/atoms/test/test_bootstrap.js
  javascript/node/selenium-webdriver/lib/by.js
  javascript/node/selenium-webdriver/test/element_finding_test.js
  py/selenium/webdriver/support/relative_locator.py
  py/test/selenium/webdriver/support/relative_by_tests.py
  rb/spec/integration/selenium/webdriver/driver_spec.rb
Labels: enhancement, Review effort [1-5]: 3, tests

#15094 [java] Add nullness for Proxy and print
  java/src/org/openqa/selenium/Proxy.java
  java/src/org/openqa/selenium/print/PageMargin.java
  java/src/org/openqa/selenium/print/PageSize.java
  java/src/org/openqa/selenium/print/PrintOptions.java
Labels: Review effort [1-5]: 2

#15097 [py] Added Docstrings to RelativeBy Class and Added Missing Deprecation Warning to with_tag_name()
  py/selenium/webdriver/support/relative_locator.py
Labels: Review effort [1-5]: 1

#15100 Update Gemfile.lock and checksums
  MODULE.bazel
  rb/Gemfile.lock
  rb/lib/selenium/webdriver/bidi/struct.rb
  rb/lib/selenium/webdriver/common/logger.rb
Labels: Review effort [1-5]: 2

#14946 Add NumberFormatException when the port isn't correctly formatted for Firefox, Edge and Chrome Drivers
  java/src/org/openqa/selenium/remote/service/DriverService.java
  java/test/org/openqa/selenium/chrome/ChromeDriverFunctionalTest.java
  java/test/org/openqa/selenium/edge/EdgeDriverFunctionalTest.java
  java/test/org/openqa/selenium/firefox/FirefoxDriverTest.java
  java/test/org/openqa/selenium/ie/InternetExplorerDriverTest.java
  java/test/org/openqa/selenium/safari/SafariDriverTest.java
Labels: Review effort [1-5]: 2

#14844 [dotnet] Annotate nullable reference types on `ActionBuilder`
  dotnet/src/webdriver/Interactions/ActionBuilder.cs
Labels: Review effort [1-5]: 2

#14871 [dotnet] Annotate nullability on `HttpCommandExecutor` aside from `Response`
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
Labels: Review effort [1-5]: 2

#15107 [dotnet] Obsolete setters and constructors on `Response` that are not conducive to immutability
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
  dotnet/src/webdriver/Response.cs
Labels: Review effort [1-5]: 2

#15111 [dotnet] Fix generation of public static html documentation
  .github/workflows/update-documentation.yml
  Rakefile
  dotnet/docs/docfx.json
Labels: Review effort [1-5]: 2

#15077 [py] Added Docstrings to ExpectedConditions Class
  py/selenium/webdriver/support/expected_conditions.py
Labels: Review effort [1-5]: 2

#15102 [py] Added Docstrings to By Class
  py/selenium/webdriver/common/by.py
Labels: Review effort [1-5]: 1

#15115 Use tax.xz for Firefox package starting in version 135 in pinned browsers
  scripts/pinned_browsers.py
Labels: Review effort [1-5]: 1

#15116 [java]: Fix the message from NumberFormatException
  java/src/org/openqa/selenium/remote/service/DriverService.java
Labels: Review effort [1-5]: 1

#15105 [java] Add nullness for enums
  java/src/org/openqa/selenium/PageLoadStrategy.java
  java/src/org/openqa/selenium/UnexpectedAlertBehaviour.java
  java/src/org/openqa/selenium/WindowType.java
Labels: Review effort [1-5]: 1

#15108 [java] Add nullness for logging
  java/src/org/openqa/selenium/logging/LogEntries.java
  java/src/org/openqa/selenium/logging/LogEntry.java
  java/src/org/openqa/selenium/logging/LogLevelMapping.java
  java/src/org/openqa/selenium/logging/SessionLogs.java
  java/test/org/openqa/selenium/logging/LoggingTest.java
Labels: Review effort [1-5]: 2

#15098 [build] Prepare for release of Selenium 4.28.0
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v132/BUILD.bazel
  common/devtools/chromium/v132/browser_protocol.pdl
  common/devtools/chromium/v132/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v132/V132Domains.cs
  dotnet/src/webdriver/DevTools/v132/V132JavaScript.cs
  dotnet/src/webdriver/DevTools/v132/V132Log.cs
  dotnet/src/webdriver/DevTools/v132/V132Network.cs
  dotnet/src/webdriver/DevTools/v132/V132Target.cs
  dotnet/test/common/ClickTest.cs
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v132/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v132/v132CdpInfo.java
  java/src/org/openqa/selenium/devtools/v132/v132Domains.java
  java/src/org/openqa/selenium/devtools/v132/v132Events.java
  java/src/org/openqa/selenium/devtools/v132/v132Javascript.java
  java/src/org/openqa/selenium/devtools/v132/v132Log.java
  java/src/org/openqa/selenium/devtools/v132/v132Network.java
  java/src/org/openqa/selenium/devtools/v132/v132Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/test/org/openqa/selenium/bidi/input/CombinedInputActionsTest.java
  java/test/org/openqa/selenium/bidi/input/DefaultMouseTest.java
  java/version.bzl
  javascript/node/selenium-webdriver/BUILD.bazel
  javascript/node/selenium-webdriver/CHANGES.md
  javascript/node/selenium-webdriver/package.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/pyproject.toml
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/test/selenium/webdriver/common/frame_switching_tests.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/bidi/struct.rb
  rb/lib/selenium/webdriver/common/logger.rb
  rb/lib/selenium/webdriver/version.rb
  rb/spec/integration/selenium/webdriver/action_builder_spec.rb
  rust/CHANGELOG.md
Labels: C-build

#15121 [Java] Add Locale.ROOT to avoid port formatting issues for all drivers
  java/src/org/openqa/selenium/chrome/ChromeDriverService.java
  java/src/org/openqa/selenium/edge/EdgeDriverService.java
  java/src/org/openqa/selenium/firefox/GeckoDriverService.java
  java/src/org/openqa/selenium/ie/InternetExplorerDriverService.java
  java/src/org/openqa/selenium/remote/service/DriverService.java
  java/test/org/openqa/selenium/chrome/ChromeDriverFunctionalTest.java
  java/test/org/openqa/selenium/edge/EdgeDriverFunctionalTest.java
  java/test/org/openqa/selenium/firefox/FirefoxDriverTest.java
  java/test/org/openqa/selenium/ie/InternetExplorerDriverTest.java
  java/test/org/openqa/selenium/safari/SafariDriverTest.java
Labels: Review effort [1-5]: 2

#15126 [rust] Bumping to 0.4.29-nightly
  rust/BUILD.bazel
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
Labels: Review effort [1-5]: 1

#15129 [dotnet] Improve format of generated CDP types
  third_party/dotnet/devtools/src/generator/Templates/command.hbs
  third_party/dotnet/devtools/src/generator/Templates/domain.hbs
  third_party/dotnet/devtools/src/generator/Templates/event.hbs
  third_party/dotnet/devtools/src/generator/Templates/type-hash.hbs
  third_party/dotnet/devtools/src/generator/Templates/type-object.hbs
Labels: Review effort [1-5]: 2

#15133 [dotnet] [bidi] Add network SetCacheBehavior command
  dotnet/src/webdriver/BiDi/Communication/Command.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextNetworkModule.cs
  dotnet/src/webdriver/BiDi/Modules/Network/NetworkModule.cs
  dotnet/src/webdriver/BiDi/Modules/Network/SetCacheBehaviorCommand.cs
  dotnet/test/common/BiDi/Network/NetworkTest.cs
Labels: Review effort [1-5]: 2

#15132 [grid] Grid UI could not open session live view
  java/CHANGELOG
  java/version.bzl
  javascript/grid-ui/src/components/LiveView/LiveView.tsx
Labels: Review effort [1-5]: 2

#15130 [java][bidi]: implement bidi `setCacheBehavior`
  java/src/org/openqa/selenium/bidi/module/Network.java
  java/src/org/openqa/selenium/bidi/network/CacheBehavior.java
  java/test/org/openqa/selenium/bidi/network/NetworkCommandsTest.java
Labels: Review effort [1-5]: 2

#15128 [py] Fix installing most of the data from source distributions
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/pyproject.toml
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
Labels: Review effort [1-5]: 2

#14900 [rb] Add Bidi Network Response Handler
  rb/lib/selenium/webdriver/bidi.rb
  rb/lib/selenium/webdriver/bidi/network.rb
  rb/lib/selenium/webdriver/bidi/network/cookies.rb
  rb/lib/selenium/webdriver/bidi/network/credentials.rb
  rb/lib/selenium/webdriver/bidi/network/headers.rb
  rb/lib/selenium/webdriver/bidi/network/intercepted_auth.rb
  rb/lib/selenium/webdriver/bidi/network/intercepted_item.rb
  rb/lib/selenium/webdriver/bidi/network/intercepted_request.rb
  rb/lib/selenium/webdriver/bidi/network/intercepted_response.rb
  rb/lib/selenium/webdriver/bidi/network/url_pattern.rb
  rb/lib/selenium/webdriver/common/network.rb
  rb/sig/lib/selenium/webdriver/bidi.rbs
  rb/sig/lib/selenium/webdriver/bidi/network.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/cookies.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/credentials.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/headers.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/intercepted_auth.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/intercepted_item.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/intercepted_request.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/intercepted_response.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/set_cookie_headers.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/url_pattern.rbs
  rb/sig/lib/selenium/webdriver/bidi/session.rbs
  rb/sig/lib/selenium/webdriver/common/network.rbs
  rb/spec/integration/selenium/webdriver/bidi/network_spec.rb
  rb/spec/integration/selenium/webdriver/network_spec.rb
  rb/spec/unit/selenium/webdriver/bidi/cookies_spec.rb
  rb/spec/unit/selenium/webdriver/bidi/credentials_spec.rb
  rb/spec/unit/selenium/webdriver/bidi/headers_spec.rb
Labels: C-rb, Review effort [1-5]: 3

#15101 [dotnet] Annotate nullability for `DriverService` and chromium/safari services
  dotnet/src/webdriver/Chromium/ChromiumDriverService.cs
  dotnet/src/webdriver/DriverService.cs
  dotnet/src/webdriver/Safari/SafariDriverService.cs
Labels: Review effort [1-5]: 2

#15147 [dotnet] Add nullability to `Command` type
  dotnet/src/webdriver/Command.cs
Labels: Review effort [1-5]: 2

#14804 [dotnet] Annotate nullable reference types on input devices
  dotnet/src/webdriver/Interactions/InputDevice.cs
  dotnet/src/webdriver/Interactions/KeyInputDevice.cs
  dotnet/src/webdriver/Interactions/PointerInputDevice.cs
  dotnet/src/webdriver/Interactions/WheelInputDevice.cs
Labels: Review effort [1-5]: 2

#15148 [dotnet] Annotate nullability on `SendingRemoteHttpRequestEventArgs`
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
  dotnet/src/webdriver/Remote/SendingRemoteHttpRequestEventArgs.cs
Labels: Review effort [1-5]: 2

#15157 [dotnet] Address some build warnings
  dotnet/src/webdriver/Cookie.cs
  dotnet/src/webdriver/CookieJar.cs
  dotnet/src/webdriver/Internal/FileUtilities.cs
Labels: Review effort [1-5]: 2

#15144 [dotnet] Enhance PrintOptions class to support for predefined and cus…
  dotnet/src/webdriver/PrintOptions.cs
  dotnet/test/common/PrintTest.cs
Labels: Review effort [1-5]: 2

#15145 [py] Fix installing most of the data from source distributions
  MODULE.bazel
  py/pyproject.toml
Labels: Review effort [1-5]: 1

#15165 Simplify user description issue template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review effort [1-5]: 1

#15109 Beatify readme header
  README.md
Labels: Review effort [1-5]: 1

#15164 Readme header license
  README.md
Labels: Review effort [1-5]: 1

#15163 [dotnet] Improve bidi exception when it is not enabled
  dotnet/src/webdriver/BiDi/WebDriver.Extensions.cs
Labels: Review effort [1-5]: 1

#15167 [dotnet] Annotate nullability on `DriverOptions`
  dotnet/src/webdriver/DriverOptions.cs
Labels: Review effort [1-5]: 2

#15045 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort [1-5]: 2

#15152 [dotnet] Annotate nullability on interactions
  dotnet/src/webdriver/ElementCoordinates.cs
  dotnet/src/webdriver/Interactions/ActionSequence.cs
  dotnet/src/webdriver/Interactions/IAction.cs
  dotnet/src/webdriver/Interactions/ICoordinates.cs
  dotnet/src/webdriver/Interactions/InputDeviceKind.cs
  dotnet/src/webdriver/Interactions/Interaction.cs
  dotnet/src/webdriver/Interactions/PauseInteraction.cs
  dotnet/src/webdriver/WebElement.cs
Labels: Review effort [1-5]: 2

#15162 [dotnet] [bidi] Use JsonSerializerContext to be AOT friendly
  dotnet/src/webdriver/BUILD.bazel
  dotnet/src/webdriver/BiDi/Communication/Broker.cs
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Communication/Transport/ITransport.cs
  dotnet/src/webdriver/BiDi/Communication/Transport/WebSocketTransport.cs
Labels: Review effort [1-5]: 3

#15181 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort [1-5]: 1

#15180 [dotnet] Generate JSON serializer per protocol
  third_party/dotnet/devtools/src/generator/CodeGen/ProtocolGenerator.cs
  third_party/dotnet/devtools/src/generator/Templates/DevToolsSessionDomains.hbs
Labels: Review effort [1-5]: 2

#15175 [java] Ensure purging dead nodes service interval is configurable
  java/src/org/openqa/selenium/grid/commands/Hub.java
  java/src/org/openqa/selenium/grid/commands/Standalone.java
  java/src/org/openqa/selenium/grid/distributor/config/DistributorFlags.java
  java/src/org/openqa/selenium/grid/distributor/config/DistributorOptions.java
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/test/org/openqa/selenium/grid/distributor/AddingNodesTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorDrainingTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorNodeAvailabilityTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorTest.java
  java/test/org/openqa/selenium/grid/distributor/SessionSchedulingTest.java
  java/test/org/openqa/selenium/grid/distributor/local/LocalDistributorTest.java
  java/test/org/openqa/selenium/grid/graphql/GraphqlHandlerTest.java
  java/test/org/openqa/selenium/grid/router/JmxTest.java
  java/test/org/openqa/selenium/grid/router/NewSessionCreationTest.java
  java/test/org/openqa/selenium/grid/router/RouterTest.java
  java/test/org/openqa/selenium/grid/router/SessionCleanUpTest.java
  java/test/org/openqa/selenium/grid/router/SessionQueueGridTest.java
  java/test/org/openqa/selenium/grid/router/SessionQueueGridWithTimeoutTest.java
Labels: Review effort [1-5]: 2

#15187 [bazel] Bump JS rulesets
  MODULE.bazel
Labels: Review effort [1-5]: 1

#15193 [dotnet] Fix name collisions for commands/responses/eventargs
  third_party/dotnet/devtools/NuGet.Config
  third_party/dotnet/devtools/src/generator/CodeGen/CommandInfo.cs
  third_party/dotnet/devtools/src/generator/CodeGen/EventInfo.cs
  third_party/dotnet/devtools/src/generator/Templates/DevToolsSessionDomains.hbs
Labels: Review effort [1-5]: 2

#15194 Add explicit reference to cdp types
  MODULE.bazel
  java/src/org/openqa/selenium/grid/commands/Hub.java
  java/src/org/openqa/selenium/grid/commands/Standalone.java
  java/src/org/openqa/selenium/grid/distributor/config/DistributorFlags.java
  java/src/org/openqa/selenium/grid/distributor/config/DistributorOptions.java
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/test/org/openqa/selenium/grid/distributor/AddingNodesTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorDrainingTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorNodeAvailabilityTest.java
  java/test/org/openqa/selenium/grid/distributor/DistributorTest.java
  java/test/org/openqa/selenium/grid/distributor/SessionSchedulingTest.java
  java/test/org/openqa/selenium/grid/distributor/local/LocalDistributorTest.java
  java/test/org/openqa/selenium/grid/graphql/GraphqlHandlerTest.java
  java/test/org/openqa/selenium/grid/router/JmxTest.java
  java/test/org/openqa/selenium/grid/router/NewSessionCreationTest.java
  java/test/org/openqa/selenium/grid/router/RouterTest.java
  java/test/org/openqa/selenium/grid/router/SessionCleanUpTest.java
  java/test/org/openqa/selenium/grid/router/SessionQueueGridTest.java
  java/test/org/openqa/selenium/grid/router/SessionQueueGridWithTimeoutTest.java
  third_party/dotnet/devtools/src/generator/CodeGen/TypeInfo.cs
  third_party/dotnet/devtools/src/generator/Templates/DevToolsSessionDomains.hbs
Labels: Review effort [1-5]: 3

#15154 [dotnet] Annotate nullability on chrome-based driver services
  dotnet/src/webdriver/Chrome/ChromeDriverService.cs
  dotnet/src/webdriver/Chromium/ChromiumDriverService.cs
  dotnet/src/webdriver/Edge/EdgeDriverService.cs
  dotnet/src/webdriver/IE/InternetExplorerDriverService.cs
Labels: Review effort [1-5]: 2

#15197 [java] Ensure Selenium logging options are respected if java logging …
  java/src/org/openqa/selenium/grid/log/LoggingOptions.java
Labels: Review effort [1-5]: 2

#15170 [java] do not enable CDP deprecation warning if BiDi enabled
  java/src/org/openqa/selenium/devtools/CdpEndpointFinder.java
  java/src/org/openqa/selenium/firefox/FirefoxDriver.java
Labels: Review effort [1-5]: 2

#15179 [grid] Add feature to go directly to a VNC session
  javascript/grid-ui/src/App.tsx
  javascript/grid-ui/src/components/RunningSessions/RunningSessions.tsx
  javascript/grid-ui/src/screens/Sessions/Sessions.tsx
Labels: Review effort [1-5]: 2

#15198 [dotnet] Simplify and modernize `DevToolsDomains.InitializeDomains`
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
Labels: Review effort [1-5]: 2

#15204 [dotnet] Add nullability to Chromium configuration types
  dotnet/src/webdriver/Chromium/ChromiumAndroidOptions.cs
  dotnet/src/webdriver/Chromium/ChromiumMobileEmulationDeviceSettings.cs
  dotnet/src/webdriver/Chromium/ChromiumNetworkConditions.cs
  dotnet/src/webdriver/Chromium/ChromiumPerformanceLoggingPreferences.cs
Labels: Review effort [1-5]: 2

#15203 [dotnet] Allow UTF-16 tolerant string converter as a dictionary key
  dotnet/src/webdriver/DevTools/Json/StringConverter.cs
Labels: Review effort [1-5]: 2

#15201 [dotnet] Fix webauth credential to allow nullable `rpID`
  dotnet/src/webdriver/VirtualAuth/Credential.cs
  dotnet/test/common/VirtualAuthn/VirtualAuthenticatorTest.cs
Labels: Review effort [1-5]: 2

#15202 [dotnet] [bidi] Avoid polymorphic commands to be more statically easier
  dotnet/src/webdriver/BiDi/Communication/Broker.cs
  dotnet/src/webdriver/BiDi/Communication/Command.cs
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Communication/Transport/ITransport.cs
  dotnet/src/webdriver/BiDi/Communication/Transport/WebSocketTransport.cs
  dotnet/src/webdriver/BiDi/Modules/Browser/BrowserModule.cs
  dotnet/src/webdriver/BiDi/Modules/Browser/CloseCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Browser/CreateUserContextCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Browser/GetUserContextsCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Browser/RemoveUserContextCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/ActivateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextModule.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/CaptureScreenshotCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/CloseCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/CreateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/GetTreeCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/HandleUserPromptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/LocateNodesCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/NavigateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/PrintCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/ReloadCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/SetViewportCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/TraverseHistoryCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Input/PerformActionsCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Input/ReleaseActionsCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/AddInterceptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/ContinueRequestCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/ContinueResponseCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/ContinueWithAuthCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/FailRequestCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/NetworkModule.cs
  dotnet/src/webdriver/BiDi/Modules/Network/ProvideResponseCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/RemoveInterceptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/SetCacheBehaviorCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/AddPreloadScriptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/CallFunctionCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/DisownCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/GetRealmsCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/RemovePreloadScriptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/ScriptModule.cs
  dotnet/src/webdriver/BiDi/Modules/Session/EndCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Session/NewCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Session/SessionModule.cs
  dotnet/src/webdriver/BiDi/Modules/Session/StatusCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Session/SubscribeCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Session/UnsubscribeCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/DeleteCookiesCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/GetCookiesCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/SetCookieCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/StorageModule.cs
Labels: Review effort [1-5]: 4

#15205 [dotnet] Optimize reflection in `JsonEnumMemberConverter`
  dotnet/src/webdriver/DevTools/Json/JsonEnumMemberConverter.cs
Labels: Review effort [1-5]: 2
