Repository SeleniumHQ/selenium, pull requests merged in 2025-05, with the labels that each got.

#15682 [java] If a dep comes from a BOM, omit the version number
  MODULE.bazel
  java/maven_install.json
Labels: C-java, B-build, Review effort 2/5

#15689 [java] Bump deps from BOMs to latest versions
  MODULE.bazel
  java/maven_install.json
Labels: C-java, B-build, Review effort 2/5

#15680 [build] allow manually rerunning RBE with cache disabled
  .github/workflows/ci-rbe.yml
  scripts/github-actions/ci-build.sh
Labels: B-build, Review effort 2/5

#15695 [py] Exclude devtools directory from type checking
  py/pyproject.toml
Labels: C-py, Review effort 1/5

#15696 [py] Add clean_options fixture and remove all Python tests from .skipped-tests
  .skipped-tests
  py/conftest.py
  py/test/selenium/webdriver/chrome/chrome_launcher_tests.py
  py/test/selenium/webdriver/chrome/chrome_service_tests.py
  py/test/selenium/webdriver/chrome/proxy_tests.py
  py/test/selenium/webdriver/edge/edge_launcher_tests.py
  py/test/selenium/webdriver/edge/edge_service_tests.py
Labels: Review effort 2/5

#15667 [java][bidi]: enable tests for storage module for edge
  java/test/org/openqa/selenium/bidi/storage/BUILD.bazel
  java/test/org/openqa/selenium/bidi/storage/StorageCommandsTest.java
Labels: C-java, B-build, B-devtools, Review effort 1/5

#15669 [py][bidi]: add bidi storage module
  py/selenium/webdriver/common/bidi/storage.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_storage_tests.py
Labels: C-py, B-devtools, Review effort 3/5

#15681 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15701 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15692 [build] allow GitHub Actions runner to use 4GB for JVM Heap
  scripts/github-actions/ci-build.sh
Labels: B-build, Review effort 1/5

#15698 update old freenode channel link to libera
  CONTRIBUTING.md
  javascript/selenium-webdriver/README.md
Labels: C-nodejs, Review effort 1/5

#15705 fixing mypy error from #15693
  py/selenium/webdriver/remote/webelement.py
  py/selenium/webdriver/support/wait.py
Labels: C-py, B-support, Review effort 2/5

#15717 [rb] move all guard and zipper tests to unit tests
  rb/spec/BUILD.bazel
  rb/spec/integration/selenium/webdriver/guard_spec.rb
  rb/spec/unit/selenium/webdriver/guards_spec.rb
  rb/spec/unit/selenium/webdriver/zipper_spec.rb
Labels: C-rb, Review effort 2/5

#15708 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15719 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15363 [rust] Replace WMIC commands (deprecated) by WinAPI in Windows
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/config.rs
  rust/src/files.rs
  rust/src/lib.rs
Labels: C-rust, Review effort 3/5

#15725 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15728 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort 1/5

#15727 Let firefox choose the bidi port by default
  rb/lib/selenium/webdriver/firefox/service.rb
  rb/spec/integration/selenium/webdriver/firefox/service_spec.rb
  rb/spec/unit/selenium/webdriver/firefox/service_spec.rb
Labels: C-rb, Review effort 2/5

#15730 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15737 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15736 [py] Missing Headers Assignment in Network Class’s _on_request()
  py/selenium/webdriver/common/bidi/network.py
Labels: C-py, B-devtools, Review effort 1/5

#15341 [py] correct type annotations of default-None params
  py/selenium/webdriver/chrome/service.py
  py/selenium/webdriver/chrome/webdriver.py
  py/selenium/webdriver/chromium/service.py
  py/selenium/webdriver/chromium/webdriver.py
  py/selenium/webdriver/common/actions/key_actions.py
  py/selenium/webdriver/common/actions/pointer_actions.py
  py/selenium/webdriver/common/actions/wheel_actions.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/edge/service.py
  py/selenium/webdriver/edge/webdriver.py
  py/selenium/webdriver/firefox/service.py
  py/selenium/webdriver/firefox/webdriver.py
  py/selenium/webdriver/ie/service.py
  py/selenium/webdriver/ie/webdriver.py
  py/selenium/webdriver/remote/remote_connection.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/safari/service.py
  py/selenium/webdriver/safari/webdriver.py
  py/selenium/webdriver/support/event_firing_webdriver.py
  py/selenium/webdriver/webkitgtk/webdriver.py
  py/selenium/webdriver/wpewebkit/webdriver.py
Labels: Review effort 2/5

#15739 [py] Add missing 'id' property to ShadowRoot class
  py/selenium/webdriver/remote/shadowroot.py
Labels: C-py, Review effort 1/5

#15731 [py] Bump Python package requirements to latest versions
  .github/workflows/ci-python.yml
  README.md
  py/BUILD.bazel
  py/conftest.py
  py/pyproject.toml
  py/requirements.txt
  py/requirements_lock.txt
  py/test/selenium/webdriver/common/devtools_tests.py
  py/test/selenium/webdriver/firefox/firefox_service_tests.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
  scripts/format.sh
Labels: C-py, B-build, Review effort 2/5

#15751 [py]: return `message` as part of exception in `execute` method
  py/selenium/webdriver/remote/websocket_connection.py
Labels: C-py, Review effort 1/5

#15764 [java] Removing deprecated `setScriptTimeout` and `pageLoadTimeout`.
  java/src/org/openqa/selenium/WebDriver.java
  java/src/org/openqa/selenium/remote/DriverCommand.java
  java/src/org/openqa/selenium/remote/RemoteWebDriver.java
  java/src/org/openqa/selenium/support/events/WebDriverListener.java
  java/test/org/openqa/selenium/support/decorators/DecoratedTimeoutsTest.java
Labels: C-java, B-support, Review effort 2/5

#15774 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15749 [py][bidi]: add bidi webExtension module
  common/extensions/BUILD.bazel
  py/BUILD.bazel
  py/docs/source/api.rst
  py/selenium/webdriver/common/bidi/webextension.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_webextension_tests.py
  py/test/selenium/webdriver/firefox/ff_installs_addons_tests.py
Labels: C-py, B-devtools, Review effort 2/5

#15756 [py] Better error for downloads on local webdrivers
  py/selenium/webdriver/chromium/webdriver.py
  py/selenium/webdriver/firefox/webdriver.py
  py/selenium/webdriver/ie/webdriver.py
  py/selenium/webdriver/safari/webdriver.py
  py/selenium/webdriver/webkitgtk/webdriver.py
  py/selenium/webdriver/wpewebkit/webdriver.py
Labels: C-py, Review effort 1/5

#15779 [py] Add missing modules to python API docs
  py/docs/source/api.rst
Labels: C-py

#15759 [grid] UI Sessions capability fields to display as additional columns
  javascript/grid-ui/src/components/RunningSessions/ColumnSelector.tsx
  javascript/grid-ui/src/components/RunningSessions/RunningSessions.tsx
  javascript/grid-ui/src/models/session-data.ts
  javascript/grid-ui/src/tests/components/ColumnSelector.test.tsx
Labels: B-grid, Review effort 2/5

#15777 [grid] UI Overview is able to see live preview per Node
  javascript/grid-ui/src/components/Node/Node.tsx
  javascript/grid-ui/src/screens/Overview/Overview.tsx
  javascript/grid-ui/src/tests/components/Node.test.tsx
  javascript/grid-ui/src/tests/components/Overview.test.tsx
Labels: B-grid, Review effort 3/5

#15776 [build] Prepare for release of Selenium 4.33.0
  .github/ISSUE_TEMPLATE/bug-report.yml
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v137/BUILD.bazel
  common/devtools/chromium/v137/browser_protocol.pdl
  common/devtools/chromium/v137/js_protocol.pdl
  common/repositories.bzl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v137/V137Domains.cs
  dotnet/src/webdriver/DevTools/v137/V137JavaScript.cs
  dotnet/src/webdriver/DevTools/v137/V137Log.cs
  dotnet/src/webdriver/DevTools/v137/V137Network.cs
  dotnet/src/webdriver/DevTools/v137/V137Target.cs
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/devtools/v137/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v137/v137CdpInfo.java
  java/src/org/openqa/selenium/devtools/v137/v137Domains.java
  java/src/org/openqa/selenium/devtools/v137/v137Events.java
  java/src/org/openqa/selenium/devtools/v137/v137Javascript.java
  java/src/org/openqa/selenium/devtools/v137/v137Log.java
  java/src/org/openqa/selenium/devtools/v137/v137Network.java
  java/src/org/openqa/selenium/devtools/v137/v137Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/selenium-webdriver/BUILD.bazel
  javascript/selenium-webdriver/CHANGES.md
  javascript/selenium-webdriver/package.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/pyproject.toml
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  py/test/selenium/webdriver/common/bidi_tests.py
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/version.rb
  rust/BUILD.bazel
  rust/CHANGELOG.md
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
Labels: C-py, C-rb, C-dotnet, C-java, C-nodejs, B-build, B-devtools, C-rust, Review effort 2/5, B-manager, C-build

#15783 [ci] Clear warning from Grid UI component tests
  javascript/grid-ui/src/screens/Overview/Overview.tsx
  javascript/grid-ui/src/tests/components/Node.test.tsx
  javascript/grid-ui/src/tests/components/Overview.test.tsx
Labels: B-grid, Review effort 2/5

#15784 [py] Upgrade type hints
  py/selenium/common/exceptions.py
  py/selenium/types.py
  py/selenium/webdriver/chrome/service.py
  py/selenium/webdriver/chromium/options.py
  py/selenium/webdriver/chromium/service.py
  py/selenium/webdriver/common/actions/action_builder.py
  py/selenium/webdriver/common/actions/input_device.py
  py/selenium/webdriver/common/actions/interaction.py
  py/selenium/webdriver/common/actions/pointer_input.py
  py/selenium/webdriver/common/bidi/browser.py
  py/selenium/webdriver/common/bidi/browsing_context.py
  py/selenium/webdriver/common/bidi/cdp.py
  py/selenium/webdriver/common/bidi/common.py
  py/selenium/webdriver/common/bidi/log.py
  py/selenium/webdriver/common/bidi/storage.py
  py/selenium/webdriver/common/bidi/webextension.py
  py/selenium/webdriver/common/by.py
  py/selenium/webdriver/common/fedcm/dialog.py
  py/selenium/webdriver/common/log.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/common/print_page_options.py
  py/selenium/webdriver/common/selenium_manager.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/common/timeouts.py
  py/selenium/webdriver/common/utils.py
  py/selenium/webdriver/common/virtual_authenticator.py
  py/selenium/webdriver/edge/service.py
  py/selenium/webdriver/firefox/options.py
  py/selenium/webdriver/firefox/service.py
  py/selenium/webdriver/ie/options.py
  py/selenium/webdriver/ie/service.py
  py/selenium/webdriver/remote/errorhandler.py
  py/selenium/webdriver/remote/fedcm.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/webelement.py
  py/selenium/webdriver/safari/options.py
  py/selenium/webdriver/safari/service.py
  py/selenium/webdriver/support/color.py
  py/selenium/webdriver/support/event_firing_webdriver.py
  py/selenium/webdriver/support/expected_conditions.py
  py/selenium/webdriver/support/relative_locator.py
  py/selenium/webdriver/support/select.py
  py/selenium/webdriver/support/wait.py
  py/selenium/webdriver/webkitgtk/service.py
  py/selenium/webdriver/wpewebkit/options.py
  py/selenium/webdriver/wpewebkit/service.py
  py/test/selenium/webdriver/common/bidi_webextension_tests.py
  py/test/selenium/webdriver/common/virtual_authenticator_tests.py
  py/test/selenium/webdriver/remote/remote_downloads_tests.py
  py/test/unit/selenium/webdriver/virtual_authenticator/credentials_tests.py
Labels: C-py, I-enhancement, Review effort 2/5

#15795 [dotnet] [bidi] Add AcceptInsecureCerts and Proxy options when create new user context
  dotnet/src/webdriver/BiDi/Modules/Browser/BrowserModule.cs
  dotnet/src/webdriver/BiDi/Modules/Browser/CreateUserContextCommand.cs
Labels: C-dotnet, Review effort 2/5

#15796 [grid] Silent fail on invalid log level
  java/src/org/openqa/selenium/grid/log/LoggingOptions.java
Labels: B-grid, C-java, Review effort 1/5

#15804 Don't silence stderr in format.sh
  scripts/format.sh
Labels: B-build, Review effort 1/5

#15811 [py] Lint Python with ruff
  .gitignore
  MODULE.bazel
  javascript/private/gen_file.py
  multitool.lock.json
  py/BUILD.bazel
  py/docs/source/conf.py
  py/release-selenium.py
  py/test/selenium/webdriver/common/bidi_tests.py
  py/tox.ini
  scripts/format.sh
  scripts/pinned_browsers.py
  scripts/selenium_manager.py
  scripts/update_cdp.py
Labels: C-py, B-build

#15812 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15818 [py] Bump ruff version
  py/tox.ini
Labels: C-py, Review effort 1/5

#15824 [dotnet] Remove unnecessary stylecop files
  dotnet/src/support/Settings.StyleCop
  dotnet/src/support/WebDriver.Support.csproj
  dotnet/src/support/WebDriver.Support.ruleset
  dotnet/src/webdriver/Settings.StyleCop
  dotnet/src/webdriver/WebDriver.csproj
  dotnet/src/webdriver/WebDriver.ruleset
  dotnet/test/chrome/Settings.StyleCop
  dotnet/test/chrome/WebDriver.Chrome.Tests.csproj
  dotnet/test/common/Settings.StyleCop
  dotnet/test/common/WebDriver.Common.Tests.csproj
  dotnet/test/firefox/Settings.StyleCop
  dotnet/test/firefox/WebDriver.Firefox.Tests.csproj
  dotnet/test/ie/Settings.StyleCop
  dotnet/test/ie/WebDriver.IE.Tests.csproj
  dotnet/test/remote/Settings.StyleCop
  dotnet/test/remote/WebDriver.Remote.Tests.csproj
  dotnet/test/safari/WebDriver.Safari.Tests.csproj
  dotnet/test/support/Settings.StyleCop
  dotnet/test/support/WebDriver.Support.Tests.csproj
Labels: C-dotnet, B-support, Review effort 1/5

#15825 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15828 [py] Lint and format all python files
  py/tox.ini
Labels: C-py, Review effort 1/5

#15794 [py][bidi]: add `enable_webextensions` option for chromium-based browsers
  py/conftest.py
  py/selenium/webdriver/chromium/options.py
  py/selenium/webdriver/common/bidi/webextension.py
  py/test/selenium/webdriver/common/bidi_webextension_tests.py
Labels: C-py, B-devtools, Review effort 2/5

#15822 [py] Auto-generate Python API docs from code
  .gitignore
  py/docs/.readthedocs.yaml
  py/docs/Makefile
  py/docs/README.rst
  py/docs/source/api.rst
  py/generate_api_module_listing.py
  py/tox.ini
Labels: C-py, Review effort 2/5

#15832 [py] Fix python API docs publishing at readthedocs
  py/docs/.readthedocs.yaml
Labels: C-py

#15831 Change flag for Chrome/Edge headless mode in tests
  java/test/org/openqa/selenium/edge/EdgeDriverFunctionalTest.java
  java/test/org/openqa/selenium/testing/drivers/Browser.java
  py/conftest.py
Labels: C-py, C-java, Review effort 1/5

#15417 [rb] Add support for beta chrome
  MODULE.bazel
  common/browsers.bzl
  common/repositories.bzl
  rb/spec/integration/BUILD.bazel
  rb/spec/integration/selenium/webdriver/chrome/BUILD.bazel
  rb/spec/tests.bzl
  scripts/pinned_browsers.py
Labels: C-rb
