Repository SeleniumHQ/selenium, pull requests merged in 2025-02, with the labels that each got.

#15206 [dotnet] Annotate nullability on firefox and chromium options
  dotnet/src/webdriver/Chrome/ChromeOptions.cs
  dotnet/src/webdriver/Edge/EdgeOptions.cs
  dotnet/src/webdriver/Firefox/FirefoxAndroidOptions.cs
  dotnet/src/webdriver/Firefox/FirefoxCommandContext.cs
  dotnet/src/webdriver/Firefox/FirefoxDriverLogLevel.cs
  dotnet/src/webdriver/Firefox/FirefoxOptions.cs
Labels: Review effort [1-5]: 2

#15208 [dotnet] Annotate nullability on `Actions` type
  dotnet/src/webdriver/Interactions/Actions.cs
  dotnet/src/webdriver/Interactions/InputDevice.cs
  dotnet/src/webdriver/Interactions/PauseInteraction.cs
  dotnet/src/webdriver/Keys.cs
Labels: Review effort [1-5]: 3

#15085 [dotnet] Update `Moq` test dependency
  dotnet/paket.dependencies
  dotnet/paket.lock
  dotnet/paket.nuget.bzl
  dotnet/test/common/WebDriver.Common.Tests.csproj
  dotnet/test/support/WebDriver.Support.Tests.csproj
Labels: Review effort [1-5]: 1

#15153 [dotnet] Fix marionette host Firefox argument
  dotnet/src/webdriver/Firefox/FirefoxDriverService.cs
Labels: Review effort [1-5]: 1

#15212 [dotnet] Align paket target framework with supported versions
  dotnet/paket.dependencies
Labels: Review effort [1-5]: 1

#15211 [dotnet] Annotate nullability on `Navigate()` and `SwitchTo()`
  dotnet/src/webdriver/INavigation.cs
  dotnet/src/webdriver/ITargetLocator.cs
  dotnet/src/webdriver/Navigator.cs
  dotnet/src/webdriver/TargetLocator.cs
Labels: Review effort [1-5]: 2

#15064 [py] Enhance PrintOptions to support default, predefined, and custom page sizes (#15052)
  py/selenium/webdriver/common/print_page_options.py
  py/test/unit/selenium/webdriver/common/print_page_options_tests.py
Labels: Review effort [1-5]: 2

#15207 [dotnet] Annotate nullability on Firefox profile
  dotnet/src/webdriver/Firefox/FirefoxProfile.cs
  dotnet/src/webdriver/Firefox/FirefoxProfileManager.cs
  dotnet/src/webdriver/Internal/FileUtilities.cs
Labels: Review effort [1-5]: 3

#15209 [dotnet] Annotate nullability on network interactions
  dotnet/src/webdriver/DevTools/Network.cs
  dotnet/src/webdriver/DevTools/v130/V130Network.cs
  dotnet/src/webdriver/DevTools/v131/V131Network.cs
  dotnet/src/webdriver/DevTools/v132/V132Network.cs
  dotnet/src/webdriver/DevTools/v85/V85Network.cs
  dotnet/src/webdriver/ICredentials.cs
  dotnet/src/webdriver/NetworkManager.cs
  dotnet/src/webdriver/PasswordCredentials.cs
  dotnet/src/webdriver/UserAgent.cs
Labels: Review effort [1-5]: 3

#15210 [dotnet] Add nullability to `Manage()`
  dotnet/src/webdriver/INavigation.cs
  dotnet/src/webdriver/IOptions.cs
  dotnet/src/webdriver/ITimeouts.cs
  dotnet/src/webdriver/IWindow.cs
  dotnet/src/webdriver/Navigator.cs
  dotnet/src/webdriver/OptionsManager.cs
  dotnet/src/webdriver/Timeouts.cs
  dotnet/src/webdriver/Window.cs
Labels: Review effort [1-5]: 2

#15200 [java][js][rb][py][dotnet] Remove firefox cdp
  dotnet/src/webdriver/Firefox/FirefoxDriver.cs
  java/src/org/openqa/selenium/firefox/FirefoxDriver.java
  java/src/org/openqa/selenium/firefox/FirefoxOptions.java
  java/test/org/openqa/selenium/devtools/BUILD.bazel
  java/test/org/openqa/selenium/devtools/CdpFacadeTest.java
  javascript/node/selenium-webdriver/lib/webdriver.js
  javascript/node/selenium-webdriver/test/devtools_test.js
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/devtools_tests.py
  rb/lib/selenium/webdriver/firefox/driver.rb
  rb/sig/lib/selenium/webdriver/firefox/driver.rbs
  rb/spec/integration/selenium/webdriver/devtools_spec.rb
Labels: Review effort [1-5]: 4

#15219 [dotnet] Annotate nullability on `SafariOptions`, error, and enums
  dotnet/src/webdriver/CapabilityType.cs
  dotnet/src/webdriver/IRotatable.cs
  dotnet/src/webdriver/Safari/SafariOptions.cs
  dotnet/src/webdriver/ScreenOrientation.cs
  dotnet/src/webdriver/WebDriverError.cs
  dotnet/src/webdriver/WebDriverResult.cs
  dotnet/src/webdriver/WindowType.cs
Labels: Review effort [1-5]: 2

#15221 [dotnet] Fix `JavaScriptEngine.ScriptCallbackBindings` not containing new bindings
  dotnet/src/webdriver/InitializationScript.cs
  dotnet/src/webdriver/JavaScriptEngine.cs
  dotnet/test/common/ExecutingJavascriptTest.cs
Labels: Review effort [1-5]: 2

#15225 [dotnet] Handle nullability on `WebElement`
  dotnet/src/webdriver/ILocatable.cs
  dotnet/src/webdriver/ITakesScreenshot.cs
  dotnet/src/webdriver/WebElement.cs
  dotnet/src/webdriver/WebElementFactory.cs
Labels: Review effort [1-5]: 3

#15220 [dotnet] Annotate nullability on `FirefoxDriverService`
  dotnet/src/webdriver/Firefox/FirefoxDriverService.cs
Labels: Review effort [1-5]: 2

#15143 [dotnet] Add nullability annotations to devtools domains
  dotnet/src/webdriver/DevTools/DevToolsExtensionMethods.cs
  dotnet/src/webdriver/DevTools/DevToolsOptions.cs
  dotnet/src/webdriver/DevTools/DevToolsSessionDomains.cs
  dotnet/src/webdriver/DevTools/DevToolsSessionEventReceivedEventArgs.cs
  dotnet/src/webdriver/DevTools/DevToolsSessionLogMessageEventArgs.cs
  dotnet/src/webdriver/DevTools/ExceptionThrownEventArgs.cs
  dotnet/src/webdriver/DevTools/Json/JsonEnumMemberConverter.cs
  dotnet/src/webdriver/DevTools/ResponsePausedEventArgs.cs
  dotnet/src/webdriver/DevTools/v130/V130JavaScript.cs
  dotnet/src/webdriver/DevTools/v131/V131JavaScript.cs
  dotnet/src/webdriver/DevTools/v132/V132JavaScript.cs
  dotnet/src/webdriver/DevTools/v85/V85JavaScript.cs
Labels: Review effort [1-5]: 2

#15229 [grid] Add default sessionTimeout to NodeStatus to increase backward compatibility
  java/src/org/openqa/selenium/grid/data/NodeStatus.java
  java/test/org/openqa/selenium/grid/data/NodeStatusTest.java
Labels: C-grid, Review effort [1-5]: 1

#15073 [py]: handle named `get_cookie` and `delete_cookie` for None and empty strings
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/cookie_tests.py
Labels: Review effort [1-5]: 2

#15080 [rb][BiDi] Add support for provide response command
  rb/lib/selenium/webdriver/bidi/network.rb
  rb/lib/selenium/webdriver/bidi/network/intercepted_response.rb
  rb/sig/lib/selenium/webdriver/bidi/network.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/cookies.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/intercepted_response.rbs
  rb/sig/lib/selenium/webdriver/bidi/network/set_cookie_headers.rbs
  rb/spec/integration/selenium/webdriver/bidi/network_spec.rb
  rb/spec/integration/selenium/webdriver/network_spec.rb
Labels: C-rb, Review effort [1-5]: 4

#15243 [dotnet] Add not-null `Response.Value` helper
  dotnet/src/webdriver/Response.cs
Labels: Review effort [1-5]: 1

#15240 [dotnet] Annotate nullability on `Target` protocol
  dotnet/src/webdriver/DevTools/Target.cs
  dotnet/src/webdriver/DevTools/TargetInfo.cs
  dotnet/src/webdriver/DevTools/v130/V130Target.cs
  dotnet/src/webdriver/DevTools/v131/V131Target.cs
  dotnet/src/webdriver/DevTools/v132/V132Target.cs
  dotnet/src/webdriver/DevTools/v85/V85Target.cs
Labels: Review effort [1-5]: 2

#15239 [dotnet] Annotate nullability on `Log` protocol
  dotnet/src/webdriver/DevTools/Log.cs
  dotnet/src/webdriver/DevTools/v130/V130Log.cs
  dotnet/src/webdriver/DevTools/v131/V131Log.cs
  dotnet/src/webdriver/DevTools/v132/V132Log.cs
  dotnet/src/webdriver/DevTools/v85/V85Log.cs
Labels: Review effort [1-5]: 2

#15218 [dotnet] Annotate nullability on `JavaScriptEngine` and related types
  dotnet/src/webdriver/DomMutatedEventArgs.cs
  dotnet/src/webdriver/DomMutationData.cs
  dotnet/src/webdriver/IJavaScriptEngine.cs
  dotnet/src/webdriver/InitializationScript.cs
  dotnet/src/webdriver/JavaScriptCallbackExecutedEventArgs.cs
  dotnet/src/webdriver/JavaScriptConsoleApiCalledEventArgs.cs
  dotnet/src/webdriver/JavaScriptEngine.cs
  dotnet/src/webdriver/JavaScriptExceptionThrownEventArgs.cs
Labels: Review effort [1-5]: 3

#15244 [dotnet] Annotate nullability on `DevToolsSession`
  dotnet/src/webdriver/DevTools/DevToolsCommandData.cs
  dotnet/src/webdriver/DevTools/DevToolsSession.cs
  dotnet/src/webdriver/DevTools/DevToolsSessionLogMessageEventArgs.cs
  dotnet/src/webdriver/DevTools/DevToolsVersionInfo.cs
  dotnet/src/webdriver/DevTools/IDevToolsSession.cs
Labels: Review effort [1-5]: 4

#15250 [dotnet][bidi] Remove json serialization from transport layer
  dotnet/src/webdriver/BiDi/Communication/Broker.cs
  dotnet/src/webdriver/BiDi/Communication/Transport/ITransport.cs
  dotnet/src/webdriver/BiDi/Communication/Transport/WebSocketTransport.cs
Labels: Review effort [1-5]: 2

#15253 [dotnet][bidi] Add OnNavigationCommitted event
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContext.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextModule.cs
Labels: Review effort [1-5]: 2

#15254 [dotnet][bidi] Add optional PromptUnload parameter when closing BrowsingContext and compiler helps
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextModule.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/CaptureScreenshotCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/CloseCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/CreateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/GetTreeCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/HandleUserPromptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/LocateNodesCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/NavigateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/PrintCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/ReloadCommand.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/SetViewportCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/AddInterceptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/ContinueRequestCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/ContinueResponseCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/NetworkModule.cs
  dotnet/src/webdriver/BiDi/Modules/Network/ProvideResponseCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Network/SetCacheBehaviorCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/AddPreloadScriptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/CallFunctionCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/GetRealmsCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/ScriptModule.cs
  dotnet/src/webdriver/BiDi/Modules/Session/SessionModule.cs
  dotnet/src/webdriver/BiDi/Modules/Session/SubscribeCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Session/UnsubscribeCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/DeleteCookiesCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/GetCookiesCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/SetCookieCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/StorageModule.cs
Labels: Review effort [1-5]: 2

#15252 [dotnet] Annotate nullability on `DevTools` and event args
  dotnet/src/webdriver/Chromium/ChromiumOptions.cs
  dotnet/src/webdriver/DevTools/DevToolsSession.cs
  dotnet/src/webdriver/DevTools/DevToolsVersionInfo.cs
  dotnet/src/webdriver/DevTools/ICommand.cs
  dotnet/src/webdriver/DevTools/IDevTools.cs
  dotnet/src/webdriver/DevTools/IDevToolsSession.cs
  dotnet/src/webdriver/DevTools/Json/JsonEnumMemberConverter.cs
  dotnet/src/webdriver/DevTools/WebSocketConnection.cs
  dotnet/src/webdriver/DevTools/v130/V130Network.cs
  dotnet/src/webdriver/DevTools/v131/V131Network.cs
  dotnet/src/webdriver/DevTools/v132/V132Network.cs
  dotnet/src/webdriver/DevTools/v85/V85Network.cs
  dotnet/src/webdriver/DomMutatedEventArgs.cs
  dotnet/src/webdriver/DomMutationData.cs
  dotnet/src/webdriver/DriverCommand.cs
  dotnet/src/webdriver/DriverOptionsMergeResult.cs
  dotnet/src/webdriver/DriverProcessStartedEventArgs.cs
  dotnet/src/webdriver/DriverProcessStartingEventArgs.cs
  dotnet/src/webdriver/HttpRequestData.cs
  dotnet/src/webdriver/HttpResponseContent.cs
  dotnet/src/webdriver/HttpResponseData.cs
  dotnet/src/webdriver/IActionExecutor.cs
  dotnet/src/webdriver/IAllowsFileDetection.cs
  dotnet/src/webdriver/IHasCommandExecutor.cs
  dotnet/src/webdriver/ITargetLocator.cs
  dotnet/src/webdriver/JavaScriptCallbackExecutedEventArgs.cs
  dotnet/src/webdriver/JavaScriptConsoleApiCalledEventArgs.cs
  dotnet/src/webdriver/JavaScriptExceptionThrownEventArgs.cs
  dotnet/src/webdriver/NetworkManager.cs
  dotnet/src/webdriver/NetworkRequestSentEventArgs.cs
  dotnet/src/webdriver/NetworkResponseReceivedEventArgs.cs
  dotnet/src/webdriver/Response.cs
Labels: Review effort [1-5]: 3

#15236 [dotnet] Annotate nullability on platform-specific WebDrivers
  dotnet/src/webdriver/Chrome/ChromeDriver.cs
  dotnet/src/webdriver/Chromium/ChromiumDriver.cs
  dotnet/src/webdriver/Chromium/ChromiumNetworkConditions.cs
  dotnet/src/webdriver/Edge/EdgeDriver.cs
  dotnet/src/webdriver/Firefox/FirefoxDriver.cs
  dotnet/src/webdriver/IE/InternetExplorerDriver.cs
  dotnet/src/webdriver/Safari/SafariDriver.cs
Labels: Review effort [1-5]: 3

#15258 [dotnet] Add back in a public parameterless constructor to `HttpRequestData`
  dotnet/src/webdriver/DevTools/v130/V130Network.cs
  dotnet/src/webdriver/DevTools/v131/V131Network.cs
  dotnet/src/webdriver/DevTools/v132/V132Network.cs
  dotnet/src/webdriver/DevTools/v85/V85Network.cs
  dotnet/src/webdriver/HttpRequestData.cs
  dotnet/src/webdriver/NetworkRequestSentEventArgs.cs
Labels: Review effort [1-5]: 2

#15259 [ci] Do not stale issues/prs assigned to any milestone
  .github/workflows/stale.yml
Labels: Review effort [1-5]: 1

#15267 [dotnet] Simplify user creation of network types
  dotnet/src/webdriver/DevTools/v130/V130Network.cs
  dotnet/src/webdriver/DevTools/v131/V131Network.cs
  dotnet/src/webdriver/DevTools/v132/V132Network.cs
  dotnet/src/webdriver/DevTools/v85/V85Network.cs
  dotnet/src/webdriver/HttpRequestData.cs
  dotnet/src/webdriver/HttpResponseData.cs
  dotnet/src/webdriver/NetworkManager.cs
  dotnet/src/webdriver/NetworkResponseReceivedEventArgs.cs
  dotnet/test/common/NetworkInterceptionTests.cs
Labels: Review effort [1-5]: 2

#15227 [java] Add the debuggerAddress capability back to Firefox options
  py/BUILD.bazel
  py/test/selenium/webdriver/common/devtools_tests.py
  rb/spec/integration/selenium/webdriver/devtools_spec.rb
Labels: Review effort [1-5]: 2

#15271 [java] Avoid augmenting CDP for Firefox
  java/src/org/openqa/selenium/devtools/CdpEndpointFinder.java
  java/src/org/openqa/selenium/firefox/BUILD.bazel
  java/test/org/openqa/selenium/remote/RemoteWebDriverBuilderTest.java
Labels: Review effort [1-5]: 2

#15270 [java] Remove deprecated non-w3c compliant NetworkConnection interface
  java/spotbugs-excludes.xml
  java/src/org/openqa/selenium/BUILD.bazel
  java/src/org/openqa/selenium/chromium/ChromiumDriver.java
  java/src/org/openqa/selenium/mobile/NetworkConnection.java
  java/src/org/openqa/selenium/remote/DriverCommand.java
  java/src/org/openqa/selenium/remote/codec/AbstractHttpCommandCodec.java
  java/src/org/openqa/selenium/remote/mobile/RemoteNetworkConnection.java
  java/test/org/openqa/selenium/mobile/BUILD.bazel
  java/test/org/openqa/selenium/mobile/NetworkConnectionTest.java
Labels: Review effort [1-5]: 2

#15278 Upgraded rules_cc Version 0.1.0 > 0.1.1
  MODULE.bazel
Labels: Review effort [1-5]: 1

#15279 [dotnet][bidi] Remove AsBiDiContextAsync helper to avoid disposal issue
  dotnet/src/webdriver/BiDi/WebDriver.Extensions.cs
  dotnet/test/common/BiDi/BiDiFixture.cs
Labels: Review effort [1-5]: 2

#15275 [py] document cygwin path for `send_keys`
  py/selenium/webdriver/remote/webelement.py
Labels: Review effort [1-5]: 1

#15283 [dotnet] Possibility to override underlying HttpClient/HttpClientHandler for all HTTP requests
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
Labels: Review effort 2/5

#15114 [rb][BiDi] Add set cache behaviour
  rb/lib/selenium/webdriver/bidi/network.rb
  rb/sig/lib/selenium/webdriver/bidi/network.rbs
  rb/spec/integration/selenium/webdriver/bidi/network_spec.rb
Labels: C-rb

#15292 [py] fix return type and docstring of get_downloadable_files
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/remote/remote_downloads_tests.py
Labels: Review effort 1/5

#15293 [java]: fix return type and docstring for `getDownloadableFiles`
  java/src/org/openqa/selenium/remote/RemoteWebDriver.java
  java/test/org/openqa/selenium/remote/RemoteWebDriverUnitTest.java
Labels: C-java, Review effort 1/5

#15289 [java] Refine logger initialization with correct class literal
  java/src/org/openqa/selenium/events/zeromq/BoundZmqEventBus.java
  java/src/org/openqa/selenium/events/zeromq/UnboundZmqEventBus.java
  java/test/org/openqa/selenium/grid/router/JmxTest.java
Labels: Review effort 1/5

#15248 [js][bidi]: implement bidi `getClientWindows` command in browser module
  javascript/node/selenium-webdriver/bidi/browser.js
  javascript/node/selenium-webdriver/bidi/clientWindowInfo.js
  javascript/node/selenium-webdriver/test/bidi/browser_test.js
Labels: Review effort [1-5]: 2

#15196 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort [1-5]: 1

#15296 [java][dotnet][js] Fix failing BiDi related tests
  dotnet/test/common/BiDi/Script/CallFunctionParameterTest.cs
  dotnet/test/common/BiDi/Script/EvaluateParametersTest.cs
  java/test/org/openqa/selenium/bidi/script/CallFunctionParameterTest.java
  java/test/org/openqa/selenium/bidi/script/EvaluateParametersTest.java
  javascript/node/selenium-webdriver/test/bidi/browsingcontext_inspector_test.js
Labels: Review effort 2/5

#15297 [grid] Node flag `register-shutdown-on-failure`
  java/src/org/openqa/selenium/grid/node/config/NodeFlags.java
  java/src/org/openqa/selenium/grid/node/config/NodeOptions.java
  java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java
Labels: C-grid, Review effort 2/5

#15295 [rb] Disable provide response test for Firefox
  rb/spec/integration/selenium/webdriver/action_builder_spec.rb
  rb/spec/integration/selenium/webdriver/bidi/network_spec.rb
  rb/spec/integration/selenium/webdriver/network_spec.rb
Labels: C-rb, Review effort 1/5

#15301 [dotnet][bidi] Underlying local/remote script number as double
  dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs
  dotnet/src/webdriver/BiDi/Modules/Script/RemoteValue.cs
Labels: Review effort 2/5

#15303 [dotnet] Fix dev environment to run tests on Windows/MacOS
  dotnet/paket.dependencies
  dotnet/paket.lock
  dotnet/paket.nuget.bzl
  dotnet/src/webdriver/BiDi/Modules/Script/CallFunctionCommand.cs
  dotnet/test/common/Environment/TestWebServer.cs
  dotnet/test/common/WebDriver.Common.Tests.csproj
  third_party/dotnet/devtools/NuGet.Config
Labels: Review effort 2/5

#15316 Update AUTHORS
  .mailmap
Labels: Review effort 1/5

#15315 [rb] Fix "no anonymous block parameter" in ruby 3.1
  rb/.rubocop.yml
  rb/lib/selenium/server.rb
  rb/lib/selenium/webdriver/bidi.rb
  rb/lib/selenium/webdriver/bidi/log_inspector.rb
  rb/lib/selenium/webdriver/bidi/network.rb
  rb/lib/selenium/webdriver/common/driver_extensions/has_network_interception.rb
  rb/lib/selenium/webdriver/common/network.rb
  rb/lib/selenium/webdriver/common/script.rb
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/lib/selenium/webdriver/support/guards.rb
Labels: Review effort 2/5

#15324 [dotnet] Revisit ignored intergration tests for chrome/edge
  dotnet/test/common/ClearTest.cs
  dotnet/test/common/ContentEditableTest.cs
  dotnet/test/common/CookieImplementationTest.cs
  dotnet/test/common/ElementFindingTest.cs
  dotnet/test/common/ExecutingAsyncJavascriptTest.cs
  dotnet/test/common/Interactions/BasicMouseInterfaceTest.cs
  dotnet/test/common/SvgDocumentTest.cs
  dotnet/test/common/UploadTest.cs
Labels: Review effort 2/5

#15228 [dotnet] Increment `WebDriver` towards nullability
  dotnet/src/webdriver/Command.cs
  dotnet/src/webdriver/CommandInfoRepository.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/src/webdriver/WebElementFactory.cs
Labels: Review effort [1-5]: 4

#15328 [dotnet] Do not warn when passing in null driver paths to driver service
  dotnet/src/webdriver/Chrome/ChromeDriverService.cs
  dotnet/src/webdriver/Edge/EdgeDriverService.cs
  dotnet/src/webdriver/Firefox/FirefoxDriverService.cs
  dotnet/src/webdriver/IE/InternetExplorerDriverService.cs
  dotnet/src/webdriver/Safari/SafariDriverService.cs
Labels: Review effort 2/5

#15285 [dotnet] Add `SystemClock` singleton
  dotnet/src/support/UI/PopupWindowFinder.cs
  dotnet/src/support/UI/SlowLoadableComponent{T}.cs
  dotnet/src/webdriver/Support/DefaultWait{T}.cs
  dotnet/src/webdriver/Support/SystemClock.cs
  dotnet/src/webdriver/Support/WebDriverWait.cs
  dotnet/test/support/UI/BUILD.bazel
  dotnet/test/support/UI/HandCrankClock.cs
  dotnet/test/support/UI/SlowLoadableComponentTest.cs
Labels: Review effort 2/5

#15342 [dotnet] Remove obsoleted members/types for 4.30
  dotnet/src/webdriver/ElementNotSelectableException.cs
  dotnet/src/webdriver/ElementNotVisibleException.cs
  dotnet/src/webdriver/IWebElement.cs
  dotnet/src/webdriver/Response.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/src/webdriver/WebDriverResult.cs
  dotnet/src/webdriver/WebElement.cs
Labels: Review effort 2/5

#15337 [py] expected_conditions: correct type annotation
  py/selenium/webdriver/support/expected_conditions.py
Labels: Review effort 1/5

#15268 [dotnet] Parse response before deserialization
  dotnet/src/webdriver/Response.cs
Labels: Review effort [1-5]: 3

#15257 [dotnet] Annotate nullability on most remaining types
  dotnet/src/webdriver/By.cs
  dotnet/src/webdriver/Chromium/ChromiumDriver.cs
  dotnet/src/webdriver/Cookie.cs
  dotnet/src/webdriver/DevTools/DevToolsSession.cs
  dotnet/src/webdriver/DomMutationData.cs
  dotnet/src/webdriver/IE/InternetExplorerDriverLogLevel.cs
  dotnet/src/webdriver/IE/InternetExplorerOptions.cs
  dotnet/src/webdriver/INetwork.cs
  dotnet/src/webdriver/ISupportsLogs.cs
  dotnet/src/webdriver/IWrapsElement.cs
  dotnet/src/webdriver/Internal/PortUtilities.cs
  dotnet/src/webdriver/Internal/ReturnedCookie.cs
  dotnet/src/webdriver/LogType.cs
  dotnet/src/webdriver/NetworkAuthenticationHandler.cs
  dotnet/src/webdriver/NetworkManager.cs
  dotnet/src/webdriver/NetworkRequestHandler.cs
  dotnet/src/webdriver/NetworkResponseHandler.cs
  dotnet/src/webdriver/RelativeBy.cs
  dotnet/src/webdriver/Remote/DesiredCapabilities.cs
  dotnet/src/webdriver/Remote/RemoteWebDriver.cs
Labels: Review effort [1-5]: 3

#15230 [dotnet] Annotate nullability on more of `WebElement`
  dotnet/src/webdriver/WebElement.cs
Labels: Review effort [1-5]: 2

#15255 [dotnet] Annotate nullable reference types on CDP-generated code
  dotnet/src/webdriver/DevTools/DevToolsEventData.cs
  third_party/dotnet/devtools/src/generator/CodeGen/Utility.cs
  third_party/dotnet/devtools/src/generator/ProtocolDefinition/CommandDefinition.cs
  third_party/dotnet/devtools/src/generator/Templates/command.hbs
  third_party/dotnet/devtools/src/generator/Templates/domain.hbs
  third_party/dotnet/devtools/src/generator/Templates/event.hbs
  third_party/dotnet/devtools/src/generator/Templates/type-enum.hbs
  third_party/dotnet/devtools/src/generator/Templates/type-hash.hbs
  third_party/dotnet/devtools/src/generator/Templates/type-object.hbs
Labels: Review effort [1-5]: 2

#15232 [dotnet] Simplify and nullable annotate `DriverFinder`
  dotnet/src/webdriver/Chromium/ChromiumDriver.cs
  dotnet/src/webdriver/DriverFinder.cs
  dotnet/src/webdriver/Firefox/FirefoxDriver.cs
  dotnet/src/webdriver/SeleniumManager.cs
Labels: Review effort [1-5]: 2

#15350 [dotnet] Annotate nullability on `WebDriver.SessionId`
  dotnet/src/webdriver/IHasSessionId.cs
  dotnet/src/webdriver/WebDriver.cs
Labels: Review effort 1/5
