Repository SeleniumHQ/selenium, pull requests merged in 2025-06, with the labels that each got.

#15841 [py] Fix: Mypy type annotation errors
  py/selenium/webdriver/common/bidi/storage.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/common/virtual_authenticator.py
Labels: C-py, Review effort 2/5

#15847 fixed errors in browser.py for 15697
  py/selenium/webdriver/common/bidi/browser.py
Labels: C-py, B-devtools, Review effort 2/5

#15830 [py][bidi]: implement bidi permissions module
  py/selenium/webdriver/common/bidi/permissions.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_permissions_tests.py
Labels: C-py, B-devtools, Review effort 2/5

#15835 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
  java/test/org/openqa/selenium/bidi/storage/StorageCommandsTest.java
Labels: B-build, Review effort 1/5

#15852 Caching the size/length in loops to slightly improve performance
  java/src/dev/selenium/tools/javadoc/JavadocJarMaker.java
  java/src/dev/selenium/tools/modules/ModuleGenerator.java
  java/src/org/openqa/selenium/grid/node/docker/DockerOptions.java
  java/src/org/openqa/selenium/grid/node/relay/RelayOptions.java
  java/src/org/openqa/selenium/json/JsonInput.java
  java/src/org/openqa/selenium/remote/WebElementToJsonConverter.java
  java/src/org/openqa/selenium/remote/codec/AbstractHttpCommandCodec.java
  java/src/org/openqa/selenium/remote/http/Route.java
  java/src/org/openqa/selenium/remote/http/UrlTemplate.java
Labels: B-grid, C-java, Review effort 2/5

#15865 [py] Re-apply #15862
  py/selenium/common/exceptions.py
Labels: Review effort 1/5

#15863 [py] fix driver_element_finding_tests.py
  py/test/selenium/webdriver/common/driver_element_finding_tests.py
Labels: C-py, Review effort 1/5

#15858 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15867 [refactor] use constant `CapabilityType.ENABLE_DOWNLOADS` instead of hard-coded value `se:downloadsEnabled`
  java/src/org/openqa/selenium/grid/data/DefaultSlotMatcher.java
  java/src/org/openqa/selenium/grid/node/config/NodeOptions.java
  java/src/org/openqa/selenium/grid/node/local/LocalNode.java
  java/test/org/openqa/selenium/chrome/ChromeOptionsTest.java
  java/test/org/openqa/selenium/grid/data/DefaultSlotMatcherTest.java
  java/test/org/openqa/selenium/grid/node/NodeTest.java
  java/test/org/openqa/selenium/grid/node/config/NodeOptionsTest.java
  java/test/org/openqa/selenium/grid/router/RemoteWebDriverDownloadTest.java
  java/test/org/openqa/selenium/grid/router/StressTest.java
  java/test/org/openqa/selenium/remote/RemoteWebDriverUnitTest.java
Labels: Review effort 2/5

#15495 [py] Refactored `conftest.py` in a more object oriented design approach
  py/conftest.py
Labels: Review effort 3/5

#15873 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15882 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5

#15881 [py] do not use global var for devtools, allows multiple devtools to run
  py/conftest.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/devtools_tests.py
Labels: C-py, Review effort 3/5

#15886 [py] Remove publication of typing coverage in CI
  .github/workflows/ci-python.yml
  py/tox.ini
Labels: C-py, B-build, Review effort 2/5

#15890 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15891 [py] Fix possible TypeError in expected conditions
  py/selenium/webdriver/support/expected_conditions.py
Labels: C-py, B-support, Review effort 2/5

#15840 [py] Refactored `server.py` in a more pythonic approach.
  py/selenium/webdriver/remote/server.py
Labels: C-py, Review effort 2/5

#15889 [py] Add properties (getter/setter) for service args
  py/selenium/webdriver/chrome/service.py
  py/selenium/webdriver/chromium/service.py
  py/selenium/webdriver/common/service.py
  py/selenium/webdriver/edge/service.py
  py/selenium/webdriver/firefox/service.py
  py/selenium/webdriver/ie/service.py
  py/selenium/webdriver/safari/service.py
  py/selenium/webdriver/webkitgtk/service.py
  py/selenium/webdriver/wpewebkit/service.py
Labels: C-py, Review effort 3/5

#15887 [py] Fix error handler check_response
  py/selenium/webdriver/remote/errorhandler.py
  py/test/unit/selenium/webdriver/remote/error_handler_tests.py
Labels: C-py, Review effort 3/5

#15903 [java] Fix code formatting
  java/src/org/openqa/selenium/bidi/browsingcontext/BrowsingContext.java
  java/src/org/openqa/selenium/bidi/browsingcontext/BrowsingContextInfo.java
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextTest.java
Labels: C-java, B-devtools, Review effort 1/5

#15880 [py][bidi]: add BiDi script module commands
  py/selenium/webdriver/common/bidi/script.py
  py/test/selenium/webdriver/common/bidi_script_tests.py
Labels: C-py, B-devtools, Review effort 4/5

#15907 [java] deprecate FtpProxy
  java/src/org/openqa/selenium/Proxy.java
Labels: C-java, Review effort 2/5

#15899 [rb] add guard for browser version
  common/repositories.bzl
  rb/spec/integration/selenium/webdriver/fedcm_spec.rb
  rb/spec/integration/selenium/webdriver/network_spec.rb
  rb/spec/integration/selenium/webdriver/spec_helper.rb
  rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb
Labels: C-rb, Review effort 2/5

#15914 [dotnet] [bidi] Adjust proxy configuration for new sessions
  dotnet/src/webdriver/BiDi/Session/ProxyConfiguration.cs
Labels: C-dotnet, Review effort 2/5

#15909 [py] Bump requirements for packaging and dev
  .github/workflows/ci-python.yml
  py/pyproject.toml
  py/requirements.txt
  py/requirements_lock.txt
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py, B-build, Review effort 2/5

#15906 [py] Deprecate support for FTP proxies
  py/selenium/webdriver/common/proxy.py
  py/test/selenium/webdriver/common/proxy_tests.py
Labels: C-py, Review effort 2/5

#15918 [py] Skip devtools when generating Python API docs
  py/docs/source/index.rst
  py/generate_api_module_listing.py
Labels: C-py, Review effort 2/5

#15917 [py] Type hint cleanup
  py/selenium/webdriver/chrome/service.py
  py/selenium/webdriver/chromium/service.py
  py/selenium/webdriver/common/bidi/script.py
  py/selenium/webdriver/edge/service.py
  py/selenium/webdriver/firefox/service.py
  py/selenium/webdriver/ie/service.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/safari/service.py
  py/selenium/webdriver/webkitgtk/service.py
  py/selenium/webdriver/wpewebkit/service.py
Labels: C-py, B-devtools, Review effort 2/5

#15895 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5

#15921 Revert "[grid] Add config `blocked-routes` and specific `blocked-delete-session` in Router"
  java/src/org/openqa/selenium/grid/commands/Hub.java
  java/src/org/openqa/selenium/grid/commands/Standalone.java
  java/src/org/openqa/selenium/grid/router/httpd/BlockedRoute.java
  java/src/org/openqa/selenium/grid/router/httpd/BlockedRoutesFilter.java
  java/src/org/openqa/selenium/grid/router/httpd/RouterFlags.java
  java/src/org/openqa/selenium/grid/router/httpd/RouterOptions.java
  java/src/org/openqa/selenium/grid/router/httpd/RouterServer.java
  java/test/org/openqa/selenium/grid/router/httpd/BUILD.bazel
  java/test/org/openqa/selenium/grid/router/httpd/BlockedRouteTest.java
  java/test/org/openqa/selenium/grid/router/httpd/BlockedRoutesFilterTest.java
  java/test/org/openqa/selenium/grid/router/httpd/RouterOptionsTest.java
Labels: B-grid, C-java, B-build, Review effort 2/5

#15929 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5

#15926 [rb] Feat 15905/deprecate ftp proxy
  rb/lib/selenium/webdriver/common/proxy.rb
Labels: C-rb, Review effort 1/5

#15934 [java][refactor] Remove Empty Space in CommandPayload
  java/src/org/openqa/selenium/remote/CommandPayload.java
Labels: C-java, Review effort 1/5

#15910 [FEAT] Add macOS-specific keys (OPTION, FN) to Keys enum for improved…
  java/src/org/openqa/selenium/Keys.java
Labels: C-java, Review effort 2/5

#15927 [py] Adding Note to enable_webextensions() regarding CDP (plus gen docstring updates)
  py/selenium/webdriver/chromium/options.py
  py/selenium/webdriver/remote/webdriver.py
Labels: C-py, Review effort 2/5

#15808 [grid] Session can be deleted via Grid UI
  java/src/org/openqa/selenium/grid/node/config/NodeFlags.java
  java/src/org/openqa/selenium/grid/node/config/NodeOptions.java
  java/test/org/openqa/selenium/grid/node/config/NodeOptionsTest.java
  javascript/grid-ui/src/components/RunningSessions/RunningSessions.tsx
  javascript/grid-ui/src/tests/components/RunningSessions.test.tsx
Labels: B-grid, Review effort 2/5

#15821 Remove license info from readme
  README.md
Labels: Review effort 1/5

#15653 [java] Use Environment variable to set driver location
  MODULE.bazel
  java/maven_install.json
  java/src/org/openqa/selenium/chrome/ChromeDriverService.java
  java/src/org/openqa/selenium/edge/EdgeDriverService.java
  java/src/org/openqa/selenium/firefox/GeckoDriverService.java
  java/src/org/openqa/selenium/ie/InternetExplorerDriverService.java
  java/src/org/openqa/selenium/remote/service/DriverFinder.java
  java/src/org/openqa/selenium/remote/service/DriverService.java
  java/src/org/openqa/selenium/safari/SafariDriverService.java
  java/test/org/openqa/selenium/remote/service/BUILD.bazel
  java/test/org/openqa/selenium/remote/service/DriverFinderTest.java
  rust/Cargo.Bazel.lock
Labels: C-java, B-build, C-rust, Review effort 2/5, B-manager

#15953 [dotnet][rb][java][js][py] Automated Browser Version Update
  .skipped-tests
  common/repositories.bzl
  java/test/org/openqa/selenium/bidi/browsingcontext/BrowsingContextInspectorTest.java
  java/test/org/openqa/selenium/federatedcredentialmanagement/FederatedCredentialManagementTest.java
Labels: B-build, Review effort 2/5

#15942 [py] Return HTTP response reason when remote connection error occurs
  py/selenium/webdriver/remote/remote_connection.py
Labels: C-py, Review effort 2/5

#15968 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5, Possible security concern

#15959 [rb] Add macOS key mappings for Options and Function keys
  rb/lib/selenium/webdriver/common/keys.rb
Labels: C-rb, Review effort 1/5

#15958 [build] Prepare for release of Selenium 4.34.0
  .github/ISSUE_TEMPLATE/bug-report.yml
  AUTHORS
  MODULE.bazel
  Rakefile
  common/devtools/chromium/v138/BUILD.bazel
  common/devtools/chromium/v138/browser_protocol.pdl
  common/devtools/chromium/v138/js_protocol.pdl
  common/selenium_manager.bzl
  dotnet/CHANGELOG
  dotnet/selenium-dotnet-version.bzl
  dotnet/src/webdriver/DevTools/DevToolsDomains.cs
  dotnet/src/webdriver/DevTools/v138/V138Domains.cs
  dotnet/src/webdriver/DevTools/v138/V138JavaScript.cs
  dotnet/src/webdriver/DevTools/v138/V138Log.cs
  dotnet/src/webdriver/DevTools/v138/V138Network.cs
  dotnet/src/webdriver/DevTools/v138/V138Target.cs
  dotnet/test/common/CustomDriverConfigs/StableChannelChromeDriver.cs
  dotnet/test/common/DevTools/DevToolsConsoleTest.cs
  dotnet/test/common/DevTools/DevToolsLogTest.cs
  dotnet/test/common/DevTools/DevToolsNetworkTest.cs
  dotnet/test/common/DevTools/DevToolsPerformanceTest.cs
  dotnet/test/common/DevTools/DevToolsProfilerTest.cs
  dotnet/test/common/DevTools/DevToolsSecurityTest.cs
  dotnet/test/common/DevTools/DevToolsTabsTest.cs
  dotnet/test/common/DevTools/DevToolsTargetTest.cs
  java/CHANGELOG
  java/maven_install.json
  java/src/org/openqa/selenium/bidi/script/RealmInfo.java
  java/src/org/openqa/selenium/devtools/v138/BUILD.bazel
  java/src/org/openqa/selenium/devtools/v138/v138CdpInfo.java
  java/src/org/openqa/selenium/devtools/v138/v138Domains.java
  java/src/org/openqa/selenium/devtools/v138/v138Events.java
  java/src/org/openqa/selenium/devtools/v138/v138Javascript.java
  java/src/org/openqa/selenium/devtools/v138/v138Log.java
  java/src/org/openqa/selenium/devtools/v138/v138Network.java
  java/src/org/openqa/selenium/devtools/v138/v138Target.java
  java/src/org/openqa/selenium/devtools/versions.bzl
  java/version.bzl
  javascript/selenium-webdriver/BUILD.bazel
  javascript/selenium-webdriver/CHANGES.md
  javascript/selenium-webdriver/package.json
  py/BUILD.bazel
  py/CHANGES
  py/docs/source/conf.py
  py/pyproject.toml
  py/selenium/__init__.py
  py/selenium/webdriver/__init__.py
  rb/.rubocop.yml
  rb/CHANGES
  rb/Gemfile.lock
  rb/lib/selenium/devtools/BUILD.bazel
  rb/lib/selenium/devtools/version.rb
  rb/lib/selenium/webdriver/bidi/network/url_pattern.rb
  rb/lib/selenium/webdriver/version.rb
  rust/BUILD.bazel
  rust/CHANGELOG.md
  rust/Cargo.Bazel.lock
  rust/Cargo.lock
  rust/Cargo.toml
  scripts/update_copyright.py
Labels: C-py, C-rb, C-dotnet, C-java, C-nodejs, B-build, B-devtools, C-rust, B-manager, C-build

#15978 [dotnet] [bidi] Get tree command returns GetTreeResult object
  dotnet/src/webdriver/BiDi/Browser/GetClientWindowsCommand.cs
  dotnet/src/webdriver/BiDi/Browser/GetUserContextsCommand.cs
  dotnet/src/webdriver/BiDi/BrowsingContext/BrowsingContext.cs
  dotnet/src/webdriver/BiDi/BrowsingContext/BrowsingContextModule.cs
  dotnet/src/webdriver/BiDi/BrowsingContext/GetTreeCommand.cs
  dotnet/src/webdriver/BiDi/BrowsingContext/LocateNodesCommand.cs
  dotnet/src/webdriver/BiDi/Communication/Broker.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Enumerable/GetTreeResultConverter.cs
  dotnet/src/webdriver/BiDi/Storage/GetCookiesCommand.cs
Labels: C-dotnet, Review effort 3/5

#15977 [py] Bump dependencies for building distribution wheel
  py/BUILD.bazel
Labels: C-py, B-build, Review effort 1/5

#15980 bump zip version 2.6.1 -> 4.2.0
  rust/Cargo.toml
Labels: C-rust, Review effort 2/5, B-manager

#15981 [py][bidi]: add note for `enable_webextensions = False`
  py/selenium/webdriver/chromium/options.py
Labels: C-py, Review effort 1/5
