Repository SeleniumHQ/selenium, pull requests merged in 2025-03, with the labels that each got.

#15351 [dotnet] Enable nullability on remote file download APIs
  dotnet/src/webdriver/IHasDownloads.cs
  dotnet/src/webdriver/Remote/RemoteWebDriver.cs
Labels: Review effort 2/5

#15352 [dotnet] Annotate nullability on elements and `WebDriver`
  dotnet/src/support/Events/EventFiringWebDriver.cs
  dotnet/src/webdriver/By.cs
  dotnet/src/webdriver/Chromium/ChromiumDriver.cs
  dotnet/src/webdriver/Command.cs
  dotnet/src/webdriver/CookieJar.cs
  dotnet/src/webdriver/Firefox/FirefoxDriver.cs
  dotnet/src/webdriver/Firefox/FirefoxProfile.cs
  dotnet/src/webdriver/IJavascriptExecutor.cs
  dotnet/src/webdriver/IWebDriver.cs
  dotnet/src/webdriver/IWebElement.cs
  dotnet/src/webdriver/RelativeBy.cs
  dotnet/src/webdriver/ShadowRoot.cs
  dotnet/src/webdriver/TargetLocator.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/src/webdriver/WebElement.cs
  dotnet/src/webdriver/WebElementFactory.cs
Labels: Review effort 3/5

#15353 [dotnet] Annotate nullability on capabilities types
  dotnet/src/webdriver/IHasCapabilities.cs
  dotnet/src/webdriver/IWritableCapabilities.cs
  dotnet/src/webdriver/Remote/DesiredCapabilities.cs
  dotnet/src/webdriver/Remote/ReadOnlyDesiredCapabilities.cs
  dotnet/src/webdriver/Remote/RemoteSessionSettings.cs
Labels: Review effort 2/5

#15291 Add support for handling user prompt
  rb/lib/selenium/webdriver/bidi/browsing_context.rb
  rb/sig/lib/selenium/webdriver/bidi/browsing_context.rbs
  rb/spec/integration/selenium/webdriver/bidi/browsing_context_spec.rb
Labels: C-rb, Review effort 2/5

#15302 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort 1/5

#15365 [rb][BiDi] Add Browser context activate command
  rb/lib/selenium/webdriver/bidi/browsing_context.rb
  rb/sig/lib/selenium/webdriver/bidi/browsing_context.rbs
  rb/spec/integration/selenium/webdriver/bidi/browsing_context_spec.rb
Labels: Review effort 2/5

#15348 [grid] Add traces for event stop session in Node
  java/src/org/openqa/selenium/grid/node/local/LocalNode.java
Labels: C-grid, Review effort 3/5

#15381 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort 1/5

#15217 [dotnet] Trim away CDP when publishing AOT apps
  dotnet/src/webdriver/WebDriver.cs
Labels: Review effort [1-5]: 2

#15386 modified delete cookie added code and test
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/spec/integration/selenium/webdriver/manager_spec.rb
Labels: Review effort 1/5

#15366 [rust] Selenium Manager support nightly Grid (#13384)
  rust/src/grid.rs
  rust/src/lib.rs
  rust/tests/grid_tests.rs
Labels: C-rust, Review effort 2/5

#15247 Issue 12549 fix atoms generation lowdash
  javascript/private/fragment.bzl
Labels: Review effort [1-5]: 2

#15405 [js][bidi]: fix chrome and firefox test for CI RBE
  javascript/node/selenium-webdriver/test/bidi/browsingcontext_inspector_test.js
Labels: C-nodejs, Review effort 1/5

#15410 [py] Ignore devtools during linting
  py/pyproject.toml
  py/tox.ini
Labels: Review effort 1/5

#15416 [rb] Add target type param to devtools
  common/src/web/service-worker.js
  common/src/web/service_worker.html
  rb/lib/selenium/webdriver/common/driver.rb
  rb/lib/selenium/webdriver/common/driver_extensions/has_devtools.rb
  rb/lib/selenium/webdriver/devtools.rb
  rb/spec/integration/selenium/webdriver/devtools_spec.rb
Labels: Review effort 2/5

#15423 [dotnet] [bidi] Encapsulate transport inside `Broker`
  dotnet/src/webdriver/BiDi/BiDi.cs
  dotnet/src/webdriver/BiDi/Communication/Broker.cs
Labels: Review effort 2/5

#15395 [dotnet] [bidi] Align `Scipt.LocalValue.Map` with spec, enable negative zero
  dotnet/src/webdriver/BiDi/Communication/Broker.cs
  dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs
  dotnet/src/webdriver/BiDi/Modules/Script/RemoteValue.cs
  dotnet/test/common/BiDi/Script/CallFunctionLocalValueTest.cs
  dotnet/test/common/BiDi/Script/CallFunctionRemoteValueTest.cs
Labels: Review effort 2/5

#15428 [dotnet] [bidi] Make `LocalValue` types not nested
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Modules/Script/AddPreloadScriptCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs
  dotnet/test/common/BiDi/Script/CallFunctionLocalValueTest.cs
  dotnet/test/common/BiDi/Script/CallFunctionParameterTest.cs
  dotnet/test/common/BiDi/Script/ScriptCommandsTest.cs
  dotnet/test/common/BiDi/Script/ScriptEventsTest.cs
Labels: Review effort 2/5

#15426 [dotnet] [bidi] Migrate RemoteValue to separate types
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Enumerable/LocateNodesResultConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/RemoteValueConverter.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/LocateNodesCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/NodeProperties.cs
  dotnet/src/webdriver/BiDi/Modules/Script/RemoteValue.cs
  dotnet/test/common/BiDi/Log/LogTest.cs
  dotnet/test/common/BiDi/Script/CallFunctionParameterTest.cs
  dotnet/test/common/BiDi/Script/CallFunctionRemoteValueTest.cs
  dotnet/test/common/BiDi/Script/EvaluateParametersTest.cs
  dotnet/test/common/BiDi/Script/ScriptCommandsTest.cs
Labels: Review effort 3/5

#15413 [py] Fix code formatting selenium_manager_tests.py
  py/test/selenium/webdriver/common/selenium_manager_tests.py
Labels: Review effort 1/5

#15415 [py] fix test discovery for pytest
  py/pyproject.toml
Labels: Review effort 1/5

#15419 [py] Rename credentials test file so it gets run
  py/test/unit/selenium/webdriver/virtual_authenticator/credentials_tests.py
Labels: Review effort 2/5

#15424 Update Python development instructions in README.md
  README.md
Labels: Review effort 1/5

#15435 [dotnet] [bidi] Make `PartitionDescriptor` as not nested
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextStorageModule.cs
  dotnet/src/webdriver/BiDi/Modules/Storage/GetCookiesCommand.cs
Labels: Review effort 2/5

#15434 [dotnet] [bidi] Make `UrlPattern` as not nested
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Modules/Network/UrlPattern.cs
  dotnet/test/common/BiDi/Network/NetworkTest.cs
Labels: Review effort 1/5

#15432 [dotnet] [bidi] Make `LogEntry` as not nested
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/LogEntryConverter.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextLogModule.cs
  dotnet/src/webdriver/BiDi/Modules/Log/LogEntry.cs
  dotnet/src/webdriver/BiDi/Modules/Log/LogModule.cs
  dotnet/test/common/BiDi/Log/LogTest.cs
  dotnet/test/common/BiDi/Script/ScriptCommandsTest.cs
Labels: Review effort 2/5

#15433 [dotnet] [bidi] Make `BytesValue` not nested
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Modules/Network/BytesValue.cs
  dotnet/test/common/BiDi/Network/NetworkEventsTest.cs
  dotnet/test/common/BiDi/Storage/StorageTest.cs
Labels: Review effort 2/5

#15438 [dotnet] [bidi] Make `ProxyConfiguration` as not nested
  dotnet/src/webdriver/BiDi/Modules/Session/ProxyConfiguration.cs
Labels: Review effort 1/5

#15429 [dotnet] [bidi] Make `Locator` types as not nested
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/Locator.cs
  dotnet/test/common/BiDi/BrowsingContext/BrowsingContextTest.cs
  dotnet/test/common/BiDi/Input/CombinedInputActionsTest.cs
  dotnet/test/common/BiDi/Input/SetFilesTest.cs
Labels: Review effort 2/5

#15431 [dotnet] [bidi] Make `ClipRectangle` as not nested
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/CaptureScreenshotCommand.cs
  dotnet/test/common/BiDi/BrowsingContext/BrowsingContextTest.cs
Labels: Review effort 2/5

#15444 [dotnet] [bidi] Make `RealmInfo` as not nested
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/RealmInfoConverter.cs
  dotnet/src/webdriver/BiDi/Modules/Script/RealmInfo.cs
  dotnet/test/common/BiDi/Script/ScriptCommandsTest.cs
  dotnet/test/common/BiDi/Script/ScriptEventsTest.cs
Labels: Review effort 2/5

#15445 [dotnet] [bidi] Make input `Origin` as not nested
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/InputOriginConverter.cs
  dotnet/src/webdriver/BiDi/Modules/Input/Origin.cs
Labels: Review effort 1/5

#15402 [py]: use `By` class attributes instead of strings
  py/selenium/webdriver/remote/locator_converter.py
Labels: C-py, Review effort 1/5

#15403 [java][bidi]: use `getBidiSessionStatus` method in tests
  java/test/org/openqa/selenium/bidi/BiDiSessionCleanUpTest.java
  java/test/org/openqa/selenium/bidi/BiDiSessionTest.java
  java/test/org/openqa/selenium/grid/router/RemoteWebDriverBiDiTest.java
Labels: C-java, Review effort [1-5]: 1

#15460 [ci] Update remote-image Dockerfile
  common/remote-build/BUILD.bazel
  scripts/dev-image/Dockerfile
  scripts/remote-image/Dockerfile
  scripts/remote-image/create-cc-toolchain-within-image.sh
Labels: Review effort 2/5

#15411 [py] fix doc for find_elements
  py/selenium/webdriver/remote/shadowroot.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/webelement.py
Labels: Review effort 1/5

#15453 [py] improve socket resource management with proper shutdown sequence
  py/selenium/webdriver/common/utils.py
Labels: Review effort 1/5

#15459 [py] Update Python documentation (modernization)
  py/docs/README.rst
  py/docs/requirements.txt
  py/docs/selenium_logo_small.png
  py/docs/source/conf.py
  py/docs/source/index.rst
  py/tox.ini
Labels: Review effort 2/5

#15466 [py] Fix docstring issues that sphinx complains about
  py/docs/source/index.rst
  py/selenium/webdriver/common/actions/action_builder.py
  py/selenium/webdriver/common/by.py
  py/selenium/webdriver/common/options.py
  py/selenium/webdriver/common/print_page_options.py
  py/selenium/webdriver/common/proxy.py
  py/selenium/webdriver/common/timeouts.py
  py/selenium/webdriver/ie/options.py
  py/selenium/webdriver/remote/shadowroot.py
  py/selenium/webdriver/remote/webdriver.py
  py/selenium/webdriver/remote/webelement.py
  py/selenium/webdriver/safari/options.py
  py/selenium/webdriver/support/expected_conditions.py
  py/selenium/webdriver/support/relative_locator.py
  py/selenium/webdriver/support/wait.py
Labels: Review effort 2/5

#15482 [rb] Fix BiDi tests errors
  rb/spec/integration/selenium/webdriver/bidi/browsing_context_spec.rb
  rb/spec/integration/selenium/webdriver/bidi/network_spec.rb
Labels: Review effort 2/5

#15183 [py] service: only shutdown if process not terminated
  py/selenium/webdriver/common/service.py
Labels: C-py, Review effort [1-5]: 1

#15485 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: Review effort 2/5

#15493 [dotnet] [bidi] Decouple EvaluateResult in Script module
  dotnet/src/webdriver/BiDi/Communication/Json/BiDiJsonSerializerContext.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/Polymorphic/EvaluateResultConverter.cs
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/BrowsingContextScriptModule.cs
  dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs
  dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs
  dotnet/src/webdriver/BiDi/Modules/Script/ScriptModule.cs
Labels: Review effort 2/5

#15491 [dotnet] [bidi] Decouple AuthCredentials in Network module
  dotnet/src/webdriver/BiDi/Modules/Network/AuthCredentials.cs
  dotnet/test/common/BiDi/Network/NetworkTest.cs
Labels: Review effort 1/5

#15490 [dotnet] [bidi] Decouple WindowProxyProperties in Script module
  dotnet/src/webdriver/BiDi/Modules/Script/RemoteValue.cs
  dotnet/src/webdriver/BiDi/Modules/Script/WindowProxyProperties.cs
Labels: Review effort 1/5

#15488 [dotnet] [bidi] Decouple ScreenshotOrigin in BrowsingContext module
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/CaptureScreenshotCommand.cs
  dotnet/test/common/BiDi/BrowsingContext/BrowsingContextTest.cs
Labels: Review effort 1/5

#15487 [dotnet] [bidi] Decouple nested types in Locator
  dotnet/src/webdriver/BiDi/Modules/BrowsingContext/Locator.cs
Labels: Review effort 2/5

#15496 [bazel] Rename `remote` config to `rbe`
  .bazelrc
  .bazelrc.remote
  CONTRIBUTING.md
  Rakefile
  scripts/github-actions/ci-build.sh
Labels: Review effort 2/5

#15455 [js] add ErrorCode for `DetachedShadowRootError`
  javascript/node/selenium-webdriver/lib/error.js
  javascript/node/selenium-webdriver/test/lib/error_test.js
Labels: C-nodejs, Review effort 1/5

#15379 [dotnet] Fix null warnings in `RelativeBy` by sealing the type
  dotnet/src/support/Extensions/WebDriverExtensions.cs
  dotnet/src/support/UI/SelectElement.cs
  dotnet/src/webdriver/RelativeBy.cs
Labels: Review effort 2/5

#15119 [java] Add nullness for AppCacheStatus, Credential, and Either
  java/src/org/openqa/selenium/html5/AppCacheStatus.java
  java/src/org/openqa/selenium/internal/Either.java
  java/src/org/openqa/selenium/virtualauthenticator/Credential.java
Labels: Review effort [1-5]: 2

#15118 [java] Add nullness for interactions
  java/src/org/openqa/selenium/interactions/Coordinates.java
  java/src/org/openqa/selenium/interactions/Interactive.java
  java/src/org/openqa/selenium/interactions/SourceType.java
Labels: Review effort [1-5]: 1

#15519 [rb] Allow symbols again to be passed on delete_cookie
  rb/lib/selenium/webdriver/remote/bridge.rb
  rb/spec/integration/selenium/webdriver/manager_spec.rb
Labels: C-rb, Review effort 2/5

#15441 [dotnet] [bidi] Simplify conversion to `LocalValue`
  dotnet/src/webdriver/BiDi/BiDiException.cs
  dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs
  dotnet/test/common/BiDi/Script/CallFunctionLocalValueTest.cs
  dotnet/test/common/BiDi/Script/LocalValueConversionTests.cs
Labels: Review effort 3/5

#15516 Enable rust tests in RBE builds
  .skipped-tests
  common/remote-build/BUILD.bazel
  rust/Cargo.toml
  rust/tests/BUILD.bazel
  rust/tests/common.rs
Labels: Review effort 1/5

#15506 [dotnet] Address lingering AOT warnings
  dotnet/src/webdriver/Chromium/ChromiumDriver.cs
  dotnet/src/webdriver/Command.cs
  dotnet/src/webdriver/Internal/FileUtilities.cs
Labels: Review effort 2/5

#15534 [dotnet] [bidi] Unignore GetClientWindows test for chromium
  dotnet/test/common/BiDi/Browser/BrowserTest.cs
Labels: Review effort 1/5

#15233 [dotnet] Unify protected and internal Execute methods
  dotnet/src/webdriver/Alert.cs
  dotnet/src/webdriver/CookieJar.cs
  dotnet/src/webdriver/HttpCommandInfo.cs
  dotnet/src/webdriver/Logs.cs
  dotnet/src/webdriver/Navigator.cs
  dotnet/src/webdriver/ShadowRoot.cs
  dotnet/src/webdriver/TargetLocator.cs
  dotnet/src/webdriver/Timeouts.cs
  dotnet/src/webdriver/WebDriver.cs
  dotnet/src/webdriver/WebElement.cs
  dotnet/src/webdriver/Window.cs
Labels: Review effort [1-5]: 2

#15540 [py] Remove unused mocker arg in chrome options test
  py/test/unit/selenium/webdriver/chrome/chrome_options_tests.py
Labels: Review effort 1/5
