Repository SeleniumHQ/selenium, pull requests merged in 2025-08, with the labels that each got.

#16121 [dotnet] Remove long awaited obsolete members
  dotnet/src/webdriver/Chromium/ChromiumDriver.cs
  dotnet/src/webdriver/Chromium/ChromiumDriverService.cs
  dotnet/src/webdriver/DevTools/DevToolsSession.cs
  dotnet/src/webdriver/DevTools/IDevTools.cs
  dotnet/src/webdriver/Edge/EdgeDriverService.cs
  dotnet/src/webdriver/Firefox/FirefoxOptions.cs
  dotnet/src/webdriver/Interactions/ActionSequence.cs
  dotnet/src/webdriver/Internal/Logging/ConsoleLogHandler.cs
  dotnet/src/webdriver/Remote/RemoteWebDriver.cs
  dotnet/src/webdriver/UserAgent.cs
Labels: C-dotnet, Review effort 2/5

#16114 [py] Fix license in package metadata and include copyright notices
  .gitignore
  py/BUILD.bazel
  py/LICENSE
  py/NOTICE
  py/pyproject.toml
Labels: C-py, B-build, Review effort 2/5

#16126 [dotnet] Change default internal log level to Warn
  dotnet/src/webdriver/Internal/Logging/LogContextManager.cs
Labels: C-dotnet, Review effort 2/5

#16131 [dotnet] Truncate log and set profile root in Firefox (GeckoDriver)
  dotnet/src/webdriver/Firefox/FirefoxDriverService.cs
Labels: C-dotnet, Review effort 2/5, Possible security concern

#16129 [dotnet][py][java][js]: add `default` as a value for SameSite
  dotnet/src/webdriver/BiDi/Network/Cookie.cs
  java/src/org/openqa/selenium/bidi/network/Cookie.java
  javascript/selenium-webdriver/bidi/networkTypes.js
  py/selenium/webdriver/common/bidi/storage.py
Labels: C-py, C-dotnet, C-java, C-nodejs, Review effort 2/5

#16137 [js]: skip fedcm tests until Chrome 140
  javascript/selenium-webdriver/test/fedcm/fedcm_test.js
Labels: C-nodejs

#16139 [dotnet] Removing unneeded verification. Done at compile time.
  dotnet/src/webdriver/Chromium/ChromiumDriverService.cs
Labels: C-dotnet, Review effort 2/5

#16064 [dotnet][rb][java][js][py] Automated Browser Version Update
  .github/workflows/ci-java.yml
  .skipped-tests
  common/repositories.bzl
  java/test/org/openqa/selenium/HistoryNavigationTest.java
  py/test/selenium/webdriver/common/w3c_interaction_tests.py
Labels: B-build, Review effort 2/5

#16146 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5, Possible security concern

#16097 [dotnet] Enabling drivers to set log to console.
  dotnet/src/webdriver/DriverProcessStartedEventArgs.cs
  dotnet/src/webdriver/DriverService.cs
  dotnet/src/webdriver/Firefox/FirefoxDriverService.cs
  dotnet/test/firefox/FirefoxDriverServiceTest.cs
Labels: C-dotnet, Review effort 2/5

#16150 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5

#16015 [rb] Remove local storage and session storage interfaces and methods
  rb/sig/interfaces/local_storage.rbs
  rb/sig/lib/selenium/webdriver/common/html5/local_storage.rbs
  rb/sig/lib/selenium/webdriver/common/html5/session_storage.rbs
  rb/sig/lib/selenium/webdriver/common/html5/shared_web_storage.rbs
  rb/sig/lib/selenium/webdriver/remote/bridge.rbs
Labels: C-rb, Review effort 2/5

#16157 [py] Use native dict for type annotation
  py/selenium/webdriver/common/bidi/session.py
Labels: C-py, B-devtools, Review effort 1/5

#16136 [py] Loosen dependency specifier for urllib3 in packaging configuration
  py/BUILD.bazel
  py/pyproject.toml
Labels: C-py, B-build, Review effort 1/5

#16140 [py]: fix WebView2 and target issues related to CDP and BiDi
  py/selenium/webdriver/remote/webdriver.py
Labels: C-py, Review effort 3/5

#16151 [grid] Restructuring classes have stateful data and improve Node health checks in LocalDistributor
  java/src/org/openqa/selenium/grid/distributor/GridModel.java
  java/src/org/openqa/selenium/grid/distributor/NodeRegistry.java
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/src/org/openqa/selenium/grid/distributor/local/LocalGridModel.java
  java/src/org/openqa/selenium/grid/distributor/local/LocalNodeRegistry.java
Labels: B-grid, C-java, Review effort 4/5

#16049 [py][bidi]: Implement low-level API for Input BiDi module
  py/selenium/webdriver/common/bidi/input.py
  py/selenium/webdriver/common/bidi/script.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_input_tests.py
Labels: C-py, B-devtools, Review effort 4/5, Possible security concern

#16155 [grid] Reduce redundant logs of find slots and retry queue requests by the Distributor
  java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java
  java/src/org/openqa/selenium/grid/distributor/local/LocalNodeRegistry.java
  java/src/org/openqa/selenium/grid/sessionqueue/local/LocalNewSessionQueue.java
  java/test/org/openqa/selenium/grid/distributor/local/LocalDistributorTest.java
Labels: B-grid, C-java, Review effort 3/5

#16169 [docs] Update issue label in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Review effort 1/5

#16170 [py][docs]: update dead API docs link to API reference in `index.rst`
  py/docs/source/index.rst
Labels: C-py, Review effort 1/5

#16175 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5

#16187 [py] Update docstring and comments in keys.py
  py/selenium/webdriver/common/keys.py
Labels: C-py, Review effort 1/5

#16190 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5

#16195 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 1/5, Possible security concern

#15371 [rb][BiDi] Create browser module, added user context related methods
  rb/lib/selenium/webdriver/bidi.rb
  rb/lib/selenium/webdriver/bidi/browser.rb
  rb/lib/selenium/webdriver/common/manager.rb
  rb/sig/lib/selenium/webdriver/bidi/browser.rbs
  rb/spec/integration/selenium/webdriver/bidi/browser_spec.rb
Labels: C-rb, Review effort 2/5

#16163 [grid] Improve readTimeout in handle session between Router and Node
  java/src/org/openqa/selenium/grid/node/Node.java
  java/src/org/openqa/selenium/grid/router/HandleSession.java
Labels: B-grid, C-java, Review effort 2/5

#16174 [py] Fix type annotation error and raise clearer error message
  py/selenium/webdriver/common/virtual_authenticator.py
  py/selenium/webdriver/remote/errorhandler.py
Labels: C-py, Review effort 2/5

#16213 [dotnet][rb][java][js][py] Automated Browser Version Update
  .skipped-tests
  common/repositories.bzl
  java/test/org/openqa/selenium/bidi/storage/StorageCommandsTest.java
  rb/spec/integration/selenium/webdriver/manager_spec.rb
Labels: B-build, Review effort 2/5

#16220 [java] Unifying select class
  .idea/misc.xml
  java/src/org/openqa/selenium/support/ui/Select.java
  java/test/org/openqa/selenium/support/ui/SelectElementTest.java
Labels: C-java, B-support, Review effort 2/5

#16235 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5, Possible security concern

#16243 Revert "[py] Update dependency cryptography to v45.0.6"
  py/requirements.txt
  py/requirements_lock.txt
Labels: C-py

#16258 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5

#16218 [dotnet] [bidi] Adjust cookie expiry type according spec (unix seconds)
  dotnet/src/webdriver/BiDi/Communication/Broker.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/DateTimeOffsetConverter.cs
  dotnet/src/webdriver/BiDi/Communication/Json/Converters/TimeSpanConverter.cs
  dotnet/src/webdriver/BiDi/Network/Cookie.cs
  dotnet/src/webdriver/BiDi/Storage/SetCookieCommand.cs
  dotnet/test/common/BiDi/Storage/StorageTest.cs
Labels: C-dotnet, Review effort 2/5

#16250 [py] Fix type annotation errors in service.py
  py/selenium/webdriver/common/service.py
Labels: C-py, Review effort 2/5

#16207 [py] Fix mypy type annotation issues in action_builder
  py/selenium/webdriver/common/actions/action_builder.py
Labels: C-py, Review effort 2/5
