Repository SeleniumHQ/selenium, pull requests merged in 2025-07, with the labels that each got.

#15936 [py][bidi]: add high level API for script module - `pin`, `unpin` and `execute`
  py/selenium/webdriver/common/bidi/script.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_script_tests.py
Labels: C-py, B-devtools, Review effort 4/5

#15988 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5, Possible security concern

#15990 [dotnet][rb][java][js][py] Automated Browser Version Update
  common/repositories.bzl
Labels: B-build, Review effort 2/5, Possible security concern

#15973 [java] Remove deprecated AppCacheStatus enum from the HTML5 package
  java/src/org/openqa/selenium/html5/AppCacheStatus.java
  java/src/org/openqa/selenium/remote/DriverCommand.java
Labels: C-java, Review effort 1/5

#16002 [py] Bump dev dependencies
  py/requirements.txt
  py/requirements_lock.txt
Labels: C-py, Review effort 1/5

#16004 [grid] Add "URI" to the list of sort-by choices on Overview UI
  javascript/grid-ui/src/screens/Overview/Overview.tsx
  javascript/grid-ui/src/tests/components/Overview.test.tsx
Labels: B-grid, Review effort 2/5

#15999 [java] Add @Nullable annotations to Firefox and Gecko driver service
  java/src/org/openqa/selenium/firefox/BUILD.bazel
  java/src/org/openqa/selenium/firefox/FirefoxDriverService.java
  java/src/org/openqa/selenium/firefox/GeckoDriverService.java
Labels: C-java, B-build, Review effort 2/5

#16001 [java] Add @Nullable annotations to InternetExplorerDriverService parameters
  java/src/org/openqa/selenium/ie/InternetExplorerDriverService.java
Labels: C-java, Review effort 2/5

#16012 Fix various typos
  README.md
  py/CHANGES
  py/docs/README.rst
  py/selenium/webdriver/common/virtual_authenticator.py
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py, Review effort 1/5

#14372 [java] JSpecify annotations for By locators
  java/src/org/openqa/selenium/By.java
  java/src/org/openqa/selenium/support/BUILD.bazel
  java/src/org/openqa/selenium/support/ByIdOrName.java
  java/src/org/openqa/selenium/support/pagefactory/ByAll.java
  java/src/org/openqa/selenium/support/pagefactory/ByChained.java
Labels: P-enhancement, Review effort [1-5]: 2

#16017 Fix email address in .mailmap
  .mailmap
Labels: Review effort 1/5

#16019 Fix typos in javascript & rb
  javascript/atoms/html5/database.js
  javascript/atoms/html5/html5_browser.js
  javascript/atoms/html5/storage.js
  javascript/atoms/test/html5/database_test.html
  javascript/atoms/test/opacity_test.html
  javascript/atoms/test/shown_test.html
  javascript/atoms/test/text_table_test.html
  javascript/atoms/test/type_test.html
  javascript/atoms/test/window_size_test.html
  javascript/selenium-webdriver/CHANGES.md
  javascript/selenium-webdriver/bidi/networkTypes.js
  javascript/selenium-webdriver/bidi/protocolType.js
  javascript/selenium-webdriver/example/logging.js
  javascript/selenium-webdriver/io/exec.js
  javascript/selenium-webdriver/remote/index.js
  javascript/selenium-webdriver/test/fedcm/fedcm_test.js
  javascript/selenium-webdriver/testing/index.js
  javascript/webdriver/test/atoms/inject/interactions_test.html
  javascript/webdriver/test/atoms/inject/sql_database_test.html
  rb/CHANGES
  rb/lib/selenium/webdriver/common/wait.rb
  rb/spec/unit/selenium/webdriver/remote/http/default_spec.rb
Labels: C-rb, B-atoms, C-nodejs, B-devtools, Review effort 1/5

#14397 [java] JSpecify annotations for capabilities
  java/src/org/openqa/selenium/Capabilities.java
  java/src/org/openqa/selenium/HasCapabilities.java
  java/src/org/openqa/selenium/ImmutableCapabilities.java
  java/src/org/openqa/selenium/MutableCapabilities.java
  java/src/org/openqa/selenium/PersistentCapabilities.java
Labels: P-enhancement, Review effort [1-5]: 2

#16033 [py] Fix path in unit test so it works cross-platform
  py/test/unit/selenium/webdriver/remote/remote_connection_tests.py
Labels: C-py, Review effort 1/5

#15819 [py][bidi]: implement bidi module - emulation
  py/selenium/webdriver/common/bidi/emulation.py
  py/selenium/webdriver/remote/webdriver.py
  py/test/selenium/webdriver/common/bidi_emulation_tests.py
Labels: C-py, B-devtools, Review effort 3/5

#16003 [py] Allow free_port() to bind to IPv6 if IPv4 is unavailable
  py/selenium/webdriver/common/utils.py
Labels: C-py, Review effort 2/5

#16056 [rust] Update base URL for Edge web driver
  rust/src/edge.rs
Labels: C-rust, Review effort 2/5, B-manager

#16048 [dotnet] Re-pack Selenium Manager as native dependency
  dotnet/src/webdriver/BUILD.bazel
  dotnet/src/webdriver/Selenium.WebDriver.StrongNamed.nuspec
  dotnet/src/webdriver/Selenium.WebDriver.csproj
  dotnet/src/webdriver/Selenium.WebDriver.nuspec
  dotnet/src/webdriver/SeleniumManager.cs
  dotnet/src/webdriver/assets/BUILD.bazel
  dotnet/src/webdriver/assets/Selenium.WebDriver.targets
  dotnet/src/webdriver/assets/nuget/README.md
  dotnet/src/webdriver/assets/nuget/build/netstandard2.0/Selenium.WebDriver.targets
  dotnet/src/webdriver/assets/nuget/buildTransitive/netstandard2.0/Selenium.WebDriver.targets
  dotnet/test/common/Selenium.WebDriver.Common.Tests.csproj
Labels: C-dotnet, B-build, Review effort 4/5

#16069 [build]: update `selenium_manager.bzl` to use latest build
  common/selenium_manager.bzl
Labels: B-build, Review effort 2/5, Possible security concern

#16071 [py] Use pinned browsers for bidi webextension tests
  py/test/selenium/webdriver/common/bidi_webextension_tests.py
Labels: C-py, Review effort 2/5

#16061 [build] Script to update Bazel multitool.lock.json (and update ruff)
  multitool.lock.json
  py/tox.ini
  scripts/update_multitool_binaries.py
Labels: C-py, B-build, Review effort 3/5

#16078 [py] Fix vendor prefix for Edge browser
  py/selenium/webdriver/edge/remote_connection.py
Labels: C-py, Review effort 2/5

#15983 [py][bidi]: support `accept_insecure_certs` and `proxy` parameters in `create_user_context`
  py/selenium/webdriver/common/bidi/browser.py
  py/selenium/webdriver/common/proxy.py
  py/test/selenium/webdriver/common/bidi_browser_tests.py
Labels: C-py, B-devtools, Review effort 3/5

#16079 [py] Encapsulated Geo Location co-ordinates using `getters/setters`
  py/selenium/webdriver/common/bidi/emulation.py
Labels: C-py, B-devtools, Review effort 2/5

#16084 [docs]: Update test website code
  web/BUILD.bazel
  web/bidi/logEntryAdded.html
  web/fedcm/fedcm_async_js.html
  web/formPage.html
  web/logEntryAdded.html
  web/relative_locators.html
  web/service-worker.js
  web/service_worker.html
Labels: Review effort 2/5

#16091 [dotnet] Fix race condition for .net framework when internal tracing enabled
  dotnet/src/webdriver/Remote/HttpCommandExecutor.cs
Labels: C-dotnet, Review effort 2/5

#16098 [dotnet] Enabling Chrome and Edge driver services to set log level
  dotnet/src/webdriver/Chromium/ChromiumDriverLogLevel.cs
  dotnet/src/webdriver/Chromium/ChromiumDriverService.cs
Labels: Review effort 2/5
